/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t divide(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));

uint64_t divide(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a / b);
}

