/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint32_t pack_u32(uint32_t hi __attribute__((unused)), uint32_t lo __attribute__((unused)));
uint32_t unpack_lo(uint32_t word __attribute__((unused)));
uint32_t unpack_hi(uint32_t word __attribute__((unused)));

uint32_t pack_u32(uint32_t hi __attribute__((unused)), uint32_t lo __attribute__((unused))) {
  return ((hi * 65536ULL) + lo);
}

uint32_t unpack_lo(uint32_t word __attribute__((unused))) {
  return (word - ((word / 65536ULL) * 65536ULL));
}

uint32_t unpack_hi(uint32_t word __attribute__((unused))) {
  return (word / 65536ULL);
}

