/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t field_extract(uint64_t val __attribute__((unused)), uint64_t shift __attribute__((unused)), uint64_t width __attribute__((unused)));
uint64_t field_insert(uint64_t val __attribute__((unused)), uint64_t field_val __attribute__((unused)), uint64_t shift __attribute__((unused)), uint64_t width __attribute__((unused)));
uint64_t eth_get_ethertype(uint64_t header_lo __attribute__((unused)), uint64_t header_hi __attribute__((unused)));
uint64_t eth_set_ethertype(uint64_t header_hi __attribute__((unused)), uint64_t ethertype __attribute__((unused)));
uint64_t ip_get_flags(uint64_t flags_frag __attribute__((unused)));
uint64_t ip_get_fragment_offset(uint64_t flags_frag __attribute__((unused)));
uint64_t ip_pack_flags_frag(uint64_t flags __attribute__((unused)), uint64_t frag_offset __attribute__((unused)));
_Bool tcp_get_syn(uint64_t flags __attribute__((unused)));
_Bool tcp_get_ack(uint64_t flags __attribute__((unused)));
_Bool tcp_get_fin(uint64_t flags __attribute__((unused)));
_Bool tcp_get_rst(uint64_t flags __attribute__((unused)));
_Bool tcp_get_psh(uint64_t flags __attribute__((unused)));
uint64_t tcp_set_syn(uint64_t flags __attribute__((unused)));
uint64_t tcp_set_ack(uint64_t flags __attribute__((unused)));
uint64_t tcp_set_fin(uint64_t flags __attribute__((unused)));
uint64_t pci_get_vendor_id(uint64_t config0 __attribute__((unused)));
uint64_t pci_get_device_id(uint64_t config0 __attribute__((unused)));
uint64_t pci_get_command(uint64_t config1 __attribute__((unused)));
uint64_t pci_get_status(uint64_t config1 __attribute__((unused)));
int main();

uint64_t field_extract(uint64_t val __attribute__((unused)), uint64_t shift __attribute__((unused)), uint64_t width __attribute__((unused))) {
  uint64_t mask __attribute__((unused)) = ((1ULL << width) - 1ULL);
  return ((val >> shift) & mask);
}

uint64_t field_insert(uint64_t val __attribute__((unused)), uint64_t field_val __attribute__((unused)), uint64_t shift __attribute__((unused)), uint64_t width __attribute__((unused))) {
  uint64_t mask __attribute__((unused)) = ((1ULL << width) - 1ULL);
  uint64_t cleared __attribute__((unused)) = (val & ((mask << shift) ^ 0xffffffffffffffffULL));
  return (cleared | ((field_val & mask) << shift));
}

uint64_t eth_get_ethertype(uint64_t header_lo __attribute__((unused)), uint64_t header_hi __attribute__((unused))) {
  return (header_hi % 65536ULL);
}

uint64_t eth_set_ethertype(uint64_t header_hi __attribute__((unused)), uint64_t ethertype __attribute__((unused))) {
  return (((header_hi / 65536ULL) * 65536ULL) + ethertype);
}

uint64_t ip_get_flags(uint64_t flags_frag __attribute__((unused))) {
  return ((flags_frag / 8192ULL) % 8ULL);
}

uint64_t ip_get_fragment_offset(uint64_t flags_frag __attribute__((unused))) {
  return (flags_frag % 8192ULL);
}

uint64_t ip_pack_flags_frag(uint64_t flags __attribute__((unused)), uint64_t frag_offset __attribute__((unused))) {
  return ((flags * 8192ULL) + frag_offset);
}

_Bool tcp_get_syn(uint64_t flags __attribute__((unused))) {
  return (((flags >> 1ULL) & 1ULL) == 1ULL);
}

_Bool tcp_get_ack(uint64_t flags __attribute__((unused))) {
  return (((flags >> 4ULL) & 1ULL) == 1ULL);
}

_Bool tcp_get_fin(uint64_t flags __attribute__((unused))) {
  return ((flags & 1ULL) == 1ULL);
}

_Bool tcp_get_rst(uint64_t flags __attribute__((unused))) {
  return (((flags >> 2ULL) & 1ULL) == 1ULL);
}

_Bool tcp_get_psh(uint64_t flags __attribute__((unused))) {
  return (((flags >> 3ULL) & 1ULL) == 1ULL);
}

uint64_t tcp_set_syn(uint64_t flags __attribute__((unused))) {
  return (flags | (1ULL << 1ULL));
}

uint64_t tcp_set_ack(uint64_t flags __attribute__((unused))) {
  return (flags | (1ULL << 4ULL));
}

uint64_t tcp_set_fin(uint64_t flags __attribute__((unused))) {
  return (flags | 1ULL);
}

uint64_t pci_get_vendor_id(uint64_t config0 __attribute__((unused))) {
  return (config0 % 65536ULL);
}

uint64_t pci_get_device_id(uint64_t config0 __attribute__((unused))) {
  return ((config0 / 65536ULL) % 65536ULL);
}

uint64_t pci_get_command(uint64_t config1 __attribute__((unused))) {
  return (config1 % 65536ULL);
}

uint64_t pci_get_status(uint64_t config1 __attribute__((unused))) {
  return ((config1 / 65536ULL) % 65536ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

