/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct IpHeader IpHeader;

typedef struct __attribute__((packed)) IpHeader {
  uint64_t version_ihl;
  uint64_t tos;
  uint64_t total_length;
  uint64_t identification;
  uint64_t flags_fragment;
  uint64_t ttl;
  uint64_t protocol;
  uint64_t checksum;
  uint64_t src_ip;
  uint64_t dst_ip;
} IpHeader;

/* Forward declarations */
IpHeader make_ip_header(uint64_t src __attribute__((unused)), uint64_t dst __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t length __attribute__((unused)));
uint64_t get_protocol(IpHeader hdr __attribute__((unused)));
int main();

IpHeader make_ip_header(uint64_t src __attribute__((unused)), uint64_t dst __attribute__((unused)), uint64_t proto __attribute__((unused)), uint64_t length __attribute__((unused))) {
  return (IpHeader){ .version_ihl = 69ULL, .tos = 0ULL, .total_length = length, .identification = 0ULL, .flags_fragment = 0ULL, .ttl = 64ULL, .protocol = proto, .checksum = 0ULL, .src_ip = src, .dst_ip = dst };
}

uint64_t get_protocol(IpHeader hdr __attribute__((unused))) {
  return hdr.protocol;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

