/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);

/* Forward declarations */
float float_scale(float x __attribute__((unused)), float y __attribute__((unused)));
uint64_t apply_dep(uint64_t f __attribute__((unused)), uint64_t v __attribute__((unused)));
uint64_t forge_double(uint64_t x __attribute__((unused)));
int main();

float float_scale(float x __attribute__((unused)), float y __attribute__((unused))) {
  return (x * y);
}

uint64_t apply_dep(uint64_t f __attribute__((unused)), uint64_t v __attribute__((unused))) {
  return f(v);
}

uint64_t forge_double(uint64_t x __attribute__((unused))) {
  return (x * 2ULL);
}

int main() {
  uint64_t r __attribute__((unused)) = apply_dep(forge_double, 5ULL);
  return (int)(r);

}

