/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_double(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t mod_mul_small(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t is_pow2(uint64_t m __attribute__((unused)));
uint64_t mod_pow2(uint64_t a __attribute__((unused)), uint64_t m __attribute__((unused)));
int main();

uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = (a + b);
  if ((s >= m)) {
    return (s - m);
  } else {
    return s;
  }
}

uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return ((a + m) - b);
  }
}

uint64_t mod_double(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t r __attribute__((unused)) = mod_add(a, a, b);
  return r;
}

uint64_t mod_mul_small(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  return ((a * b) % m);
}

uint64_t is_pow2(uint64_t m __attribute__((unused))) {
  if (((m & (m - 1ULL)) == 0ULL)) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint64_t mod_pow2(uint64_t a __attribute__((unused)), uint64_t m __attribute__((unused))) {
  return (a & (m - 1ULL));
}

int __attribute__((weak)) main() {
  uint64_t m __attribute__((unused)) = 17ULL;
  uint64_t a1 __attribute__((unused)) = mod_add(10ULL, 12ULL, m);
  uint64_t a2 __attribute__((unused)) = mod_sub(5ULL, 11ULL, m);
  uint64_t a3 __attribute__((unused)) = mod_double(9ULL, m);
  uint64_t a4 __attribute__((unused)) = mod_mul_small(6ULL, 7ULL, m);
  uint64_t p1 __attribute__((unused)) = is_pow2(16ULL);
  uint64_t p2 __attribute__((unused)) = is_pow2(12ULL);
  uint64_t p3 __attribute__((unused)) = mod_pow2(255ULL, 16ULL);
  return (int)(((((((a1 + a2) + a3) + a4) + p1) + p2) + p3));

}

