/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t search_step_lo(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t mid __attribute__((unused)));
uint64_t search_step_hi(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t mid __attribute__((unused)));
uint64_t search_mid(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));

uint64_t search_step_lo(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t mid __attribute__((unused))) {
  return (mid + 1ULL);
}

uint64_t search_step_hi(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t mid __attribute__((unused))) {
  return (mid - 1ULL);
}

uint64_t search_mid(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  return (lo + ((hi - lo) / 2ULL));
}

