/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);
typedef float (*forge_fn_f32_u64_u64_ret_f32_t)(float, uint64_t, uint64_t);

__device__ uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t shfl_up_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_or(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_xor(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_and(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_sub(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_exch(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

__device__ uint64_t lane_id(void);  /* extern: forge_gpu */

__device__ uint64_t warp_id(void);  /* extern: forge_gpu */

__device__ float shfl_xor_sync_f32(float val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ float shfl_down_sync_f32(float val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

/* Forward declarations */
static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused)));
uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
__global__ void matmul_16(forge_span_u32_t a __attribute__((unused)), forge_span_u32_t b __attribute__((unused)), forge_span_u32_t c __attribute__((unused)), uint32_t m __attribute__((unused)), uint32_t n __attribute__((unused)));
int main();

static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

__global__ void matmul_16(forge_span_u32_t a __attribute__((unused)), forge_span_u32_t b __attribute__((unused)), forge_span_u32_t c __attribute__((unused)), uint32_t m __attribute__((unused)), uint32_t n __attribute__((unused))) {
  __shared__ uint32_t as_tile[256];
  __shared__ uint32_t bs_tile[256];
  uint32_t x __attribute__((unused)) = threadIdx_x;
  uint32_t y __attribute__((unused)) = threadIdx_y;
  uint32_t col __attribute__((unused)) = ((blockIdx_x * 16ULL) + x);
  uint32_t row __attribute__((unused)) = ((blockIdx_y * 16ULL) + y);
  uint32_t s_idx __attribute__((unused)) = ((y * 16ULL) + x);
  if ((row < m)) {
    uint32_t a_idx __attribute__((unused)) = ((row * 16ULL) + x);
    if ((a_idx < a.len)) {
      as_tile[s_idx] = a.data[a_idx];

    }

  }
  if ((col < n)) {
    uint32_t b_idx __attribute__((unused)) = ((y * n) + col);
    if ((b_idx < b.len)) {
      bs_tile[s_idx] = b.data[b_idx];

    }

  }
  __syncthreads();
  if ((row < m)) {
    if ((col < n)) {
      uint32_t acc __attribute__((unused)) = 0ULL;
      uint32_t ki __attribute__((unused)) = 0ULL;
      {
        while ((ki < 16ULL)) {
          uint32_t a_s __attribute__((unused)) = ((y * 16ULL) + ki);
          uint32_t b_s __attribute__((unused)) = ((ki * 16ULL) + x);
          uint32_t av __attribute__((unused)) = as_tile[a_s];
          uint32_t bv __attribute__((unused)) = bs_tile[b_s];
          acc = (acc + (av * bv));
          ki = (ki + 1ULL);
        }

      }
      uint32_t c_idx __attribute__((unused)) = ((row * n) + col);
      if ((c_idx < c.len)) {
        c.data[c_idx] = acc;

      }

    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

