/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PixelFlags PixelFlags;

typedef struct PixelFlags {
  uint32_t visible : 1;
  uint32_t layer : 4;
  uint32_t palette : 8;
} PixelFlags;

/* Forward declarations */
uint32_t write_visible(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused)));
uint32_t write_layer(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused)));
uint32_t write_palette(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused)));
int main();

uint32_t write_visible(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused))) {
  PixelFlags q __attribute__((unused)) = p;
  q.visible = v;
  return q.visible;
}

uint32_t write_layer(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused))) {
  PixelFlags q __attribute__((unused)) = p;
  q.layer = v;
  return q.layer;
}

uint32_t write_palette(PixelFlags p __attribute__((unused)), uint32_t v __attribute__((unused))) {
  PixelFlags q __attribute__((unused)) = p;
  q.palette = v;
  return q.palette;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

