/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

static const uint32_t M31_P = 2147483647ULL;

/* Forward declarations */
uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_neg(uint32_t a __attribute__((unused)));
uint32_t m31_double(uint32_t a __attribute__((unused)));
uint32_t m31_butterfly_hi(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t w __attribute__((unused)));
uint32_t m31_butterfly_lo(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t w __attribute__((unused)));
uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_is_zero(uint32_t a __attribute__((unused)));
uint32_t qm31_is_zero(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
int main();

uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = (((uint64_t)a) + ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((s >= p)) {
    r = (s - p);
  } else {
    r = s;
  }
  return ((uint32_t)r);
}

uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t a64 __attribute__((unused)) = ((uint64_t)a);
  uint64_t b64 __attribute__((unused)) = ((uint64_t)b);
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((a64 >= b64)) {
    r = (a64 - b64);
  } else {
    r = ((a64 + p) - b64);
  }
  return ((uint32_t)r);
}

uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t prod __attribute__((unused)) = (((uint64_t)a) * ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r __attribute__((unused)) = (prod % p);
  return ((uint32_t)r);
}

uint32_t m31_neg(uint32_t a __attribute__((unused))) {
  if ((a == 0ULL)) {
    return 0ULL;
  } else {
    return (M31_P - a);
  }
}

uint32_t m31_double(uint32_t a __attribute__((unused))) {
  return m31_add(a, a);
}

uint32_t m31_butterfly_hi(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t w __attribute__((unused))) {
  uint32_t t __attribute__((unused)) = m31_mul(w, b);
  /* assert erased */;
  return m31_add(a, t);
}

uint32_t m31_butterfly_lo(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)), uint32_t w __attribute__((unused))) {
  uint32_t t __attribute__((unused)) = m31_mul(w, b);
  return m31_sub(a, t);
}

uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ac __attribute__((unused)) = m31_mul(a_re, b_re);
  uint32_t bd __attribute__((unused)) = m31_mul(a_im, b_im);
  /* assert erased */;
  return m31_sub(ac, bd);
}

uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ad __attribute__((unused)) = m31_mul(a_re, b_im);
  uint32_t bc __attribute__((unused)) = m31_mul(a_im, b_re);
  /* assert erased */;
  return m31_add(ad, bc);
}

uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_add(a_re, b_re);
}

uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_add(a_im, b_im);
}

uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_sub(a_re, b_re);
}

uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_sub(a_im, b_im);
}

uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t dbl __attribute__((unused)) = m31_double(bd_re);
  uint32_t t __attribute__((unused)) = m31_sub(dbl, bd_im);
  /* assert erased */;
  return m31_add(ac_re, t);
}

uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t dbl __attribute__((unused)) = m31_double(bd_im);
  uint32_t t __attribute__((unused)) = m31_add(bd_re, dbl);
  /* assert erased */;
  return m31_add(ac_im, t);
}

uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, d_re, d_im);
  uint32_t bc_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, c_re, c_im);
  /* assert erased */;
  return m31_add(ad_re, bc_re);
}

uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, d_re, d_im);
  uint32_t bc_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, c_re, c_im);
  /* assert erased */;
  return m31_add(ad_im, bc_im);
}

uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t m31_is_zero(uint32_t a __attribute__((unused))) {
  if ((a == 0ULL)) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint32_t qm31_is_zero(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  if (((((a_re == 0ULL) && (a_im == 0ULL)) && (b_re == 0ULL)) && (b_im == 0ULL))) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

