/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t gray_encode(uint64_t n __attribute__((unused)));
uint64_t gray_decode16(uint64_t g __attribute__((unused)));
uint64_t gray_xor_dist(uint64_t n __attribute__((unused)));
uint64_t is_pow2(uint64_t x __attribute__((unused)));
uint64_t gray_check_dist(uint64_t n __attribute__((unused)));
uint64_t gray_roundtrip8(uint64_t n __attribute__((unused)));
uint64_t gray_injective4(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
int main();

uint64_t gray_encode(uint64_t n __attribute__((unused))) {
  return (n ^ (n >> 1ULL));
}

uint64_t gray_decode16(uint64_t g __attribute__((unused))) {
  uint64_t p0 __attribute__((unused)) = (g ^ (g >> 8ULL));
  uint64_t p1 __attribute__((unused)) = (p0 ^ (p0 >> 4ULL));
  uint64_t p2 __attribute__((unused)) = (p1 ^ (p1 >> 2ULL));
  uint64_t p3 __attribute__((unused)) = (p2 ^ (p2 >> 1ULL));
  return (p3 & 65535ULL);
}

uint64_t gray_xor_dist(uint64_t n __attribute__((unused))) {
  uint64_t g0 __attribute__((unused)) = gray_encode(n);
  uint64_t g1 __attribute__((unused)) = gray_encode((n + 1ULL));
  return (g0 ^ g1);
}

uint64_t is_pow2(uint64_t x __attribute__((unused))) {
  if (((x & (x - 1ULL)) == 0ULL)) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint64_t gray_check_dist(uint64_t n __attribute__((unused))) {
  uint64_t dist __attribute__((unused)) = gray_xor_dist(n);
  if (((dist > 0ULL) && ((dist & (dist - 1ULL)) == 0ULL))) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint64_t gray_roundtrip8(uint64_t n __attribute__((unused))) {
  uint64_t g __attribute__((unused)) = gray_encode(n);
  uint64_t p0 __attribute__((unused)) = (g ^ (g >> 4ULL));
  uint64_t p1 __attribute__((unused)) = (p0 ^ (p0 >> 2ULL));
  uint64_t p2 __attribute__((unused)) = (p1 ^ (p1 >> 1ULL));
  return (p2 & 255ULL);
}

uint64_t gray_injective4(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t ga __attribute__((unused)) = gray_encode(a);
  uint64_t gb __attribute__((unused)) = gray_encode(b);
  if ((ga == gb)) {
    if ((a == b)) {
      return 1ULL;
    } else {
      return 0ULL;
    }
  } else {
    if ((a != b)) {
      return 1ULL;
    } else {
      return 0ULL;
    }
  }
}

int __attribute__((weak)) main() {
  uint64_t g0 __attribute__((unused)) = gray_encode(0ULL);
  uint64_t g1 __attribute__((unused)) = gray_encode(1ULL);
  uint64_t g2 __attribute__((unused)) = gray_encode(2ULL);
  uint64_t g3 __attribute__((unused)) = gray_encode(3ULL);
  uint64_t g4 __attribute__((unused)) = gray_encode(4ULL);
  uint64_t g5 __attribute__((unused)) = gray_encode(5ULL);
  uint64_t g6 __attribute__((unused)) = gray_encode(6ULL);
  uint64_t g7 __attribute__((unused)) = gray_encode(7ULL);
  uint64_t sb0 __attribute__((unused)) = gray_check_dist(0ULL);
  uint64_t sb3 __attribute__((unused)) = gray_check_dist(3ULL);
  uint64_t sb7 __attribute__((unused)) = gray_check_dist(7ULL);
  uint64_t rt0 __attribute__((unused)) = gray_roundtrip8(0ULL);
  uint64_t rt5 __attribute__((unused)) = gray_roundtrip8(5ULL);
  uint64_t rt255 __attribute__((unused)) = gray_roundtrip8(255ULL);
  uint64_t inj __attribute__((unused)) = gray_injective4(3ULL, 5ULL);
  return (int)(((((((((((((((g0 + g1) + g2) + g3) + g4) + g5) + g6) + g7) + sb0) + sb3) + sb7) + rt0) + rt5) + rt255) + inj));

}

