/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t countdown(uint64_t n __attribute__((unused)));
uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t isqrt_step(uint64_t n __attribute__((unused)), uint64_t acc __attribute__((unused)));

uint64_t countdown(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    return countdown((n - 1ULL));
  }
}

uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if (((a - ((a / b) * b)) == 0ULL)) {
    return b;
  } else {
    return gcd(b, (a - ((a / b) * b)));
  }
}

uint64_t isqrt_step(uint64_t n __attribute__((unused)), uint64_t acc __attribute__((unused))) {
  if ((n == 0ULL)) {
    return acc;
  } else {
    return isqrt_step((n - 1ULL), (acc + 1ULL));
  }
}

