/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void bubble_sort(forge_span_u64_t s __attribute__((unused)));
int main();

void bubble_sort(forge_span_u64_t s __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    while ((k < n)) {
      uint64_t bound __attribute__((unused)) = ((n - k) - 1ULL);
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < bound)) {
          uint64_t a __attribute__((unused)) = s.data[j];
          uint64_t b __attribute__((unused)) = s.data[(j + 1ULL)];
          uint64_t lo_val;
          if ((a <= b)) {
            lo_val = a;
          } else {
            lo_val = b;
          }
          uint64_t hi_val;
          if ((a <= b)) {
            hi_val = b;
          } else {
            hi_val = a;
          }
          s.data[j] = lo_val;
          s.data[(j + 1ULL)] = hi_val;
          j = (j + 1ULL);
        }

      }
      k = (k + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

