/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void normalize_to_pivot(forge_span_u64_t s __attribute__((unused)), uint64_t pivot __attribute__((unused)));
int main();

void normalize_to_pivot(forge_span_u64_t s __attribute__((unused)), uint64_t pivot __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    while ((k < n)) {
      if ((s.data[k] < pivot)) {
        s.data[k] = 0ULL;

      }
      if ((s.data[k] > pivot)) {
        s.data[k] = (pivot + 1ULL);

      }
      k = (k + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

