/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t count_down(uint64_t x __attribute__((unused)));
uint64_t triangular(uint64_t n __attribute__((unused)));
uint64_t count_down_to_zero(uint64_t x __attribute__((unused)));

uint64_t count_down(uint64_t x __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  {
    while ((v > 0ULL)) {
      v = (v - 1ULL);
    }

  }
  return v;
}

uint64_t triangular(uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i <= n)) {
      acc = (acc + i);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t count_down_to_zero(uint64_t x __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  {
    while ((v > 0ULL)) {
      v = (v - 1ULL);
    }

  }
  return v;
}

