/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Range Range;

typedef struct Range {
  uint64_t lo;
  uint64_t hi;
} Range;

/* Forward declarations */
Range make_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
Range clamp_range(uint64_t v __attribute__((unused)), uint64_t max __attribute__((unused)));
uint64_t in_range(Range r __attribute__((unused)), uint64_t x __attribute__((unused)));
uint64_t range_width(Range r __attribute__((unused)));

Range make_range(uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  return (Range){ .lo = lo, .hi = hi };
}

Range clamp_range(uint64_t v __attribute__((unused)), uint64_t max __attribute__((unused))) {
  if ((v <= max)) {
    return (Range){ .lo = v, .hi = max };
  } else {
    return (Range){ .lo = 0ULL, .hi = max };
  }
}

uint64_t in_range(Range r __attribute__((unused)), uint64_t x __attribute__((unused))) {
  if (((r.lo <= x) && (x <= r.hi))) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint64_t range_width(Range r __attribute__((unused))) {
  return (r.hi - r.lo);
}

