/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t three_way_partition(forge_span_u64_t s __attribute__((unused)), uint64_t pivot __attribute__((unused)));
int main();

__forge_tuple_u64_u64_t three_way_partition(forge_span_u64_t s __attribute__((unused)), uint64_t pivot __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = s.len;
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t mid __attribute__((unused)) = 0ULL;
  uint64_t hi __attribute__((unused)) = n;
  {
    while ((mid < hi)) {
      if ((s.data[mid] < pivot)) {
        uint64_t tmp __attribute__((unused)) = s.data[lo];
        s.data[lo] = s.data[mid];
        s.data[mid] = tmp;
        lo = (lo + 1ULL);
        mid = (mid + 1ULL);

      } else if ((s.data[mid] > pivot)) {
        hi = (hi - 1ULL);
        uint64_t tmp __attribute__((unused)) = s.data[mid];
        s.data[mid] = s.data[hi];
        s.data[hi] = tmp;

      } else {
        mid = (mid + 1ULL);

      }
    }

  }
  return FORGE_AGG(__forge_tuple_u64_u64_t, lo, hi);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

