/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t minmax(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t use_minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
int main();

__forge_tuple_u64_u64_t minmax(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return FORGE_AGG(__forge_tuple_u64_u64_t, a, b);
  } else {
    return FORGE_AGG(__forge_tuple_u64_u64_t, b, a);
  }
}

uint64_t use_minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  __forge_tuple_u64_u64_t __tup_20_4 __attribute__((unused)) = minmax(x, y);
  uint64_t lo __attribute__((unused)) = (__tup_20_4)._0;
  uint64_t hi __attribute__((unused)) = (__tup_20_4)._1;
  return (hi - lo);
}

int main() {
  return (int)(0ULL);

}

