/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
_Bool is_even(uint64_t n __attribute__((unused)));
_Bool is_odd(uint64_t n __attribute__((unused)));
uint64_t ack_a(uint64_t n __attribute__((unused)));
uint64_t ack_b(uint64_t n __attribute__((unused)));

_Bool is_even(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 1;
  } else {
    return is_odd((n - 1ULL));
  }
}

_Bool is_odd(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0;
  } else {
    return is_even((n - 1ULL));
  }
}

uint64_t ack_a(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 1ULL;
  } else {
    return (ack_b((n - 1ULL)) + 1ULL);
  }
}

uint64_t ack_b(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 2ULL;
  } else {
    return (ack_a((n - 1ULL)) + 1ULL);
  }
}

