/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct BoundedCounter BoundedCounter;

typedef struct BoundedCounter {
  uint64_t count;
  uint64_t max;
} BoundedCounter;

/* Forward declarations */
BoundedCounter make_counter(uint64_t limit __attribute__((unused)));
BoundedCounter increment(BoundedCounter c __attribute__((unused)));
int main();

BoundedCounter make_counter(uint64_t limit __attribute__((unused))) {
  return (BoundedCounter){ .count = 0ULL, .max = limit };
}

BoundedCounter increment(BoundedCounter c __attribute__((unused))) {
  return (BoundedCounter){ .count = (c.count + 1ULL), .max = c.max };
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

