/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct RingBuf RingBuf;

typedef struct RingBuf {
  uint64_t head;
  uint64_t tail;
  uint64_t cap;
} RingBuf;

/* Forward declarations */
RingBuf ring_push(RingBuf buf __attribute__((unused)));
RingBuf ring_make(uint64_t capacity __attribute__((unused)));
int main();

RingBuf ring_push(RingBuf buf __attribute__((unused))) {
  uint64_t new_tail __attribute__((unused)) = ((buf.tail + 1ULL) % buf.cap);
  return (RingBuf){ .head = buf.head, .tail = new_tail, .cap = buf.cap };
}

RingBuf ring_make(uint64_t capacity __attribute__((unused))) {
  return (RingBuf){ .head = 0ULL, .tail = 0ULL, .cap = capacity };
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

