/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Utf8Result Utf8Result;

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint8_t* data; uintptr_t len; } forge_span_u8_t;

typedef struct Utf8Result {
  uint64_t codepoint;
  uint64_t len;
  _Bool valid;
} Utf8Result;

/* Forward declarations */
Utf8Result decode_utf8_byte(forge_span_u8_t buf __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t count_ascii(forge_span_u8_t buf __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

Utf8Result decode_utf8_byte(forge_span_u8_t buf __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t b0 __attribute__((unused)) = ((uint64_t)buf.data[0ULL]);
  if ((b0 < 128ULL)) {
    return (Utf8Result){ .codepoint = b0, .len = 1ULL, .valid = 1 };
  } else {
    if ((b0 < 192ULL)) {
      return (Utf8Result){ .codepoint = 0ULL, .len = 1ULL, .valid = 0 };
    } else {
      if ((b0 < 224ULL)) {
        if ((n >= 2ULL)) {
          uint64_t b1 __attribute__((unused)) = ((uint64_t)buf.data[1ULL]);
          uint64_t cp __attribute__((unused)) = (((b0 - 192ULL) * 64ULL) + (b1 % 64ULL));
          return (Utf8Result){ .codepoint = cp, .len = 2ULL, .valid = 1 };
        } else {
          return (Utf8Result){ .codepoint = 0ULL, .len = 1ULL, .valid = 0 };
        }
      } else {
        if ((b0 < 240ULL)) {
          if ((n >= 3ULL)) {
            uint64_t b1 __attribute__((unused)) = ((uint64_t)buf.data[1ULL]);
            uint64_t b2 __attribute__((unused)) = ((uint64_t)buf.data[2ULL]);
            uint64_t cp __attribute__((unused)) = ((((b0 - 224ULL) * 4096ULL) + ((b1 % 64ULL) * 64ULL)) + (b2 % 64ULL));
            return (Utf8Result){ .codepoint = cp, .len = 3ULL, .valid = 1 };
          } else {
            return (Utf8Result){ .codepoint = 0ULL, .len = 1ULL, .valid = 0 };
          }
        } else {
          if ((b0 < 248ULL)) {
            if ((n >= 4ULL)) {
              uint64_t b1 __attribute__((unused)) = ((uint64_t)buf.data[1ULL]);
              uint64_t b2 __attribute__((unused)) = ((uint64_t)buf.data[2ULL]);
              uint64_t b3 __attribute__((unused)) = ((uint64_t)buf.data[3ULL]);
              uint64_t cp __attribute__((unused)) = (((((b0 - 240ULL) * 262144ULL) + ((b1 % 64ULL) * 4096ULL)) + ((b2 % 64ULL) * 64ULL)) + (b3 % 64ULL));
              return (Utf8Result){ .codepoint = cp, .len = 4ULL, .valid = 1 };
            } else {
              return (Utf8Result){ .codepoint = 0ULL, .len = 1ULL, .valid = 0 };
            }
          } else {
            return (Utf8Result){ .codepoint = 0ULL, .len = 1ULL, .valid = 0 };
          }
        }
      }
    }
  }
}

uint64_t count_ascii(forge_span_u8_t buf __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t b __attribute__((unused)) = ((uint64_t)buf.data[i]);
      if ((b < 128ULL)) {
        count = (count + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

