/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t sum_bytes(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused)));
uint64_t byte_scale4(uint8_t b __attribute__((unused)));
uint64_t nibble_shift(uint64_t x __attribute__((unused)));
uint64_t be_encode(uint64_t nibble_hi __attribute__((unused)), uint64_t nibble_lo __attribute__((unused)));
int main();

uint64_t sum_bytes(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = ((uint64_t)a);
  uint64_t y __attribute__((unused)) = ((uint64_t)b);
  return (x + y);
}

uint64_t byte_scale4(uint8_t b __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = ((uint64_t)b);
  return (v * 4ULL);
}

uint64_t nibble_shift(uint64_t x __attribute__((unused))) {
  uint64_t n __attribute__((unused)) = (x % 16ULL);
  return (n * 16ULL);
}

uint64_t be_encode(uint64_t nibble_hi __attribute__((unused)), uint64_t nibble_lo __attribute__((unused))) {
  return ((nibble_hi * 16ULL) + nibble_lo);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

