/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t low4(uint64_t x __attribute__((unused)));
uint64_t low8(uint64_t x __attribute__((unused)));
uint64_t shr4(uint64_t x __attribute__((unused)));
uint64_t upper_nibble_bits(uint64_t x __attribute__((unused)));
uint64_t byte0(uint64_t x __attribute__((unused)));
uint64_t byte1(uint64_t x __attribute__((unused)));
uint64_t byte2(uint64_t x __attribute__((unused)));
uint64_t byte3(uint64_t x __attribute__((unused)));
_Bool mask_le_left(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
int main();

uint64_t low4(uint64_t x __attribute__((unused))) {
  return (x & 15ULL);
}

uint64_t low8(uint64_t x __attribute__((unused))) {
  return (x & 255ULL);
}

uint64_t shr4(uint64_t x __attribute__((unused))) {
  return (x >> 4ULL);
}

uint64_t upper_nibble_bits(uint64_t x __attribute__((unused))) {
  uint64_t shifted __attribute__((unused)) = (x >> 4ULL);
  return (shifted & 15ULL);
}

uint64_t byte0(uint64_t x __attribute__((unused))) {
  return (x & 255ULL);
}

uint64_t byte1(uint64_t x __attribute__((unused))) {
  return ((x >> 8ULL) & 255ULL);
}

uint64_t byte2(uint64_t x __attribute__((unused))) {
  return ((x >> 16ULL) & 255ULL);
}

uint64_t byte3(uint64_t x __attribute__((unused))) {
  return ((x >> 24ULL) & 255ULL);
}

_Bool mask_le_left(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t m __attribute__((unused)) = (a & b);
  return (m <= a);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

