/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Counter Counter;
typedef struct ConnState ConnState;

typedef struct Counter {
  uint64_t value;
  uint64_t max;
} Counter;

typedef struct ConnState {
  uint64_t state;
  uint64_t count;
} ConnState;

/* Forward declarations */
void counter_init(Counter* c __attribute__((unused)), uint64_t max __attribute__((unused)));
void counter_inc(Counter* c __attribute__((unused)));
void counter_reset(Counter* c __attribute__((unused)));
void conn_open(ConnState* c __attribute__((unused)));
void conn_send(ConnState* c __attribute__((unused)));
void conn_close(ConnState* c __attribute__((unused)));
void set_val(uint64_t* v __attribute__((unused)), uint64_t val __attribute__((unused)));
int main();

void counter_init(Counter* c __attribute__((unused)), uint64_t max __attribute__((unused))) {
  (*c).value = 0ULL;
  (*c).max = max;
}

void counter_inc(Counter* c __attribute__((unused))) {
  (*c).value = ((*c).value + 1ULL);
}

void counter_reset(Counter* c __attribute__((unused))) {
  (*c).value = 0ULL;
}

void conn_open(ConnState* c __attribute__((unused))) {
  (*c).state = 1ULL;
}

void conn_send(ConnState* c __attribute__((unused))) {
  (*c).count = ((*c).count + 1ULL);
}

void conn_close(ConnState* c __attribute__((unused))) {
  (*c).state = 2ULL;
}

void set_val(uint64_t* v __attribute__((unused)), uint64_t val __attribute__((unused))) {
  (*v) = val;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

