/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct RingBuf RingBuf;

typedef struct RingBuf {
  uint64_t head;
  uint64_t tail;
  uint64_t count;
  uint64_t cap;
  uint64_t state;
} RingBuf;

/* Forward declarations */
RingBuf rbuf_new(uint64_t cap __attribute__((unused)));
void rbuf_push(RingBuf* b __attribute__((unused)));
void rbuf_pop(RingBuf* b __attribute__((unused)));
uint64_t rbuf_count(RingBuf* b __attribute__((unused)));
uint64_t starts_empty(uint64_t cap __attribute__((unused)));
uint64_t push_one(uint64_t cap __attribute__((unused)));
uint64_t push_pop_count(uint64_t cap __attribute__((unused)));
uint64_t push_pop_state(uint64_t cap __attribute__((unused)));
int main();

RingBuf rbuf_new(uint64_t cap __attribute__((unused))) {
  return (RingBuf){ .head = 0ULL, .tail = 0ULL, .count = 0ULL, .cap = cap, .state = 0ULL };
}

void rbuf_push(RingBuf* b __attribute__((unused))) {
  (*b).tail = (((*b).tail + 1ULL) % (*b).cap);
  (*b).count = ((*b).count + 1ULL);
  (*b).state = (((*b).count == (*b).cap) ? 2ULL : 1ULL);
}

void rbuf_pop(RingBuf* b __attribute__((unused))) {
  (*b).head = (((*b).head + 1ULL) % (*b).cap);
  (*b).count = ((*b).count - 1ULL);
  (*b).state = (((*b).count == 0ULL) ? 0ULL : 1ULL);
}

uint64_t rbuf_count(RingBuf* b __attribute__((unused))) {
  return (*b).count;
}

uint64_t starts_empty(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  return b.state;
}

uint64_t push_one(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  return b.count;
}

uint64_t push_pop_count(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  rbuf_pop((&b));
  return b.count;
}

uint64_t push_pop_state(uint64_t cap __attribute__((unused))) {
  RingBuf b __attribute__((unused)) = rbuf_new(cap);
  rbuf_push((&b));
  rbuf_pop((&b));
  return b.state;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

