/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Point Point;
typedef struct Rect Rect;
typedef struct Segment Segment;

typedef struct Point {
  uint64_t x;
  uint64_t y;
} Point;

typedef struct Rect {
  Point tl;
  Point br;
} Rect;

typedef struct Segment {
  Point start;
  Point end_;
} Segment;

/* Forward declarations */
uint64_t rect_width(Rect r __attribute__((unused)));
uint64_t rect_height(Rect r __attribute__((unused)));
uint64_t rect_area(Rect r __attribute__((unused)));
uint64_t point_in_rect(Point p __attribute__((unused)), Rect r __attribute__((unused)));
uint64_t seg_length_x(Segment s __attribute__((unused)));
uint64_t seg_length_y(Segment s __attribute__((unused)));
int main();

uint64_t rect_width(Rect r __attribute__((unused))) {
  return (r.br.x - r.tl.x);
}

uint64_t rect_height(Rect r __attribute__((unused))) {
  return (r.br.y - r.tl.y);
}

uint64_t rect_area(Rect r __attribute__((unused))) {
  uint64_t w __attribute__((unused)) = (r.br.x - r.tl.x);
  uint64_t h __attribute__((unused)) = (r.br.y - r.tl.y);
  return (w * h);
}

uint64_t point_in_rect(Point p __attribute__((unused)), Rect r __attribute__((unused))) {
  return 1ULL;
}

uint64_t seg_length_x(Segment s __attribute__((unused))) {
  return (s.end_.x - s.start.x);
}

uint64_t seg_length_y(Segment s __attribute__((unused))) {
  return (s.end_.y - s.start.y);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

