/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
_Bool register_lemmas();
uint64_t half_product(uint64_t n __attribute__((unused)));
uint64_t safe_double(uint64_t n __attribute__((unused)));
uint64_t triangle_ge_n(uint64_t n __attribute__((unused)));

_Bool register_lemmas() {
  /* proof erased */;
  return 1;
}

uint64_t half_product(uint64_t n __attribute__((unused))) {
  return ((n * (n + 1ULL)) / 2ULL);
}

uint64_t safe_double(uint64_t n __attribute__((unused))) {
  return (2ULL * n);
}

uint64_t triangle_ge_n(uint64_t n __attribute__((unused))) {
  return ((n * (n + 1ULL)) / 2ULL);
}

