/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct SeqState SeqState;

typedef struct SeqState {
  uint64_t next_seq;
  uint64_t sent;
} SeqState;

/* Forward declarations */
SeqState seq_init();
void seq_send(SeqState* s __attribute__((unused)));
uint64_t one_send_seq();
uint64_t one_send_count();
uint64_t three_sends();
uint64_t seq_equals_count();
int main();

SeqState seq_init() {
  return (SeqState){ .next_seq = 0ULL, .sent = 0ULL };
}

void seq_send(SeqState* s __attribute__((unused))) {
  (*s).next_seq = ((*s).next_seq + 1ULL);
  (*s).sent = ((*s).sent + 1ULL);
}

uint64_t one_send_seq() {
  SeqState s __attribute__((unused)) = seq_init();
  seq_send((&s));
  return s.next_seq;
}

uint64_t one_send_count() {
  SeqState s __attribute__((unused)) = seq_init();
  seq_send((&s));
  return s.sent;
}

uint64_t three_sends() {
  SeqState s __attribute__((unused)) = seq_init();
  seq_send((&s));
  seq_send((&s));
  seq_send((&s));
  return s.next_seq;
}

uint64_t seq_equals_count() {
  SeqState s __attribute__((unused)) = seq_init();
  seq_send((&s));
  seq_send((&s));
  return (s.next_seq - s.sent);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

