/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Account Account;

typedef struct Account {
  uint64_t balance;
  uint64_t txns;
} Account;

/* Forward declarations */
Account acct_new(uint64_t initial __attribute__((unused)));
void acct_deposit(Account* a __attribute__((unused)), uint64_t amount __attribute__((unused)));
void acct_withdraw(Account* a __attribute__((unused)), uint64_t amount __attribute__((unused)));
uint64_t deposit_100();
uint64_t deposit_withdraw();
uint64_t three_txns();
uint64_t net_zero(uint64_t initial __attribute__((unused)), uint64_t x __attribute__((unused)));
int main();

Account acct_new(uint64_t initial __attribute__((unused))) {
  return (Account){ .balance = initial, .txns = 0ULL };
}

void acct_deposit(Account* a __attribute__((unused)), uint64_t amount __attribute__((unused))) {
  (*a).balance = ((*a).balance + amount);
  (*a).txns = ((*a).txns + 1ULL);
}

void acct_withdraw(Account* a __attribute__((unused)), uint64_t amount __attribute__((unused))) {
  (*a).balance = ((*a).balance - amount);
  (*a).txns = ((*a).txns + 1ULL);
}

uint64_t deposit_100() {
  Account a __attribute__((unused)) = acct_new(0ULL);
  acct_deposit((&a), 100ULL);
  return a.balance;
}

uint64_t deposit_withdraw() {
  Account a __attribute__((unused)) = acct_new(0ULL);
  acct_deposit((&a), 100ULL);
  acct_withdraw((&a), 30ULL);
  return a.balance;
}

uint64_t three_txns() {
  Account a __attribute__((unused)) = acct_new(50ULL);
  acct_deposit((&a), 10ULL);
  acct_deposit((&a), 20ULL);
  acct_withdraw((&a), 5ULL);
  return a.txns;
}

uint64_t net_zero(uint64_t initial __attribute__((unused)), uint64_t x __attribute__((unused))) {
  Account a __attribute__((unused)) = acct_new(initial);
  acct_deposit((&a), x);
  acct_withdraw((&a), x);
  return a.balance;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

