/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Sched Sched;

typedef struct Sched {
  uint64_t current;
  uint64_t count;
  uint64_t yields;
} Sched;

/* Forward declarations */
Sched sched_new(uint64_t count __attribute__((unused)));
void sched_yield(Sched* s __attribute__((unused)));
uint64_t yield_once_3tasks();
uint64_t yield_full_cycle();
uint64_t yield_count();
uint64_t count_preserved();
int main();

Sched sched_new(uint64_t count __attribute__((unused))) {
  return (Sched){ .current = 0ULL, .count = count, .yields = 0ULL };
}

void sched_yield(Sched* s __attribute__((unused))) {
  (*s).current = (((*s).current + 1ULL) % (*s).count);
  (*s).yields = ((*s).yields + 1ULL);
}

uint64_t yield_once_3tasks() {
  Sched s __attribute__((unused)) = sched_new(3ULL);
  sched_yield((&s));
  return s.current;
}

uint64_t yield_full_cycle() {
  Sched s __attribute__((unused)) = sched_new(3ULL);
  sched_yield((&s));
  sched_yield((&s));
  sched_yield((&s));
  return s.current;
}

uint64_t yield_count() {
  Sched s __attribute__((unused)) = sched_new(5ULL);
  sched_yield((&s));
  sched_yield((&s));
  sched_yield((&s));
  return s.yields;
}

uint64_t count_preserved() {
  Sched s __attribute__((unused)) = sched_new(4ULL);
  sched_yield((&s));
  sched_yield((&s));
  return s.count;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

