/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Epoch Epoch;

typedef struct Epoch {
  uint64_t epoch;
  uint64_t rollbacks;
} Epoch;

/* Forward declarations */
Epoch epoch_new();
void epoch_commit(Epoch* e __attribute__((unused)));
void epoch_rollback(Epoch* e __attribute__((unused)));
uint64_t one_commit();
uint64_t three_commits();
uint64_t commit_rollback_commit_epoch();
uint64_t commit_rollback_commit_rollbacks();
uint64_t rollback_preserves_epoch();
int main();

Epoch epoch_new() {
  return (Epoch){ .epoch = 0ULL, .rollbacks = 0ULL };
}

void epoch_commit(Epoch* e __attribute__((unused))) {
  (*e).epoch = ((*e).epoch + 1ULL);
}

void epoch_rollback(Epoch* e __attribute__((unused))) {
  (*e).rollbacks = ((*e).rollbacks + 1ULL);
}

uint64_t one_commit() {
  Epoch e __attribute__((unused)) = epoch_new();
  epoch_commit((&e));
  return e.epoch;
}

uint64_t three_commits() {
  Epoch e __attribute__((unused)) = epoch_new();
  epoch_commit((&e));
  epoch_commit((&e));
  epoch_commit((&e));
  return e.epoch;
}

uint64_t commit_rollback_commit_epoch() {
  Epoch e __attribute__((unused)) = epoch_new();
  epoch_commit((&e));
  epoch_rollback((&e));
  epoch_commit((&e));
  return e.epoch;
}

uint64_t commit_rollback_commit_rollbacks() {
  Epoch e __attribute__((unused)) = epoch_new();
  epoch_commit((&e));
  epoch_rollback((&e));
  epoch_commit((&e));
  return e.rollbacks;
}

uint64_t rollback_preserves_epoch() {
  Epoch e __attribute__((unused)) = epoch_new();
  epoch_commit((&e));
  epoch_rollback((&e));
  epoch_rollback((&e));
  return e.epoch;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

