/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PingPong PingPong;

typedef struct PingPong {
  uint64_t pings;
  uint64_t pongs;
  uint64_t turn;
} PingPong;

/* Forward declarations */
PingPong pp_new();
void pp_ping(PingPong* p __attribute__((unused)));
void pp_pong(PingPong* p __attribute__((unused)));
uint64_t one_ping_count();
uint64_t one_ping_turn();
uint64_t one_cycle_pings();
uint64_t one_cycle_pongs();
uint64_t one_cycle_turn();
uint64_t three_cycles_pings();
int main();

PingPong pp_new() {
  return (PingPong){ .pings = 0ULL, .pongs = 0ULL, .turn = 0ULL };
}

void pp_ping(PingPong* p __attribute__((unused))) {
  (*p).pings = ((*p).pings + 1ULL);
  (*p).turn = 1ULL;
}

void pp_pong(PingPong* p __attribute__((unused))) {
  (*p).pongs = ((*p).pongs + 1ULL);
  (*p).turn = 0ULL;
}

uint64_t one_ping_count() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  return p.pings;
}

uint64_t one_ping_turn() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  return p.turn;
}

uint64_t one_cycle_pings() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.pings;
}

uint64_t one_cycle_pongs() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.pongs;
}

uint64_t one_cycle_turn() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  return p.turn;
}

uint64_t three_cycles_pings() {
  PingPong p __attribute__((unused)) = pp_new();
  pp_ping((&p));
  pp_pong((&p));
  pp_ping((&p));
  pp_pong((&p));
  pp_ping((&p));
  pp_pong((&p));
  return p.pings;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

