/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct EventLog EventLog;

typedef struct EventLog {
  uint64_t count;
  uint64_t cap;
  uint64_t flushes;
} EventLog;

/* Forward declarations */
EventLog log_new(uint64_t cap __attribute__((unused)));
void log_append(EventLog* l __attribute__((unused)));
void log_flush(EventLog* l __attribute__((unused)));
uint64_t five_appends(uint64_t cap __attribute__((unused)));
uint64_t append_flush_count(uint64_t cap __attribute__((unused)));
uint64_t append_flush_flushes(uint64_t cap __attribute__((unused)));
uint64_t two_flush_cycles(uint64_t cap __attribute__((unused)));
int main();

EventLog log_new(uint64_t cap __attribute__((unused))) {
  return (EventLog){ .count = 0ULL, .cap = cap, .flushes = 0ULL };
}

void log_append(EventLog* l __attribute__((unused))) {
  (*l).count = ((*l).count + 1ULL);
}

void log_flush(EventLog* l __attribute__((unused))) {
  (*l).count = 0ULL;
  (*l).flushes = ((*l).flushes + 1ULL);
}

uint64_t five_appends(uint64_t cap __attribute__((unused))) {
  EventLog l __attribute__((unused)) = log_new(cap);
  log_append((&l));
  log_append((&l));
  log_append((&l));
  log_append((&l));
  log_append((&l));
  return l.count;
}

uint64_t append_flush_count(uint64_t cap __attribute__((unused))) {
  EventLog l __attribute__((unused)) = log_new(cap);
  log_append((&l));
  log_append((&l));
  log_append((&l));
  log_flush((&l));
  return l.count;
}

uint64_t append_flush_flushes(uint64_t cap __attribute__((unused))) {
  EventLog l __attribute__((unused)) = log_new(cap);
  log_append((&l));
  log_append((&l));
  log_append((&l));
  log_flush((&l));
  return l.flushes;
}

uint64_t two_flush_cycles(uint64_t cap __attribute__((unused))) {
  EventLog l __attribute__((unused)) = log_new(cap);
  log_append((&l));
  log_append((&l));
  log_flush((&l));
  log_append((&l));
  log_flush((&l));
  return l.flushes;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

