/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Semaphore Semaphore;

typedef struct Semaphore {
  uint64_t count;
  uint64_t cap;
} Semaphore;

/* Forward declarations */
Semaphore sem_new(uint64_t cap __attribute__((unused)));
void sem_down(Semaphore* s __attribute__((unused)));
void sem_up(Semaphore* s __attribute__((unused)));
uint64_t initial_count();
uint64_t three_downs();
uint64_t down_up();
uint64_t two_down_one_up(uint64_t cap __attribute__((unused)));
int main();

Semaphore sem_new(uint64_t cap __attribute__((unused))) {
  return (Semaphore){ .count = cap, .cap = cap };
}

void sem_down(Semaphore* s __attribute__((unused))) {
  (*s).count = ((*s).count - 1ULL);
}

void sem_up(Semaphore* s __attribute__((unused))) {
  (*s).count = ((*s).count + 1ULL);
}

uint64_t initial_count() {
  Semaphore s __attribute__((unused)) = sem_new(3ULL);
  return s.count;
}

uint64_t three_downs() {
  Semaphore s __attribute__((unused)) = sem_new(3ULL);
  sem_down((&s));
  sem_down((&s));
  sem_down((&s));
  return s.count;
}

uint64_t down_up() {
  Semaphore s __attribute__((unused)) = sem_new(5ULL);
  sem_down((&s));
  sem_up((&s));
  return s.count;
}

uint64_t two_down_one_up(uint64_t cap __attribute__((unused))) {
  Semaphore s __attribute__((unused)) = sem_new(cap);
  sem_down((&s));
  sem_down((&s));
  sem_up((&s));
  return s.count;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

