/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Ledger Ledger;

typedef struct Ledger {
  uint64_t credits;
  uint64_t debits;
} Ledger;

/* Forward declarations */
Ledger ledger_new();
void ledger_credit(Ledger* l __attribute__((unused)), uint64_t amount __attribute__((unused)));
void ledger_debit(Ledger* l __attribute__((unused)), uint64_t amount __attribute__((unused)));
uint64_t credit_100();
uint64_t credit_debit_balance();
uint64_t multi_ops();
uint64_t net_zero();
int main();

Ledger ledger_new() {
  return (Ledger){ .credits = 0ULL, .debits = 0ULL };
}

void ledger_credit(Ledger* l __attribute__((unused)), uint64_t amount __attribute__((unused))) {
  (*l).credits = ((*l).credits + amount);
}

void ledger_debit(Ledger* l __attribute__((unused)), uint64_t amount __attribute__((unused))) {
  (*l).debits = ((*l).debits + amount);
}

uint64_t credit_100() {
  Ledger l __attribute__((unused)) = ledger_new();
  ledger_credit((&l), 100ULL);
  return l.credits;
}

uint64_t credit_debit_balance() {
  Ledger l __attribute__((unused)) = ledger_new();
  ledger_credit((&l), 200ULL);
  ledger_debit((&l), 50ULL);
  return (l.credits - l.debits);
}

uint64_t multi_ops() {
  Ledger l __attribute__((unused)) = ledger_new();
  ledger_credit((&l), 100ULL);
  ledger_credit((&l), 100ULL);
  ledger_credit((&l), 100ULL);
  ledger_debit((&l), 80ULL);
  ledger_debit((&l), 60ULL);
  return (l.credits - l.debits);
}

uint64_t net_zero() {
  Ledger l __attribute__((unused)) = ledger_new();
  ledger_credit((&l), 50ULL);
  ledger_debit((&l), 50ULL);
  return (l.credits - l.debits);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

