/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Pool Pool;

typedef struct Pool {
  uint64_t free;
  uint64_t used;
  uint64_t total;
} Pool;

/* Forward declarations */
Pool pool_new(uint64_t total __attribute__((unused)));
void pool_alloc(Pool* p __attribute__((unused)));
void pool_free(Pool* p __attribute__((unused)));
uint64_t initial_free();
uint64_t alloc_three_free(uint64_t total __attribute__((unused)));
uint64_t alloc_three_used(uint64_t total __attribute__((unused)));
uint64_t balance_preserved(uint64_t total __attribute__((unused)));
uint64_t alloc_free_cycle();
int main();

Pool pool_new(uint64_t total __attribute__((unused))) {
  return (Pool){ .free = total, .used = 0ULL, .total = total };
}

void pool_alloc(Pool* p __attribute__((unused))) {
  (*p).free = ((*p).free - 1ULL);
  (*p).used = ((*p).used + 1ULL);
}

void pool_free(Pool* p __attribute__((unused))) {
  (*p).used = ((*p).used - 1ULL);
  (*p).free = ((*p).free + 1ULL);
}

uint64_t initial_free() {
  Pool p __attribute__((unused)) = pool_new(5ULL);
  return p.free;
}

uint64_t alloc_three_free(uint64_t total __attribute__((unused))) {
  Pool p __attribute__((unused)) = pool_new(total);
  pool_alloc((&p));
  pool_alloc((&p));
  pool_alloc((&p));
  return p.free;
}

uint64_t alloc_three_used(uint64_t total __attribute__((unused))) {
  Pool p __attribute__((unused)) = pool_new(total);
  pool_alloc((&p));
  pool_alloc((&p));
  pool_alloc((&p));
  return p.used;
}

uint64_t balance_preserved(uint64_t total __attribute__((unused))) {
  Pool p __attribute__((unused)) = pool_new(total);
  pool_alloc((&p));
  pool_alloc((&p));
  pool_alloc((&p));
  pool_free((&p));
  pool_free((&p));
  return (p.free + p.used);
}

uint64_t alloc_free_cycle() {
  Pool p __attribute__((unused)) = pool_new(4ULL);
  pool_alloc((&p));
  pool_alloc((&p));
  pool_alloc((&p));
  pool_alloc((&p));
  pool_free((&p));
  pool_free((&p));
  pool_free((&p));
  pool_free((&p));
  return p.free;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

