/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Device Device;

typedef struct Device {
  uint64_t powered;
  uint64_t initialized;
  uint64_t active;
  uint64_t ops;
} Device;

/* Forward declarations */
Device dev_new();
void dev_power_on(Device* d __attribute__((unused)));
void dev_init(Device* d __attribute__((unused)));
void dev_activate(Device* d __attribute__((unused)));
void dev_deactivate(Device* d __attribute__((unused)));
uint64_t full_startup_active();
uint64_t full_startup_ops();
uint64_t activate_deactivate();
uint64_t four_ops();
int main();

Device dev_new() {
  return (Device){ .powered = 0ULL, .initialized = 0ULL, .active = 0ULL, .ops = 0ULL };
}

void dev_power_on(Device* d __attribute__((unused))) {
  (*d).powered = 1ULL;
  (*d).ops = ((*d).ops + 1ULL);
}

void dev_init(Device* d __attribute__((unused))) {
  (*d).initialized = 1ULL;
  (*d).ops = ((*d).ops + 1ULL);
}

void dev_activate(Device* d __attribute__((unused))) {
  (*d).active = 1ULL;
  (*d).ops = ((*d).ops + 1ULL);
}

void dev_deactivate(Device* d __attribute__((unused))) {
  (*d).active = 0ULL;
  (*d).ops = ((*d).ops + 1ULL);
}

uint64_t full_startup_active() {
  Device d __attribute__((unused)) = dev_new();
  dev_power_on((&d));
  dev_init((&d));
  dev_activate((&d));
  return d.active;
}

uint64_t full_startup_ops() {
  Device d __attribute__((unused)) = dev_new();
  dev_power_on((&d));
  dev_init((&d));
  dev_activate((&d));
  return d.ops;
}

uint64_t activate_deactivate() {
  Device d __attribute__((unused)) = dev_new();
  dev_power_on((&d));
  dev_init((&d));
  dev_activate((&d));
  dev_deactivate((&d));
  return d.active;
}

uint64_t four_ops() {
  Device d __attribute__((unused)) = dev_new();
  dev_power_on((&d));
  dev_init((&d));
  dev_activate((&d));
  dev_deactivate((&d));
  return d.ops;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

