/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Permissions Permissions;

typedef struct Permissions {
  uint64_t count;
  uint64_t cap;
  uint64_t grants;
  uint64_t revokes;
} Permissions;

/* Forward declarations */
Permissions perm_new(uint64_t cap __attribute__((unused)));
void perm_grant(Permissions* p __attribute__((unused)));
void perm_revoke(Permissions* p __attribute__((unused)));
uint64_t grant_three(uint64_t cap __attribute__((unused)));
uint64_t grant3_revoke1(uint64_t cap __attribute__((unused)));
uint64_t grant_revoke_all(uint64_t cap __attribute__((unused)));
uint64_t total_grants(uint64_t cap __attribute__((unused)));
int main();

Permissions perm_new(uint64_t cap __attribute__((unused))) {
  return (Permissions){ .count = 0ULL, .cap = cap, .grants = 0ULL, .revokes = 0ULL };
}

void perm_grant(Permissions* p __attribute__((unused))) {
  (*p).count = ((*p).count + 1ULL);
  (*p).grants = ((*p).grants + 1ULL);
}

void perm_revoke(Permissions* p __attribute__((unused))) {
  (*p).count = ((*p).count - 1ULL);
  (*p).revokes = ((*p).revokes + 1ULL);
}

uint64_t grant_three(uint64_t cap __attribute__((unused))) {
  Permissions p __attribute__((unused)) = perm_new(cap);
  perm_grant((&p));
  perm_grant((&p));
  perm_grant((&p));
  return p.count;
}

uint64_t grant3_revoke1(uint64_t cap __attribute__((unused))) {
  Permissions p __attribute__((unused)) = perm_new(cap);
  perm_grant((&p));
  perm_grant((&p));
  perm_grant((&p));
  perm_revoke((&p));
  return p.count;
}

uint64_t grant_revoke_all(uint64_t cap __attribute__((unused))) {
  Permissions p __attribute__((unused)) = perm_new(cap);
  perm_grant((&p));
  perm_grant((&p));
  perm_grant((&p));
  perm_revoke((&p));
  perm_revoke((&p));
  perm_revoke((&p));
  return p.count;
}

uint64_t total_grants(uint64_t cap __attribute__((unused))) {
  Permissions p __attribute__((unused)) = perm_new(cap);
  perm_grant((&p));
  perm_grant((&p));
  perm_revoke((&p));
  perm_grant((&p));
  perm_grant((&p));
  return p.grants;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

