/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Flow Flow;

typedef struct Flow {
  uint64_t sent;
  uint64_t received;
  uint64_t dropped;
} Flow;

/* Forward declarations */
Flow flow_new();
void flow_send(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused)));
void flow_receive(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused)));
void flow_drop(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t send_100();
uint64_t send_receive();
uint64_t in_flight();
uint64_t multi_send();
int main();

Flow flow_new() {
  return (Flow){ .sent = 0ULL, .received = 0ULL, .dropped = 0ULL };
}

void flow_send(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*f).sent = ((*f).sent + n);
}

void flow_receive(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*f).received = ((*f).received + n);
}

void flow_drop(Flow* f __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*f).dropped = ((*f).dropped + n);
}

uint64_t send_100() {
  Flow f __attribute__((unused)) = flow_new();
  flow_send((&f), 100ULL);
  return f.sent;
}

uint64_t send_receive() {
  Flow f __attribute__((unused)) = flow_new();
  flow_send((&f), 100ULL);
  flow_receive((&f), 80ULL);
  return f.received;
}

uint64_t in_flight() {
  Flow f __attribute__((unused)) = flow_new();
  flow_send((&f), 100ULL);
  flow_receive((&f), 70ULL);
  flow_drop((&f), 20ULL);
  return ((f.sent - f.received) - f.dropped);
}

uint64_t multi_send() {
  Flow f __attribute__((unused)) = flow_new();
  flow_send((&f), 30ULL);
  flow_send((&f), 50ULL);
  flow_send((&f), 20ULL);
  return f.sent;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

