/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct KVSlot KVSlot;

typedef struct KVSlot {
  uint64_t value;
  uint64_t version;
  uint64_t reads;
} KVSlot;

/* Forward declarations */
KVSlot kv_new();
void kv_write(KVSlot* k __attribute__((unused)), uint64_t v __attribute__((unused)));
uint64_t kv_read(KVSlot* k __attribute__((unused)));
uint64_t write_42();
uint64_t two_writes_value();
uint64_t two_writes_version();
uint64_t three_reads();
uint64_t read_returns_value();
int main();

KVSlot kv_new() {
  return (KVSlot){ .value = 0ULL, .version = 0ULL, .reads = 0ULL };
}

void kv_write(KVSlot* k __attribute__((unused)), uint64_t v __attribute__((unused))) {
  (*k).value = v;
  (*k).version = ((*k).version + 1ULL);
}

uint64_t kv_read(KVSlot* k __attribute__((unused))) {
  (*k).reads = ((*k).reads + 1ULL);
  return (*k).value;
}

uint64_t write_42() {
  KVSlot k __attribute__((unused)) = kv_new();
  kv_write((&k), 42ULL);
  return k.value;
}

uint64_t two_writes_value() {
  KVSlot k __attribute__((unused)) = kv_new();
  kv_write((&k), 42ULL);
  kv_write((&k), 99ULL);
  return k.value;
}

uint64_t two_writes_version() {
  KVSlot k __attribute__((unused)) = kv_new();
  kv_write((&k), 42ULL);
  kv_write((&k), 99ULL);
  return k.version;
}

uint64_t three_reads() {
  KVSlot k __attribute__((unused)) = kv_new();
  kv_write((&k), 10ULL);
  kv_read((&k));
  kv_read((&k));
  kv_read((&k));
  return k.reads;
}

uint64_t read_returns_value() {
  KVSlot k __attribute__((unused)) = kv_new();
  kv_write((&k), 77ULL);
  return kv_read((&k));
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

