/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct StreamCursor StreamCursor;

typedef struct StreamCursor {
  uint64_t pos;
  uint64_t mark;
  uint64_t limit;
} StreamCursor;

/* Forward declarations */
StreamCursor cursor_new(uint64_t limit __attribute__((unused)));
void cursor_advance(StreamCursor* c __attribute__((unused)), uint64_t n __attribute__((unused)));
void cursor_set_mark(StreamCursor* c __attribute__((unused)));
void cursor_reset_to_mark(StreamCursor* c __attribute__((unused)));
uint64_t advance_10(uint64_t limit __attribute__((unused)));
uint64_t mark_at_5(uint64_t limit __attribute__((unused)));
uint64_t reset_to_mark(uint64_t limit __attribute__((unused)));
uint64_t reset_and_readvance(uint64_t limit __attribute__((unused)));
int main();

StreamCursor cursor_new(uint64_t limit __attribute__((unused))) {
  return (StreamCursor){ .pos = 0ULL, .mark = 0ULL, .limit = limit };
}

void cursor_advance(StreamCursor* c __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*c).pos = ((*c).pos + n);
}

void cursor_set_mark(StreamCursor* c __attribute__((unused))) {
  (*c).mark = (*c).pos;
}

void cursor_reset_to_mark(StreamCursor* c __attribute__((unused))) {
  (*c).pos = (*c).mark;
}

uint64_t advance_10(uint64_t limit __attribute__((unused))) {
  StreamCursor c __attribute__((unused)) = cursor_new(limit);
  cursor_advance((&c), 10ULL);
  return c.pos;
}

uint64_t mark_at_5(uint64_t limit __attribute__((unused))) {
  StreamCursor c __attribute__((unused)) = cursor_new(limit);
  cursor_advance((&c), 5ULL);
  cursor_set_mark((&c));
  cursor_advance((&c), 3ULL);
  return c.mark;
}

uint64_t reset_to_mark(uint64_t limit __attribute__((unused))) {
  StreamCursor c __attribute__((unused)) = cursor_new(limit);
  cursor_advance((&c), 5ULL);
  cursor_set_mark((&c));
  cursor_advance((&c), 3ULL);
  cursor_reset_to_mark((&c));
  return c.pos;
}

uint64_t reset_and_readvance(uint64_t limit __attribute__((unused))) {
  StreamCursor c __attribute__((unused)) = cursor_new(limit);
  cursor_advance((&c), 5ULL);
  cursor_set_mark((&c));
  cursor_advance((&c), 3ULL);
  cursor_reset_to_mark((&c));
  cursor_advance((&c), 2ULL);
  return c.pos;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

