/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t array_sum(uint64_t* a __attribute__((unused)));
uint64_t dot8(uint64_t* a __attribute__((unused)), uint64_t* b __attribute__((unused)));
uint64_t ct_table_lookup(uint64_t* tbl __attribute__((unused)), uint64_t idx __attribute__((unused)));
uint64_t zeros();
uint64_t run();

uint64_t array_sum(uint64_t* a __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < 8ULL)) {
      s = (s + a[i]);
      i = (i + 1ULL);
    }

  }
  return s;
}

uint64_t dot8(uint64_t* a __attribute__((unused)), uint64_t* b __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < 8ULL)) {
      s = (s + (a[i] * b[i]));
      i = (i + 1ULL);
    }

  }
  return s;
}

uint64_t ct_table_lookup(uint64_t* tbl __attribute__((unused)), uint64_t idx __attribute__((unused))) {
  return tbl[idx];
}

uint64_t zeros() {
  uint64_t z[16] __attribute__((unused)) = { 0 };
  return (z[0ULL] + z[15ULL]);
}

uint64_t run() {
  uint64_t a[8] __attribute__((unused)) = { 1ULL, 2ULL, 3ULL, 4ULL, 5ULL, 6ULL, 7ULL, 8ULL };
  uint64_t b[8] __attribute__((unused)) = { 2ULL, 2ULL, 2ULL, 2ULL, 2ULL, 2ULL, 2ULL, 2ULL };
  uint64_t s __attribute__((unused)) = array_sum(a);
  uint64_t d __attribute__((unused)) = dot8(a, b);
  uint64_t tbl[4] __attribute__((unused)) = { 10ULL, 20ULL, 30ULL, 40ULL };
  uint64_t v __attribute__((unused)) = ct_table_lookup(tbl, 2ULL);
  uint64_t z __attribute__((unused)) = zeros();
  return (((s + d) + v) + z);
}

