/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PowerState PowerState;

typedef struct PowerState {
  uint64_t state;
  uint64_t transitions;
} PowerState;

/* Forward declarations */
PowerState ps_new();
void ps_to_s1(PowerState* p __attribute__((unused)));
void ps_to_s2(PowerState* p __attribute__((unused)));
void ps_to_s3(PowerState* p __attribute__((unused)));
void ps_resume(PowerState* p __attribute__((unused)));
uint64_t enter_s1();
uint64_t deep_sleep();
uint64_t resume_from_s3();
uint64_t sleep_cycle_transitions();
uint64_t resume_from_s1();
int main();

PowerState ps_new() {
  return (PowerState){ .state = 0ULL, .transitions = 0ULL };
}

void ps_to_s1(PowerState* p __attribute__((unused))) {
  (*p).state = 1ULL;
  (*p).transitions = ((*p).transitions + 1ULL);
}

void ps_to_s2(PowerState* p __attribute__((unused))) {
  (*p).state = 2ULL;
  (*p).transitions = ((*p).transitions + 1ULL);
}

void ps_to_s3(PowerState* p __attribute__((unused))) {
  (*p).state = 3ULL;
  (*p).transitions = ((*p).transitions + 1ULL);
}

void ps_resume(PowerState* p __attribute__((unused))) {
  (*p).state = 0ULL;
  (*p).transitions = ((*p).transitions + 1ULL);
}

uint64_t enter_s1() {
  PowerState p __attribute__((unused)) = ps_new();
  ps_to_s1((&p));
  return p.state;
}

uint64_t deep_sleep() {
  PowerState p __attribute__((unused)) = ps_new();
  ps_to_s1((&p));
  ps_to_s2((&p));
  ps_to_s3((&p));
  return p.state;
}

uint64_t resume_from_s3() {
  PowerState p __attribute__((unused)) = ps_new();
  ps_to_s1((&p));
  ps_to_s2((&p));
  ps_to_s3((&p));
  ps_resume((&p));
  return p.state;
}

uint64_t sleep_cycle_transitions() {
  PowerState p __attribute__((unused)) = ps_new();
  ps_to_s1((&p));
  ps_to_s2((&p));
  ps_to_s3((&p));
  ps_resume((&p));
  return p.transitions;
}

uint64_t resume_from_s1() {
  PowerState p __attribute__((unused)) = ps_new();
  ps_to_s1((&p));
  ps_resume((&p));
  return p.state;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

