/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct TxLog TxLog;

typedef struct TxLog {
  uint64_t open;
  uint64_t committed;
  uint64_t aborted;
  uint64_t total;
} TxLog;

/* Forward declarations */
TxLog txlog_new();
void txlog_begin(TxLog* t __attribute__((unused)));
void txlog_commit(TxLog* t __attribute__((unused)));
void txlog_abort(TxLog* t __attribute__((unused)));
uint64_t begin_three_open();
uint64_t commit_two();
uint64_t mixed_ops_open();
uint64_t total_grows();
int main();

TxLog txlog_new() {
  return (TxLog){ .open = 0ULL, .committed = 0ULL, .aborted = 0ULL, .total = 0ULL };
}

void txlog_begin(TxLog* t __attribute__((unused))) {
  (*t).open = ((*t).open + 1ULL);
  (*t).total = ((*t).total + 1ULL);
}

void txlog_commit(TxLog* t __attribute__((unused))) {
  (*t).committed = ((*t).committed + 1ULL);
  (*t).open = ((*t).open - 1ULL);
}

void txlog_abort(TxLog* t __attribute__((unused))) {
  (*t).aborted = ((*t).aborted + 1ULL);
  (*t).open = ((*t).open - 1ULL);
}

uint64_t begin_three_open() {
  TxLog t __attribute__((unused)) = txlog_new();
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_begin((&t));
  return t.open;
}

uint64_t commit_two() {
  TxLog t __attribute__((unused)) = txlog_new();
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_commit((&t));
  txlog_commit((&t));
  return t.committed;
}

uint64_t mixed_ops_open() {
  TxLog t __attribute__((unused)) = txlog_new();
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_commit((&t));
  txlog_abort((&t));
  return t.open;
}

uint64_t total_grows() {
  TxLog t __attribute__((unused)) = txlog_new();
  txlog_begin((&t));
  txlog_begin((&t));
  txlog_commit((&t));
  txlog_begin((&t));
  txlog_abort((&t));
  txlog_begin((&t));
  return t.total;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

