/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct SparseCounter SparseCounter;

typedef struct SparseCounter {
  uint64_t bucket_small;
  uint64_t bucket_large;
  uint64_t threshold;
  uint64_t spills;
} SparseCounter;

/* Forward declarations */
SparseCounter sc_new(uint64_t threshold __attribute__((unused)));
void sc_inc_small(SparseCounter* s __attribute__((unused)));
void sc_spill(SparseCounter* s __attribute__((unused)));
void sc_inc_large(SparseCounter* s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t small_four();
uint64_t spill_large();
uint64_t spill_resets_small();
uint64_t two_spills();
int main();

SparseCounter sc_new(uint64_t threshold __attribute__((unused))) {
  return (SparseCounter){ .bucket_small = 0ULL, .bucket_large = 0ULL, .threshold = threshold, .spills = 0ULL };
}

void sc_inc_small(SparseCounter* s __attribute__((unused))) {
  (*s).bucket_small = ((*s).bucket_small + 1ULL);
}

void sc_spill(SparseCounter* s __attribute__((unused))) {
  (*s).bucket_large = ((*s).bucket_large + (*s).threshold);
  (*s).bucket_small = 0ULL;
  (*s).spills = ((*s).spills + 1ULL);
}

void sc_inc_large(SparseCounter* s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*s).bucket_large = ((*s).bucket_large + n);
}

uint64_t small_four() {
  SparseCounter s __attribute__((unused)) = sc_new(5ULL);
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  return s.bucket_small;
}

uint64_t spill_large() {
  SparseCounter s __attribute__((unused)) = sc_new(5ULL);
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_spill((&s));
  return s.bucket_large;
}

uint64_t spill_resets_small() {
  SparseCounter s __attribute__((unused)) = sc_new(5ULL);
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_spill((&s));
  return s.bucket_small;
}

uint64_t two_spills() {
  SparseCounter s __attribute__((unused)) = sc_new(5ULL);
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_spill((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_inc_small((&s));
  sc_spill((&s));
  return s.bucket_large;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

