/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct ConsensusRound ConsensusRound;

typedef struct ConsensusRound {
  uint64_t yes;
  uint64_t no;
  uint64_t abstain;
  uint64_t participants;
} ConsensusRound;

/* Forward declarations */
ConsensusRound cr_new(uint64_t participants __attribute__((unused)));
void cr_vote_yes(ConsensusRound* r __attribute__((unused)));
void cr_vote_no(ConsensusRound* r __attribute__((unused)));
void cr_vote_abstain(ConsensusRound* r __attribute__((unused)));
uint64_t three_yes();
uint64_t all_vote_total();
uint64_t no_count();
uint64_t participants_preserved();
int main();

ConsensusRound cr_new(uint64_t participants __attribute__((unused))) {
  return (ConsensusRound){ .yes = 0ULL, .no = 0ULL, .abstain = 0ULL, .participants = participants };
}

void cr_vote_yes(ConsensusRound* r __attribute__((unused))) {
  (*r).yes = ((*r).yes + 1ULL);
}

void cr_vote_no(ConsensusRound* r __attribute__((unused))) {
  (*r).no = ((*r).no + 1ULL);
}

void cr_vote_abstain(ConsensusRound* r __attribute__((unused))) {
  (*r).abstain = ((*r).abstain + 1ULL);
}

uint64_t three_yes() {
  ConsensusRound r __attribute__((unused)) = cr_new(5ULL);
  cr_vote_yes((&r));
  cr_vote_yes((&r));
  cr_vote_yes((&r));
  return r.yes;
}

uint64_t all_vote_total() {
  ConsensusRound r __attribute__((unused)) = cr_new(5ULL);
  cr_vote_yes((&r));
  cr_vote_yes((&r));
  cr_vote_yes((&r));
  cr_vote_no((&r));
  cr_vote_abstain((&r));
  return ((r.yes + r.no) + r.abstain);
}

uint64_t no_count() {
  ConsensusRound r __attribute__((unused)) = cr_new(5ULL);
  cr_vote_yes((&r));
  cr_vote_no((&r));
  cr_vote_no((&r));
  return r.no;
}

uint64_t participants_preserved() {
  ConsensusRound r __attribute__((unused)) = cr_new(7ULL);
  cr_vote_yes((&r));
  cr_vote_yes((&r));
  cr_vote_no((&r));
  return r.participants;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

