/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct MerklePath MerklePath;

typedef struct MerklePath {
  uint64_t depth;
  uint64_t siblings;
  uint64_t root_set;
} MerklePath;

/* Forward declarations */
MerklePath mp_new();
void mp_descend(MerklePath* p __attribute__((unused)));
void mp_set_root(MerklePath* p __attribute__((unused)));
uint64_t four_levels_depth();
uint64_t four_levels_siblings();
uint64_t depth_eq_siblings();
uint64_t root_set_after_path();
int main();

MerklePath mp_new() {
  return (MerklePath){ .depth = 0ULL, .siblings = 0ULL, .root_set = 0ULL };
}

void mp_descend(MerklePath* p __attribute__((unused))) {
  (*p).depth = ((*p).depth + 1ULL);
  (*p).siblings = ((*p).siblings + 1ULL);
}

void mp_set_root(MerklePath* p __attribute__((unused))) {
  (*p).root_set = 1ULL;
}

uint64_t four_levels_depth() {
  MerklePath p __attribute__((unused)) = mp_new();
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  return p.depth;
}

uint64_t four_levels_siblings() {
  MerklePath p __attribute__((unused)) = mp_new();
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  return p.siblings;
}

uint64_t depth_eq_siblings() {
  MerklePath p __attribute__((unused)) = mp_new();
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  return (p.depth - p.siblings);
}

uint64_t root_set_after_path() {
  MerklePath p __attribute__((unused)) = mp_new();
  mp_descend((&p));
  mp_descend((&p));
  mp_descend((&p));
  mp_set_root((&p));
  return p.root_set;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

