/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct MidiState MidiState;

typedef struct MidiState {
  uint64_t active;
  uint64_t note_ons;
  uint64_t note_offs;
  uint64_t max_active;
} MidiState;

/* Forward declarations */
MidiState midi_new();
void midi_note_on(MidiState* m __attribute__((unused)));
void midi_note_off(MidiState* m __attribute__((unused)));
uint64_t four_notes_on();
uint64_t chord_partial_release();
uint64_t event_counts();
uint64_t note_off_count();
uint64_t all_released();
int main();

MidiState midi_new() {
  return (MidiState){ .active = 0ULL, .note_ons = 0ULL, .note_offs = 0ULL, .max_active = 128ULL };
}

void midi_note_on(MidiState* m __attribute__((unused))) {
  (*m).active = ((*m).active + 1ULL);
  (*m).note_ons = ((*m).note_ons + 1ULL);
}

void midi_note_off(MidiState* m __attribute__((unused))) {
  (*m).active = ((*m).active - 1ULL);
  (*m).note_offs = ((*m).note_offs + 1ULL);
}

uint64_t four_notes_on() {
  MidiState m __attribute__((unused)) = midi_new();
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_on((&m));
  return m.active;
}

uint64_t chord_partial_release() {
  MidiState m __attribute__((unused)) = midi_new();
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_off((&m));
  midi_note_off((&m));
  return m.active;
}

uint64_t event_counts() {
  MidiState m __attribute__((unused)) = midi_new();
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_off((&m));
  return m.note_ons;
}

uint64_t note_off_count() {
  MidiState m __attribute__((unused)) = midi_new();
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_off((&m));
  midi_note_off((&m));
  return m.note_offs;
}

uint64_t all_released() {
  MidiState m __attribute__((unused)) = midi_new();
  midi_note_on((&m));
  midi_note_on((&m));
  midi_note_off((&m));
  midi_note_off((&m));
  return m.active;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

