/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct CWnd CWnd;

typedef struct CWnd {
  uint64_t cwnd;
  uint64_t ssthresh;
  uint64_t losses;
} CWnd;

/* Forward declarations */
CWnd cwnd_new(uint64_t initial __attribute__((unused)), uint64_t ssthresh __attribute__((unused)));
void cwnd_slow_start(CWnd* c __attribute__((unused)));
void cwnd_cong_avoid(CWnd* c __attribute__((unused)));
void cwnd_loss(CWnd* c __attribute__((unused)));
uint64_t slow_start_doubles();
uint64_t cong_avoid_inc();
uint64_t loss_resets_cwnd();
uint64_t loss_sets_ssthresh();
uint64_t loss_count();
int main();

CWnd cwnd_new(uint64_t initial __attribute__((unused)), uint64_t ssthresh __attribute__((unused))) {
  return (CWnd){ .cwnd = initial, .ssthresh = ssthresh, .losses = 0ULL };
}

void cwnd_slow_start(CWnd* c __attribute__((unused))) {
  (*c).cwnd = ((*c).cwnd * 2ULL);
}

void cwnd_cong_avoid(CWnd* c __attribute__((unused))) {
  (*c).cwnd = ((*c).cwnd + 1ULL);
}

void cwnd_loss(CWnd* c __attribute__((unused))) {
  (*c).ssthresh = ((*c).cwnd / 2ULL);
  (*c).cwnd = 1ULL;
  (*c).losses = ((*c).losses + 1ULL);
}

uint64_t slow_start_doubles() {
  CWnd c __attribute__((unused)) = cwnd_new(1ULL, 16ULL);
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  return c.cwnd;
}

uint64_t cong_avoid_inc() {
  CWnd c __attribute__((unused)) = cwnd_new(1ULL, 16ULL);
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_cong_avoid((&c));
  cwnd_cong_avoid((&c));
  cwnd_cong_avoid((&c));
  cwnd_cong_avoid((&c));
  return c.cwnd;
}

uint64_t loss_resets_cwnd() {
  CWnd c __attribute__((unused)) = cwnd_new(1ULL, 32ULL);
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_loss((&c));
  return c.cwnd;
}

uint64_t loss_sets_ssthresh() {
  CWnd c __attribute__((unused)) = cwnd_new(1ULL, 32ULL);
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_loss((&c));
  return c.ssthresh;
}

uint64_t loss_count() {
  CWnd c __attribute__((unused)) = cwnd_new(1ULL, 32ULL);
  cwnd_slow_start((&c));
  cwnd_slow_start((&c));
  cwnd_loss((&c));
  cwnd_cong_avoid((&c));
  cwnd_cong_avoid((&c));
  cwnd_cong_avoid((&c));
  cwnd_loss((&c));
  return c.losses;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

