/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Debounce Debounce;

typedef struct Debounce {
  uint64_t stable_count;
  uint64_t threshold;
  uint64_t registered;
  uint64_t state;
} Debounce;

/* Forward declarations */
Debounce db_new(uint64_t threshold __attribute__((unused)));
void db_read_pressed(Debounce* d __attribute__((unused)));
void db_register_press(Debounce* d __attribute__((unused)));
void db_read_released(Debounce* d __attribute__((unused)));
uint64_t debounce_register();
uint64_t state_pressed();
uint64_t release_resets();
uint64_t two_presses();
int main();

Debounce db_new(uint64_t threshold __attribute__((unused))) {
  return (Debounce){ .stable_count = 0ULL, .threshold = threshold, .registered = 0ULL, .state = 0ULL };
}

void db_read_pressed(Debounce* d __attribute__((unused))) {
  (*d).stable_count = ((*d).stable_count + 1ULL);
}

void db_register_press(Debounce* d __attribute__((unused))) {
  (*d).registered = ((*d).registered + 1ULL);
  (*d).state = 1ULL;
  (*d).stable_count = ((*d).stable_count + 1ULL);
}

void db_read_released(Debounce* d __attribute__((unused))) {
  (*d).stable_count = 0ULL;
  (*d).state = 0ULL;
}

uint64_t debounce_register() {
  Debounce d __attribute__((unused)) = db_new(4ULL);
  db_read_pressed((&d));
  db_read_pressed((&d));
  db_read_pressed((&d));
  db_register_press((&d));
  return d.registered;
}

uint64_t state_pressed() {
  Debounce d __attribute__((unused)) = db_new(3ULL);
  db_read_pressed((&d));
  db_read_pressed((&d));
  db_register_press((&d));
  return d.state;
}

uint64_t release_resets() {
  Debounce d __attribute__((unused)) = db_new(3ULL);
  db_read_pressed((&d));
  db_read_pressed((&d));
  db_register_press((&d));
  db_read_released((&d));
  return d.stable_count;
}

uint64_t two_presses() {
  Debounce d __attribute__((unused)) = db_new(2ULL);
  db_read_pressed((&d));
  db_register_press((&d));
  db_read_released((&d));
  db_read_pressed((&d));
  db_register_press((&d));
  return d.registered;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

