/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PipelineBuffer PipelineBuffer;

typedef struct PipelineBuffer {
  uint64_t pushed;
  uint64_t popped;
  uint64_t capacity;
  uint64_t stalls;
} PipelineBuffer;

/* Forward declarations */
PipelineBuffer pb_new(uint64_t capacity __attribute__((unused)));
void pb_push(PipelineBuffer* b __attribute__((unused)));
void pb_stall(PipelineBuffer* b __attribute__((unused)));
void pb_pop(PipelineBuffer* b __attribute__((unused)));
uint64_t push_3();
uint64_t push_pop_size();
uint64_t stall_count();
uint64_t total_popped();
int main();

PipelineBuffer pb_new(uint64_t capacity __attribute__((unused))) {
  return (PipelineBuffer){ .pushed = 0ULL, .popped = 0ULL, .capacity = capacity, .stalls = 0ULL };
}

void pb_push(PipelineBuffer* b __attribute__((unused))) {
  (*b).pushed = ((*b).pushed + 1ULL);
}

void pb_stall(PipelineBuffer* b __attribute__((unused))) {
  (*b).stalls = ((*b).stalls + 1ULL);
}

void pb_pop(PipelineBuffer* b __attribute__((unused))) {
  (*b).popped = ((*b).popped + 1ULL);
}

uint64_t push_3() {
  PipelineBuffer b __attribute__((unused)) = pb_new(4ULL);
  pb_push((&b));
  pb_push((&b));
  pb_push((&b));
  return (b.pushed - b.popped);
}

uint64_t push_pop_size() {
  PipelineBuffer b __attribute__((unused)) = pb_new(4ULL);
  pb_push((&b));
  pb_push((&b));
  pb_pop((&b));
  return (b.pushed - b.popped);
}

uint64_t stall_count() {
  PipelineBuffer b __attribute__((unused)) = pb_new(2ULL);
  pb_push((&b));
  pb_push((&b));
  pb_stall((&b));
  pb_pop((&b));
  pb_push((&b));
  pb_stall((&b));
  return b.stalls;
}

uint64_t total_popped() {
  PipelineBuffer b __attribute__((unused)) = pb_new(4ULL);
  pb_push((&b));
  pb_push((&b));
  pb_push((&b));
  pb_pop((&b));
  pb_pop((&b));
  pb_pop((&b));
  return b.popped;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

