/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct RewardPoints RewardPoints;

typedef struct RewardPoints {
  uint64_t earned;
  uint64_t redeemed;
  uint64_t expired;
  uint64_t balance;
} RewardPoints;

/* Forward declarations */
RewardPoints rp_new();
void rp_earn(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused)));
void rp_redeem(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused)));
void rp_expire(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t earn_200();
uint64_t redeem_50();
uint64_t balance_invariant();
uint64_t expire_count();
int main();

RewardPoints rp_new() {
  return (RewardPoints){ .earned = 0ULL, .redeemed = 0ULL, .expired = 0ULL, .balance = 0ULL };
}

void rp_earn(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*r).earned = ((*r).earned + n);
  (*r).balance = ((*r).balance + n);
}

void rp_redeem(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*r).redeemed = ((*r).redeemed + n);
  (*r).balance = ((*r).balance - n);
}

void rp_expire(RewardPoints* r __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*r).expired = ((*r).expired + n);
  (*r).balance = ((*r).balance - n);
}

uint64_t earn_200() {
  RewardPoints r __attribute__((unused)) = rp_new();
  rp_earn((&r), 100ULL);
  rp_earn((&r), 100ULL);
  return r.balance;
}

uint64_t redeem_50() {
  RewardPoints r __attribute__((unused)) = rp_new();
  rp_earn((&r), 200ULL);
  rp_redeem((&r), 50ULL);
  return r.balance;
}

uint64_t balance_invariant() {
  RewardPoints r __attribute__((unused)) = rp_new();
  rp_earn((&r), 300ULL);
  rp_redeem((&r), 100ULL);
  rp_expire((&r), 50ULL);
  return (r.balance - ((r.earned - r.redeemed) - r.expired));
}

uint64_t expire_count() {
  RewardPoints r __attribute__((unused)) = rp_new();
  rp_earn((&r), 200ULL);
  rp_expire((&r), 25ULL);
  rp_expire((&r), 50ULL);
  return r.expired;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

