/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct AlarmManager AlarmManager;

typedef struct AlarmManager {
  uint64_t armed;
  uint64_t triggered;
  uint64_t silenced;
  uint64_t total;
} AlarmManager;

/* Forward declarations */
AlarmManager am_new();
void am_arm(AlarmManager* a __attribute__((unused)));
void am_trigger(AlarmManager* a __attribute__((unused)));
void am_silence(AlarmManager* a __attribute__((unused)));
uint64_t arm_3();
uint64_t trigger_one();
uint64_t silence_count();
uint64_t total_preserved();
int main();

AlarmManager am_new() {
  return (AlarmManager){ .armed = 0ULL, .triggered = 0ULL, .silenced = 0ULL, .total = 0ULL };
}

void am_arm(AlarmManager* a __attribute__((unused))) {
  (*a).armed = ((*a).armed + 1ULL);
  (*a).total = ((*a).total + 1ULL);
}

void am_trigger(AlarmManager* a __attribute__((unused))) {
  (*a).armed = ((*a).armed - 1ULL);
  (*a).triggered = ((*a).triggered + 1ULL);
}

void am_silence(AlarmManager* a __attribute__((unused))) {
  (*a).triggered = ((*a).triggered - 1ULL);
  (*a).silenced = ((*a).silenced + 1ULL);
}

uint64_t arm_3() {
  AlarmManager a __attribute__((unused)) = am_new();
  am_arm((&a));
  am_arm((&a));
  am_arm((&a));
  return a.armed;
}

uint64_t trigger_one() {
  AlarmManager a __attribute__((unused)) = am_new();
  am_arm((&a));
  am_arm((&a));
  am_trigger((&a));
  return a.triggered;
}

uint64_t silence_count() {
  AlarmManager a __attribute__((unused)) = am_new();
  am_arm((&a));
  am_trigger((&a));
  am_silence((&a));
  return a.silenced;
}

uint64_t total_preserved() {
  AlarmManager a __attribute__((unused)) = am_new();
  am_arm((&a));
  am_arm((&a));
  am_arm((&a));
  am_trigger((&a));
  am_silence((&a));
  return a.total;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

