/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct DataPipeline DataPipeline;

typedef struct DataPipeline {
  uint64_t ingested;
  uint64_t accepted;
  uint64_t rejected;
  uint64_t processed;
} DataPipeline;

/* Forward declarations */
DataPipeline dp_new();
void dp_ingest_accept(DataPipeline* d __attribute__((unused)));
void dp_ingest_reject(DataPipeline* d __attribute__((unused)));
void dp_process(DataPipeline* d __attribute__((unused)));
uint64_t ingest_count();
uint64_t conservation();
uint64_t process_count();
uint64_t rejected_not_processed();
int main();

DataPipeline dp_new() {
  return (DataPipeline){ .ingested = 0ULL, .accepted = 0ULL, .rejected = 0ULL, .processed = 0ULL };
}

void dp_ingest_accept(DataPipeline* d __attribute__((unused))) {
  (*d).ingested = ((*d).ingested + 1ULL);
  (*d).accepted = ((*d).accepted + 1ULL);
}

void dp_ingest_reject(DataPipeline* d __attribute__((unused))) {
  (*d).ingested = ((*d).ingested + 1ULL);
  (*d).rejected = ((*d).rejected + 1ULL);
}

void dp_process(DataPipeline* d __attribute__((unused))) {
  (*d).processed = ((*d).processed + 1ULL);
}

uint64_t ingest_count() {
  DataPipeline d __attribute__((unused)) = dp_new();
  dp_ingest_accept((&d));
  dp_ingest_accept((&d));
  dp_ingest_accept((&d));
  dp_ingest_reject((&d));
  return d.ingested;
}

uint64_t conservation() {
  DataPipeline d __attribute__((unused)) = dp_new();
  dp_ingest_accept((&d));
  dp_ingest_reject((&d));
  dp_ingest_accept((&d));
  dp_ingest_reject((&d));
  return ((d.ingested - d.accepted) - d.rejected);
}

uint64_t process_count() {
  DataPipeline d __attribute__((unused)) = dp_new();
  dp_ingest_accept((&d));
  dp_ingest_accept((&d));
  dp_ingest_accept((&d));
  dp_process((&d));
  dp_process((&d));
  return d.processed;
}

uint64_t rejected_not_processed() {
  DataPipeline d __attribute__((unused)) = dp_new();
  dp_ingest_reject((&d));
  dp_ingest_reject((&d));
  dp_ingest_reject((&d));
  return d.rejected;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

