/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct SessionTracker SessionTracker;

typedef struct SessionTracker {
  uint64_t active;
  uint64_t total_sessions;
  uint64_t total_duration;
  uint64_t logouts;
} SessionTracker;

/* Forward declarations */
SessionTracker st_new();
void st_login(SessionTracker* s __attribute__((unused)));
void st_logout(SessionTracker* s __attribute__((unused)), uint64_t duration __attribute__((unused)));
uint64_t three_logins();
uint64_t login_logout();
uint64_t duration_sum();
uint64_t total_sessions();
int main();

SessionTracker st_new() {
  return (SessionTracker){ .active = 0ULL, .total_sessions = 0ULL, .total_duration = 0ULL, .logouts = 0ULL };
}

void st_login(SessionTracker* s __attribute__((unused))) {
  (*s).active = ((*s).active + 1ULL);
  (*s).total_sessions = ((*s).total_sessions + 1ULL);
}

void st_logout(SessionTracker* s __attribute__((unused)), uint64_t duration __attribute__((unused))) {
  (*s).active = ((*s).active - 1ULL);
  (*s).total_duration = ((*s).total_duration + duration);
  (*s).logouts = ((*s).logouts + 1ULL);
}

uint64_t three_logins() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_login((&s));
  return s.active;
}

uint64_t login_logout() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_logout((&s), 100ULL);
  return s.active;
}

uint64_t duration_sum() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_logout((&s), 100ULL);
  st_logout((&s), 150ULL);
  return s.total_duration;
}

uint64_t total_sessions() {
  SessionTracker s __attribute__((unused)) = st_new();
  st_login((&s));
  st_login((&s));
  st_login((&s));
  st_logout((&s), 60ULL);
  return s.total_sessions;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

