/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t divmod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
__forge_tuple_u64_u64_t minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
__forge_tuple_u64_u64_t swap(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
__forge_tuple_u64_u64_t split_at(uint64_t total __attribute__((unused)), uint64_t at __attribute__((unused)));
uint64_t run();

__forge_tuple_u64_u64_t divmod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, (a / b), (a % b));
}

__forge_tuple_u64_u64_t minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  if ((x <= y)) {
    return FORGE_AGG(__forge_tuple_u64_u64_t, x, y);
  } else {
    return FORGE_AGG(__forge_tuple_u64_u64_t, y, x);
  }
}

__forge_tuple_u64_u64_t swap(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, y, x);
}

__forge_tuple_u64_u64_t split_at(uint64_t total __attribute__((unused)), uint64_t at __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, at, (total - at));
}

uint64_t run() {
  __forge_tuple_u64_u64_t dm __attribute__((unused)) = divmod(10ULL, 3ULL);
  uint64_t q __attribute__((unused)) = (dm)._0;
  uint64_t r __attribute__((unused)) = (dm)._1;
  __forge_tuple_u64_u64_t mm __attribute__((unused)) = minmax(7ULL, 2ULL);
  uint64_t lo __attribute__((unused)) = (mm)._0;
  uint64_t hi __attribute__((unused)) = (mm)._1;
  __forge_tuple_u64_u64_t sw __attribute__((unused)) = swap(5ULL, 9ULL);
  uint64_t a __attribute__((unused)) = (sw)._0;
  uint64_t b __attribute__((unused)) = (sw)._1;
  __forge_tuple_u64_u64_t sp __attribute__((unused)) = split_at(20ULL, 8ULL);
  uint64_t left __attribute__((unused)) = (sp)._0;
  uint64_t right __attribute__((unused)) = (sp)._1;
  return (((((((q + r) + lo) + hi) + a) + b) + left) + right);
}

