/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct TapeDrive TapeDrive;

typedef struct TapeDrive {
  uint64_t position;
  uint64_t length;
  uint64_t reads;
  uint64_t writes;
  uint64_t seeks;
} TapeDrive;

/* Forward declarations */
TapeDrive td_new(uint64_t length __attribute__((unused)));
void td_seek_fwd(TapeDrive* t __attribute__((unused)), uint64_t n __attribute__((unused)));
void td_seek_bwd(TapeDrive* t __attribute__((unused)), uint64_t n __attribute__((unused)));
void td_read(TapeDrive* t __attribute__((unused)));
void td_write(TapeDrive* t __attribute__((unused)));
uint64_t seek_fwd();
uint64_t seek_back();
uint64_t reads_tracked();
uint64_t seek_count();
int main();

TapeDrive td_new(uint64_t length __attribute__((unused))) {
  return (TapeDrive){ .position = 0ULL, .length = length, .reads = 0ULL, .writes = 0ULL, .seeks = 0ULL };
}

void td_seek_fwd(TapeDrive* t __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*t).position = ((*t).position + n);
  (*t).seeks = ((*t).seeks + 1ULL);
}

void td_seek_bwd(TapeDrive* t __attribute__((unused)), uint64_t n __attribute__((unused))) {
  (*t).position = ((*t).position - n);
  (*t).seeks = ((*t).seeks + 1ULL);
}

void td_read(TapeDrive* t __attribute__((unused))) {
  (*t).reads = ((*t).reads + 1ULL);
}

void td_write(TapeDrive* t __attribute__((unused))) {
  (*t).writes = ((*t).writes + 1ULL);
}

uint64_t seek_fwd() {
  TapeDrive t __attribute__((unused)) = td_new(100ULL);
  td_seek_fwd((&t), 30ULL);
  return t.position;
}

uint64_t seek_back() {
  TapeDrive t __attribute__((unused)) = td_new(100ULL);
  td_seek_fwd((&t), 30ULL);
  td_seek_bwd((&t), 20ULL);
  return t.position;
}

uint64_t reads_tracked() {
  TapeDrive t __attribute__((unused)) = td_new(100ULL);
  td_seek_fwd((&t), 10ULL);
  td_read((&t));
  td_read((&t));
  td_read((&t));
  return t.reads;
}

uint64_t seek_count() {
  TapeDrive t __attribute__((unused)) = td_new(100ULL);
  td_seek_fwd((&t), 20ULL);
  td_seek_fwd((&t), 10ULL);
  td_seek_bwd((&t), 5ULL);
  return t.seeks;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

