/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PIDIntegral PIDIntegral;

typedef struct PIDIntegral {
  uint64_t integral;
  uint64_t max_integral;
  uint64_t accumulates;
  uint64_t clamps;
  uint64_t resets;
} PIDIntegral;

/* Forward declarations */
PIDIntegral pid_new(uint64_t max __attribute__((unused)));
void pid_accumulate(PIDIntegral* p __attribute__((unused)), uint64_t err __attribute__((unused)));
void pid_clamp(PIDIntegral* p __attribute__((unused)), uint64_t err __attribute__((unused)));
void pid_reset(PIDIntegral* p __attribute__((unused)));
uint64_t accumulate();
uint64_t clamp_at_max();
uint64_t reset_clears();
uint64_t clamp_count();
int main();

PIDIntegral pid_new(uint64_t max __attribute__((unused))) {
  return (PIDIntegral){ .integral = 0ULL, .max_integral = max, .accumulates = 0ULL, .clamps = 0ULL, .resets = 0ULL };
}

void pid_accumulate(PIDIntegral* p __attribute__((unused)), uint64_t err __attribute__((unused))) {
  (*p).integral = ((*p).integral + err);
  (*p).accumulates = ((*p).accumulates + 1ULL);
}

void pid_clamp(PIDIntegral* p __attribute__((unused)), uint64_t err __attribute__((unused))) {
  (*p).integral = (*p).max_integral;
  (*p).clamps = ((*p).clamps + 1ULL);
}

void pid_reset(PIDIntegral* p __attribute__((unused))) {
  (*p).integral = 0ULL;
  (*p).resets = ((*p).resets + 1ULL);
}

uint64_t accumulate() {
  PIDIntegral p __attribute__((unused)) = pid_new(200ULL);
  pid_accumulate((&p), 30ULL);
  pid_accumulate((&p), 20ULL);
  return p.integral;
}

uint64_t clamp_at_max() {
  PIDIntegral p __attribute__((unused)) = pid_new(100ULL);
  pid_accumulate((&p), 80ULL);
  pid_clamp((&p), 50ULL);
  return p.integral;
}

uint64_t reset_clears() {
  PIDIntegral p __attribute__((unused)) = pid_new(100ULL);
  pid_accumulate((&p), 50ULL);
  pid_reset((&p));
  return p.integral;
}

uint64_t clamp_count() {
  PIDIntegral p __attribute__((unused)) = pid_new(100ULL);
  pid_accumulate((&p), 80ULL);
  pid_clamp((&p), 50ULL);
  pid_reset((&p));
  pid_accumulate((&p), 70ULL);
  pid_clamp((&p), 60ULL);
  return p.clamps;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

