/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct VoteQuorum VoteQuorum;

typedef struct VoteQuorum {
  uint64_t voters;
  uint64_t quorum;
  uint64_t yes_votes;
  uint64_t no_votes;
  uint64_t abstentions;
} VoteQuorum;

/* Forward declarations */
VoteQuorum vq_new(uint64_t voters __attribute__((unused)), uint64_t quorum __attribute__((unused)));
void vq_vote_yes(VoteQuorum* v __attribute__((unused)));
void vq_vote_no(VoteQuorum* v __attribute__((unused)));
void vq_abstain(VoteQuorum* v __attribute__((unused)));
uint64_t three_yes();
uint64_t quorum_met();
uint64_t total_votes();
uint64_t no_votes();
int main();

VoteQuorum vq_new(uint64_t voters __attribute__((unused)), uint64_t quorum __attribute__((unused))) {
  return (VoteQuorum){ .voters = voters, .quorum = quorum, .yes_votes = 0ULL, .no_votes = 0ULL, .abstentions = 0ULL };
}

void vq_vote_yes(VoteQuorum* v __attribute__((unused))) {
  (*v).yes_votes = ((*v).yes_votes + 1ULL);
}

void vq_vote_no(VoteQuorum* v __attribute__((unused))) {
  (*v).no_votes = ((*v).no_votes + 1ULL);
}

void vq_abstain(VoteQuorum* v __attribute__((unused))) {
  (*v).abstentions = ((*v).abstentions + 1ULL);
}

uint64_t three_yes() {
  VoteQuorum v __attribute__((unused)) = vq_new(5ULL, 3ULL);
  vq_vote_yes((&v));
  vq_vote_yes((&v));
  vq_vote_yes((&v));
  return v.yes_votes;
}

uint64_t quorum_met() {
  VoteQuorum v __attribute__((unused)) = vq_new(5ULL, 3ULL);
  vq_vote_yes((&v));
  vq_vote_yes((&v));
  vq_vote_yes((&v));
  return v.yes_votes;
}

uint64_t total_votes() {
  VoteQuorum v __attribute__((unused)) = vq_new(5ULL, 3ULL);
  vq_vote_yes((&v));
  vq_vote_yes((&v));
  vq_vote_no((&v));
  vq_abstain((&v));
  vq_vote_no((&v));
  return ((v.yes_votes + v.no_votes) + v.abstentions);
}

uint64_t no_votes() {
  VoteQuorum v __attribute__((unused)) = vq_new(5ULL, 3ULL);
  vq_vote_yes((&v));
  vq_vote_no((&v));
  vq_vote_no((&v));
  return v.no_votes;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

