/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct PowerBudget PowerBudget;

typedef struct PowerBudget {
  uint64_t budget;
  uint64_t cpu_draw;
  uint64_t gpu_draw;
  uint64_t io_draw;
  uint64_t total_draw;
} PowerBudget;

/* Forward declarations */
PowerBudget pb_new(uint64_t budget __attribute__((unused)));
void pb_draw_cpu(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused)));
void pb_draw_gpu(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused)));
void pb_draw_io(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused)));
uint64_t cpu_draw();
uint64_t total_150();
uint64_t gpu_independent();
uint64_t draw_sum();
int main();

PowerBudget pb_new(uint64_t budget __attribute__((unused))) {
  return (PowerBudget){ .budget = budget, .cpu_draw = 0ULL, .gpu_draw = 0ULL, .io_draw = 0ULL, .total_draw = 0ULL };
}

void pb_draw_cpu(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused))) {
  (*p).cpu_draw = ((*p).cpu_draw + w);
  (*p).total_draw = ((*p).total_draw + w);
}

void pb_draw_gpu(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused))) {
  (*p).gpu_draw = ((*p).gpu_draw + w);
  (*p).total_draw = ((*p).total_draw + w);
}

void pb_draw_io(PowerBudget* p __attribute__((unused)), uint64_t w __attribute__((unused))) {
  (*p).io_draw = ((*p).io_draw + w);
  (*p).total_draw = ((*p).total_draw + w);
}

uint64_t cpu_draw() {
  PowerBudget p __attribute__((unused)) = pb_new(300ULL);
  pb_draw_cpu((&p), 50ULL);
  return p.cpu_draw;
}

uint64_t total_150() {
  PowerBudget p __attribute__((unused)) = pb_new(300ULL);
  pb_draw_cpu((&p), 50ULL);
  pb_draw_gpu((&p), 80ULL);
  pb_draw_io((&p), 20ULL);
  return p.total_draw;
}

uint64_t gpu_independent() {
  PowerBudget p __attribute__((unused)) = pb_new(300ULL);
  pb_draw_cpu((&p), 50ULL);
  pb_draw_gpu((&p), 80ULL);
  return p.gpu_draw;
}

uint64_t draw_sum() {
  PowerBudget p __attribute__((unused)) = pb_new(300ULL);
  pb_draw_cpu((&p), 40ULL);
  pb_draw_gpu((&p), 90ULL);
  pb_draw_io((&p), 30ULL);
  return (((p.total_draw - p.cpu_draw) - p.gpu_draw) - p.io_draw);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

