/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t divmod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
__forge_tuple_u64_u64_t minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
__forge_tuple_u64_u64_t swap(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
uint64_t quotient_le(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused)));
uint64_t sorted_sum(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused)));
uint64_t run();

__forge_tuple_u64_u64_t divmod(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, (a / b), (a % b));
}

__forge_tuple_u64_u64_t minmax(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  if ((x <= y)) {
    return FORGE_AGG(__forge_tuple_u64_u64_t, x, y);
  } else {
    return FORGE_AGG(__forge_tuple_u64_u64_t, y, x);
  }
}

__forge_tuple_u64_u64_t swap(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, y, x);
}

uint64_t quotient_le(uint64_t n __attribute__((unused)), uint64_t d __attribute__((unused))) {
  __forge_tuple_u64_u64_t __tup_42_4 __attribute__((unused)) = divmod(n, d);
  uint64_t q __attribute__((unused)) = (__tup_42_4)._0;
  uint64_t r __attribute__((unused)) = (__tup_42_4)._1;
  return q;
}

uint64_t sorted_sum(uint64_t x __attribute__((unused)), uint64_t y __attribute__((unused))) {
  __forge_tuple_u64_u64_t __tup_52_4 __attribute__((unused)) = minmax(x, y);
  uint64_t lo __attribute__((unused)) = (__tup_52_4)._0;
  uint64_t hi __attribute__((unused)) = (__tup_52_4)._1;
  return (lo + hi);
}

uint64_t run() {
  __forge_tuple_u64_u64_t __tup_62_4 __attribute__((unused)) = divmod(17ULL, 5ULL);
  uint64_t q __attribute__((unused)) = (__tup_62_4)._0;
  uint64_t r __attribute__((unused)) = (__tup_62_4)._1;
  __forge_tuple_u64_u64_t __tup_66_4 __attribute__((unused)) = minmax(9ULL, 4ULL);
  uint64_t lo __attribute__((unused)) = (__tup_66_4)._0;
  uint64_t hi __attribute__((unused)) = (__tup_66_4)._1;
  __forge_tuple_u64_u64_t __tup_70_4 __attribute__((unused)) = swap(10ULL, 20ULL);
  uint64_t a __attribute__((unused)) = (__tup_70_4)._0;
  uint64_t b __attribute__((unused)) = (__tup_70_4)._1;
  __forge_tuple_u64_u64_t __tup_74_4 __attribute__((unused)) = minmax(q, r);
  uint64_t s __attribute__((unused)) = (__tup_74_4)._0;
  uint64_t t __attribute__((unused)) = (__tup_74_4)._1;
  return (((((((q + r) + lo) + hi) + a) + b) + s) + t);
}

