/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Node Node;

typedef struct Node {
  uint64_t val;
  uint64_t next;
} Node;

/* Tuple typedefs */
typedef struct { uint64_t _0; Node* _1; } __forge_tuple_u64_own_Node_t;
typedef struct { Node _0; Node* _1; } __forge_tuple_Node_own_Node_t;

/* own<T> heap helpers (linear ownership) */
static inline Node* __forge_own_alloc_Node(Node __val) { Node* __p = (Node*)malloc(sizeof(Node)); if (!__p) { abort(); } *__p = __val; return __p; }
static inline Node  __forge_own_into_Node(Node* __p) { Node __v = *__p; free(__p); return __v; }
static inline __forge_tuple_Node_own_Node_t __forge_own_get_Node(Node* __p) { return (__forge_tuple_Node_own_Node_t){ ._0 = *__p, ._1 = __p }; }

/* Forward declarations */
Node* node_new(uint64_t v __attribute__((unused)));
__forge_tuple_u64_own_Node_t node_val(Node* p __attribute__((unused)));
uint64_t node_free(Node* p __attribute__((unused)));
uint64_t node_sum2(Node* p1 __attribute__((unused)), Node* p2 __attribute__((unused)));
uint64_t run();

Node* node_new(uint64_t v __attribute__((unused))) {
  Node n __attribute__((unused)) = (Node){ .val = v, .next = 0ULL };
  return __forge_own_alloc_Node(n);
}

__forge_tuple_u64_own_Node_t node_val(Node* p __attribute__((unused))) {
  __forge_tuple_Node_own_Node_t __tup_35_4 __attribute__((unused)) = __forge_own_get_Node(p);
  Node n __attribute__((unused)) = (__tup_35_4)._0;
  Node* q __attribute__((unused)) = (__tup_35_4)._1;
  return FORGE_AGG(__forge_tuple_u64_own_Node_t, n.val, q);
}

uint64_t node_free(Node* p __attribute__((unused))) {
  __forge_tuple_Node_own_Node_t __tup_43_4 __attribute__((unused)) = __forge_own_get_Node(p);
  Node n __attribute__((unused)) = (__tup_43_4)._0;
  Node* q __attribute__((unused)) = (__tup_43_4)._1;
  uint64_t v __attribute__((unused)) = n.val;
  (free(q), (void)0);
  return v;
}

uint64_t node_sum2(Node* p1 __attribute__((unused)), Node* p2 __attribute__((unused))) {
  uint64_t v1 __attribute__((unused)) = node_free(p1);
  uint64_t v2 __attribute__((unused)) = node_free(p2);
  return (v1 + v2);
}

uint64_t run() {
  Node* a __attribute__((unused)) = node_new(10ULL);
  Node* b __attribute__((unused)) = node_new(32ULL);
  __forge_tuple_u64_own_Node_t __tup_67_4 __attribute__((unused)) = node_val(a);
  uint64_t va __attribute__((unused)) = (__tup_67_4)._0;
  Node* a2 __attribute__((unused)) = (__tup_67_4)._1;
  __forge_tuple_u64_own_Node_t __tup_70_4 __attribute__((unused)) = node_val(b);
  uint64_t vb __attribute__((unused)) = (__tup_70_4)._0;
  Node* b2 __attribute__((unused)) = (__tup_70_4)._1;
  (free(a2), (void)0);
  (free(b2), (void)0);
  return (va + vb);
}

