/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint8_t safe_add_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused)));
uint8_t safe_sub_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused)));
uint8_t half_u8(uint8_t v __attribute__((unused)));
uint8_t triple_clamped(uint8_t v __attribute__((unused)));
uint8_t distance_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused)));
uint8_t avg_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused)));
uint8_t check_safe_add();
uint8_t check_safe_sub();
uint8_t check_half_200();
uint8_t check_triple_50();
uint8_t check_distance_10_5();
uint8_t check_distance_5_10();
int main();

uint8_t safe_add_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused))) {
  return (a + b);
}

uint8_t safe_sub_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused))) {
  return (a - b);
}

uint8_t half_u8(uint8_t v __attribute__((unused))) {
  return (v / 2ULL);
}

uint8_t triple_clamped(uint8_t v __attribute__((unused))) {
  return ((v + v) + v);
}

uint8_t distance_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused))) {
  if ((a >= b)) {
    return (a - b);
  } else {
    return (b - a);
  }
}

uint8_t avg_u8(uint8_t a __attribute__((unused)), uint8_t b __attribute__((unused))) {
  return ((a / 2ULL) + (b / 2ULL));
}

uint8_t check_safe_add() {
  return safe_add_u8(150ULL, 50ULL);
}

uint8_t check_safe_sub() {
  return safe_sub_u8(200ULL, 100ULL);
}

uint8_t check_half_200() {
  return half_u8(200ULL);
}

uint8_t check_triple_50() {
  return triple_clamped(50ULL);
}

uint8_t check_distance_10_5() {
  return distance_u8(10ULL, 5ULL);
}

uint8_t check_distance_5_10() {
  return distance_u8(5ULL, 10ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

