/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t div_floor(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t rem_bound(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_divisible(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t align_down(uint64_t v __attribute__((unused)), uint64_t align __attribute__((unused)));
uint64_t align_up(uint64_t v __attribute__((unused)), uint64_t align __attribute__((unused)));
uint64_t check_div_floor_10_3();
uint64_t check_rem_10_3();
_Bool check_divisible_12_4();
_Bool check_not_divisible_10_3();
uint64_t check_align_down_10_4();
uint64_t check_align_up_9_4();
uint64_t check_align_up_exact();
int main();

uint64_t div_floor(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a / b);
}

uint64_t rem_bound(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a % b);
}

_Bool is_divisible(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return ((a % b) == 0ULL);
}

uint64_t align_down(uint64_t v __attribute__((unused)), uint64_t align __attribute__((unused))) {
  return ((v / align) * align);
}

uint64_t align_up(uint64_t v __attribute__((unused)), uint64_t align __attribute__((unused))) {
  return ((((v + align) - 1ULL) / align) * align);
}

uint64_t check_div_floor_10_3() {
  return div_floor(10ULL, 3ULL);
}

uint64_t check_rem_10_3() {
  return rem_bound(10ULL, 3ULL);
}

_Bool check_divisible_12_4() {
  return is_divisible(12ULL, 4ULL);
}

_Bool check_not_divisible_10_3() {
  return is_divisible(10ULL, 3ULL);
}

uint64_t check_align_down_10_4() {
  return align_down(10ULL, 4ULL);
}

uint64_t check_align_up_9_4() {
  return align_up(9ULL, 4ULL);
}

uint64_t check_align_up_exact() {
  return align_up(8ULL, 4ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

