/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Counter Counter;

typedef struct Counter {
  uint64_t value;
  uint64_t max;
} Counter;

/* Forward declarations */
Counter counter_new(uint64_t max __attribute__((unused)));
void counter_inc(Counter* c __attribute__((unused)));
void counter_dec(Counter* c __attribute__((unused)));
void counter_reset(Counter* c __attribute__((unused)));
_Bool counter_at_max(const Counter* c __attribute__((unused)));
uint64_t counter_value(const Counter* c __attribute__((unused)));
int main();

Counter counter_new(uint64_t max __attribute__((unused))) {
  return (Counter){ .value = 0ULL, .max = max };
}

void counter_inc(Counter* c __attribute__((unused))) {
  if (((*c).value < (*c).max)) {
    (*c).value = ((*c).value + 1ULL);

  }
}

void counter_dec(Counter* c __attribute__((unused))) {
  if (((*c).value > 0ULL)) {
    (*c).value = ((*c).value - 1ULL);

  }
}

void counter_reset(Counter* c __attribute__((unused))) {
  (*c).value = 0ULL;
}

_Bool counter_at_max(const Counter* c __attribute__((unused))) {
  return ((*c).value == (*c).max);
}

uint64_t counter_value(const Counter* c __attribute__((unused))) {
  return (*c).value;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

