/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t mat_get(forge_span_u64_t m __attribute__((unused)), uint64_t idx __attribute__((unused)));
void mat_set(forge_span_u64_t m __attribute__((unused)), uint64_t idx __attribute__((unused)), uint64_t v __attribute__((unused)));
void mat_zero_n(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t row_start __attribute__((unused)), uint64_t cols __attribute__((unused)));
uint64_t mat_col_max(forge_span_u64_t m __attribute__((unused)), uint64_t col __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t rows __attribute__((unused)));
int main();

uint64_t mat_get(forge_span_u64_t m __attribute__((unused)), uint64_t idx __attribute__((unused))) {
  return m.data[idx];
}

void mat_set(forge_span_u64_t m __attribute__((unused)), uint64_t idx __attribute__((unused)), uint64_t v __attribute__((unused))) {
  m.data[idx] = v;
}

void mat_zero_n(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      m.data[i] = 0ULL;
      i = (i + 1ULL);
    }

  }
}

uint64_t mat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t row_start __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t c __attribute__((unused)) = 0ULL;
  {
    while ((c < cols)) {
      acc = (acc + m.data[(row_start + c)]);
      c = (c + 1ULL);
    }

  }
  return acc;
}

uint64_t mat_col_max(forge_span_u64_t m __attribute__((unused)), uint64_t col __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t rows __attribute__((unused))) {
  uint64_t mx __attribute__((unused)) = m.data[col];
  uint64_t r __attribute__((unused)) = 1ULL;
  {
    while ((r < rows)) {
      uint64_t v __attribute__((unused)) = m.data[(col + (r * cols))];
      if ((v > mx)) {
        mx = v;

      }
      r = (r + 1ULL);
    }

  }
  return mx;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

