/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t span_sum(forge_span_u64_t s __attribute__((unused)));
uint64_t span_count_above(forge_span_u64_t s __attribute__((unused)), uint64_t threshold __attribute__((unused)));
_Bool span_contains(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t span_or_all(forge_span_u64_t s __attribute__((unused)));
uint64_t span_and_all(forge_span_u64_t s __attribute__((unused)));
_Bool span_all_le(forge_span_u64_t s __attribute__((unused)), uint64_t bound __attribute__((unused)));
uint64_t run();

uint64_t span_sum(forge_span_u64_t s __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        acc = (acc + x);
      }
    }

  }
  return acc;
}

uint64_t span_count_above(forge_span_u64_t s __attribute__((unused)), uint64_t threshold __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        if ((x > threshold)) {
          count = (count + 1ULL);
        }
      }
    }

  }
  return count;
}

_Bool span_contains(forge_span_u64_t s __attribute__((unused)), uint64_t target __attribute__((unused))) {
  _Bool found __attribute__((unused)) = 0;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        if ((x == target)) {
          found = 1;
        }
      }
    }

  }
  return found;
}

uint64_t span_or_all(forge_span_u64_t s __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        acc = (acc | x);
      }
    }

  }
  return acc;
}

uint64_t span_and_all(forge_span_u64_t s __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0xffffffffffffffffULL;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        acc = (acc & x);
      }
    }

  }
  return acc;
}

_Bool span_all_le(forge_span_u64_t s __attribute__((unused)), uint64_t bound __attribute__((unused))) {
  _Bool ok __attribute__((unused)) = 1;
  {
    { forge_span_u64_t __span_x = s;
      for (uint64_t __i_x = 0; __i_x < __span_x.len; __i_x++) {
        uint64_t x __attribute__((unused)) = __span_x.data[__i_x];
        if ((x > bound)) {
          ok = 0;
        }
      }
    }

  }
  return ok;
}

uint64_t run() {
  return 0ULL;
}

