/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t gcd_loop(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
_Bool is_coprime(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t check_gcd_same();
uint64_t check_gcd_pos();
uint64_t check_loop_pos();
int main();

uint64_t gcd(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a == b)) {
    return a;
  } else {
    if ((a > b)) {
      return gcd((a - b), b);
    } else {
      return gcd(a, (b - a));
    }
  }
}

uint64_t gcd_loop(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = a;
  uint64_t y __attribute__((unused)) = b;
  {
    while ((x != y)) {
      _Bool go_x __attribute__((unused)) = (x > y);
      if (go_x) {
        x = (x - y);

      } else {
        y = (y - x);

      }
    }

  }
  return x;
}

_Bool is_coprime(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (gcd(a, b) == 1ULL);
}

uint64_t check_gcd_same() {
  return gcd(5ULL, 5ULL);
}

uint64_t check_gcd_pos() {
  return gcd_loop(12ULL, 8ULL);
}

uint64_t check_loop_pos() {
  return gcd_loop(9ULL, 6ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

