/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t popcount_loop(uint64_t x __attribute__((unused)));
uint64_t popcount_kernighan(uint64_t x __attribute__((unused)));
uint64_t parity_bit(uint64_t x __attribute__((unused)));
_Bool has_exactly_one_bit(uint64_t x __attribute__((unused)));
uint64_t check_popcount_0();
uint64_t check_popcount_1();
uint64_t check_popcount_255();
uint64_t check_kernighan_0();
uint64_t check_kernighan_1();
uint64_t check_parity_0();
int main();

uint64_t popcount_loop(uint64_t x __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  uint64_t c __attribute__((unused)) = 0ULL;
  {
    while ((v > 0ULL)) {
      c = (c + (v & 1ULL));
      v = (v >> 1ULL);
    }

  }
  return c;
}

uint64_t popcount_kernighan(uint64_t x __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  uint64_t c __attribute__((unused)) = 0ULL;
  {
    while ((v > 0ULL)) {
      v = (v & (v - 1ULL));
      c = (c + 1ULL);
    }

  }
  return c;
}

uint64_t parity_bit(uint64_t x __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = popcount_loop(x);
  return (cnt % 2ULL);
}

_Bool has_exactly_one_bit(uint64_t x __attribute__((unused))) {
  return ((x & (x - 1ULL)) == 0ULL);
}

uint64_t check_popcount_0() {
  return popcount_loop(0ULL);
}

uint64_t check_popcount_1() {
  return popcount_loop(1ULL);
}

uint64_t check_popcount_255() {
  return popcount_loop(255ULL);
}

uint64_t check_kernighan_0() {
  return popcount_kernighan(0ULL);
}

uint64_t check_kernighan_1() {
  return popcount_kernighan(1ULL);
}

uint64_t check_parity_0() {
  return parity_bit(0ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

