/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Queue Queue;

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

typedef struct Queue {
  forge_span_u64_t data;
  uint64_t head;
  uint64_t tail;
  uint64_t size;
  uint64_t cap;
} Queue;

/* Forward declarations */
Queue queue_new(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)));
_Bool queue_is_empty(const Queue* q __attribute__((unused)));
_Bool queue_is_full(const Queue* q __attribute__((unused)));
void queue_enqueue(Queue* q __attribute__((unused)), uint64_t v __attribute__((unused)));
uint64_t queue_dequeue(Queue* q __attribute__((unused)));
uint64_t queue_size(const Queue* q __attribute__((unused)));
int main();

Queue queue_new(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return (Queue){ .data = buf, .head = 0ULL, .tail = 0ULL, .size = 0ULL, .cap = cap };
}

_Bool queue_is_empty(const Queue* q __attribute__((unused))) {
  return ((*q).size == 0ULL);
}

_Bool queue_is_full(const Queue* q __attribute__((unused))) {
  return ((*q).size == (*q).cap);
}

void queue_enqueue(Queue* q __attribute__((unused)), uint64_t v __attribute__((unused))) {
  (*q).data.data[(*q).tail] = v;
  (*q).tail = (((*q).tail + 1ULL) % (*q).cap);
  (*q).size = ((*q).size + 1ULL);
}

uint64_t queue_dequeue(Queue* q __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = (*q).data.data[(*q).head];
  (*q).head = (((*q).head + 1ULL) % (*q).cap);
  (*q).size = ((*q).size - 1ULL);
  return v;
}

uint64_t queue_size(const Queue* q __attribute__((unused))) {
  return (*q).size;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

