/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t bswap16(uint64_t v __attribute__((unused)));
uint64_t bswap32(uint64_t v __attribute__((unused)));
uint64_t bswap64(uint64_t v __attribute__((unused)));
void bswap_span(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t check_bswap16_zero();
uint64_t check_bswap32_zero();
uint64_t check_bswap16_bounds();
uint64_t check_bswap32_bounds();
int main();

uint64_t bswap16(uint64_t v __attribute__((unused))) {
  return (((v & 255ULL) << 8ULL) | ((v >> 8ULL) & 255ULL));
}

uint64_t bswap32(uint64_t v __attribute__((unused))) {
  uint64_t b0 __attribute__((unused)) = (v & 255ULL);
  uint64_t b1 __attribute__((unused)) = ((v >> 8ULL) & 255ULL);
  uint64_t b2 __attribute__((unused)) = ((v >> 16ULL) & 255ULL);
  uint64_t b3 __attribute__((unused)) = ((v >> 24ULL) & 255ULL);
  return ((((b0 << 24ULL) | (b1 << 16ULL)) | (b2 << 8ULL)) | b3);
}

uint64_t bswap64(uint64_t v __attribute__((unused))) {
  uint64_t b0 __attribute__((unused)) = (v & 255ULL);
  uint64_t b1 __attribute__((unused)) = ((v >> 8ULL) & 255ULL);
  uint64_t b2 __attribute__((unused)) = ((v >> 16ULL) & 255ULL);
  uint64_t b3 __attribute__((unused)) = ((v >> 24ULL) & 255ULL);
  uint64_t b4 __attribute__((unused)) = ((v >> 32ULL) & 255ULL);
  uint64_t b5 __attribute__((unused)) = ((v >> 40ULL) & 255ULL);
  uint64_t b6 __attribute__((unused)) = ((v >> 48ULL) & 255ULL);
  uint64_t b7 __attribute__((unused)) = ((v >> 56ULL) & 255ULL);
  return ((((((((b0 << 56ULL) | (b1 << 48ULL)) | (b2 << 40ULL)) | (b3 << 32ULL)) | (b4 << 24ULL)) | (b5 << 16ULL)) | (b6 << 8ULL)) | b7);
}

void bswap_span(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      s.data[i] = bswap64(s.data[i]);
      i = (i + 1ULL);
    }

  }
}

uint64_t check_bswap16_zero() {
  return bswap16(0ULL);
}

uint64_t check_bswap32_zero() {
  return bswap32(0ULL);
}

uint64_t check_bswap16_bounds() {
  return bswap16(4660ULL);
}

uint64_t check_bswap32_bounds() {
  return bswap32(305419896ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

