/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t heap_parent(uint64_t i __attribute__((unused)));
uint64_t heap_left(uint64_t i __attribute__((unused)));
uint64_t heap_right(uint64_t i __attribute__((unused)));
_Bool heap_is_valid_node(forge_span_u64_t h __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t i __attribute__((unused)));
void heap_swap(forge_span_u64_t h __attribute__((unused)), uint64_t i __attribute__((unused)), uint64_t j __attribute__((unused)));
uint64_t heap_sift_down_step(forge_span_u64_t h __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t i __attribute__((unused)));
_Bool heap_size_valid(uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused)));
int main();

uint64_t heap_parent(uint64_t i __attribute__((unused))) {
  return ((i - 1ULL) / 2ULL);
}

uint64_t heap_left(uint64_t i __attribute__((unused))) {
  return ((2ULL * i) + 1ULL);
}

uint64_t heap_right(uint64_t i __attribute__((unused))) {
  return ((2ULL * i) + 2ULL);
}

_Bool heap_is_valid_node(forge_span_u64_t h __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t i __attribute__((unused))) {
  uint64_t left __attribute__((unused)) = heap_left(i);
  uint64_t right __attribute__((unused)) = heap_right(i);
  _Bool ok_l __attribute__((unused)) = ((left >= n) || (h.data[i] <= h.data[left]));
  _Bool ok_r __attribute__((unused)) = ((right >= n) || (h.data[i] <= h.data[right]));
  return (ok_l && ok_r);
}

void heap_swap(forge_span_u64_t h __attribute__((unused)), uint64_t i __attribute__((unused)), uint64_t j __attribute__((unused))) {
  uint64_t tmp __attribute__((unused)) = h.data[i];
  h.data[i] = h.data[j];
  h.data[j] = tmp;
}

uint64_t heap_sift_down_step(forge_span_u64_t h __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t i __attribute__((unused))) {
  uint64_t left __attribute__((unused)) = heap_left(i);
  uint64_t right __attribute__((unused)) = heap_right(i);
  uint64_t smallest __attribute__((unused)) = i;
  if (((left < n) && (h.data[left] < h.data[smallest]))) {
    smallest = left;

  }
  if (((right < n) && (h.data[right] < h.data[smallest]))) {
    smallest = right;

  }
  return smallest;
}

_Bool heap_size_valid(uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return (n <= cap);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

