/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t collatz_steps(uint64_t n __attribute__((unused)));
uint64_t classify(uint64_t x __attribute__((unused)));
int main();

uint64_t collatz_steps(uint64_t n __attribute__((unused))) {
  uint64_t steps __attribute__((unused)) = ({ uint64_t __loop_result_0;
    for(;;) {
      uint64_t x __attribute__((unused)) = n;
      uint64_t cnt __attribute__((unused)) = 0ULL;
      {
        while ((x != 1ULL)) {
          uint64_t next;
          if ((x % 2ULL) == 0ULL) {
            next = (x / 2ULL);
          }
          else if (1) {
            next = ((3ULL * x) + 1ULL);
          }

          x = next;
          cnt = (cnt + 1ULL);
        }

      }
      __loop_result_0 = cnt; break;
    }
    __loop_result_0; });
  return steps;
}

uint64_t classify(uint64_t x __attribute__((unused))) {
  if ((x <= 9)) {
    return 0ULL;
  }
  else if ((x >= 10 && x <= 99)) {
    return 1ULL;
  }
  else if (1) {
    return 2ULL;
  }

}

int __attribute__((weak)) main() {
  uint64_t a __attribute__((unused)) = classify(5ULL);
  uint64_t b __attribute__((unused)) = classify(42ULL);
  uint64_t c __attribute__((unused)) = classify(100ULL);
  return (int)(((a + b) + c));

}

