/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sparse_dot(forge_span_u64_t idx __attribute__((unused)), forge_span_u64_t vals __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dense __attribute__((unused)), uint64_t d_len __attribute__((unused)));
uint64_t sparse_count_valid(forge_span_u64_t idx __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t d_len __attribute__((unused)));
uint64_t sparse_max_index(forge_span_u64_t idx __attribute__((unused)), uint64_t n __attribute__((unused)));
void sparse_scale(forge_span_u64_t vals __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)));
int main();

uint64_t sparse_dot(forge_span_u64_t idx __attribute__((unused)), forge_span_u64_t vals __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dense __attribute__((unused)), uint64_t d_len __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = idx.data[i];
      if (((j < d_len) && (j < dense.len))) {
        sum = (sum + (vals.data[i] * dense.data[j]));

      }
      i = (i + 1ULL);
    }

  }
  return sum;
}

uint64_t sparse_count_valid(forge_span_u64_t idx __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t d_len __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((idx.data[i] < d_len)) {
        count = (count + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

uint64_t sparse_max_index(forge_span_u64_t idx __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t m __attribute__((unused)) = idx.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((idx.data[i] > m)) {
        m = idx.data[i];

      }
      i = (i + 1ULL);
    }

  }
  return m;
}

void sparse_scale(forge_span_u64_t vals __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      vals.data[i] = (vals.data[i] * k);
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

