/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Point Point;
typedef struct Pair Pair;

typedef struct Point {
  uint64_t x;
  uint64_t y;
} Point;

typedef struct Pair {
  uint64_t a;
  uint64_t b;
} Pair;


/* Forward declarations */
uint64_t Point__Hashable__hash(const Point* self __attribute__((unused)));
uint64_t Pair__sum(const Pair* self __attribute__((unused)));
int main();

uint64_t Point__Hashable__hash(const Point* self __attribute__((unused))) {
  return (((*self).x * 2654435761ULL) ^ ((*self).y * 2246822519ULL));
}

uint64_t Pair__sum(const Pair* self __attribute__((unused))) {
  return ((*self).a + (*self).b);
}

int __attribute__((weak)) main() {
  Point p __attribute__((unused)) = (Point){ .x = 3ULL, .y = 7ULL };
  uint64_t h __attribute__((unused)) = Point__Hashable__hash((&p));
  Pair q __attribute__((unused)) = (Pair){ .a = 10ULL, .b = 32ULL };
  uint64_t s __attribute__((unused)) = Pair__sum((&q));
  return (int)(s);

}

