/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t reverse_bits_8(uint64_t x __attribute__((unused)));
uint64_t reverse_bits_n(uint64_t x __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t bit_rev_index(uint64_t i __attribute__((unused)), uint64_t log2n __attribute__((unused)));
int main();

uint64_t reverse_bits_8(uint64_t x __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  uint64_t r __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < 8ULL)) {
      r = (((r * 2ULL) % 256ULL) + (v & 1ULL));
      v = (v >> 1ULL);
      i = (i + 1ULL);
    }

  }
  return r;
}

uint64_t reverse_bits_n(uint64_t x __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = x;
  uint64_t r __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      r = ((r * 2ULL) + (v & 1ULL));
      v = (v >> 1ULL);
      i = (i + 1ULL);
    }

  }
  return r;
}

uint64_t bit_rev_index(uint64_t i __attribute__((unused)), uint64_t log2n __attribute__((unused))) {
  return reverse_bits_n(i, log2n);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

