/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t partition_by_zero(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t partition_lt(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t thresh __attribute__((unused)));
uint64_t partition_even(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t partition_by_zero(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((s.data[i] == 0ULL)) {
        uint64_t tmp __attribute__((unused)) = s.data[lo];
        s.data[lo] = s.data[i];
        s.data[i] = tmp;
        lo = (lo + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return lo;
}

uint64_t partition_lt(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t thresh __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((s.data[i] < thresh)) {
        uint64_t tmp __attribute__((unused)) = s.data[lo];
        s.data[lo] = s.data[i];
        s.data[i] = tmp;
        lo = (lo + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return lo;
}

uint64_t partition_even(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if (((s.data[i] % 2ULL) == 0ULL)) {
        uint64_t tmp __attribute__((unused)) = s.data[lo];
        s.data[lo] = s.data[i];
        s.data[i] = tmp;
        lo = (lo + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return lo;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

