/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Point Point;
typedef struct Color Color;



typedef struct Point {
  uint64_t x;
  uint64_t y;
} Point;

typedef struct Color {
  uint64_t r;
  uint64_t g;
  uint64_t b;
} Color;

/* Forward declarations */
uint64_t Point__Hashable__hash(const Point* self __attribute__((unused)));
_Bool Point__Eq__eq(const Point* self __attribute__((unused)), const Point* other __attribute__((unused)));
uint64_t Color__Hashable__hash(const Color* self __attribute__((unused)));
int main();

uint64_t Point__Hashable__hash(const Point* self __attribute__((unused))) {
  return (((*self).x * 31ULL) + (*self).y);
}

_Bool Point__Eq__eq(const Point* self __attribute__((unused)), const Point* other __attribute__((unused))) {
  return (((*self).x == (*other).x) && ((*self).y == (*other).y));
}

uint64_t Color__Hashable__hash(const Color* self __attribute__((unused))) {
  return ((((*self).r * 1000003ULL) + ((*self).g * 1009ULL)) + (*self).b);
}

int __attribute__((weak)) main() {
  Point p1 __attribute__((unused)) = (Point){ .x = 3ULL, .y = 7ULL };
  Point p2 __attribute__((unused)) = (Point){ .x = 3ULL, .y = 7ULL };
  Color c __attribute__((unused)) = (Color){ .r = 255ULL, .g = 128ULL, .b = 0ULL };
  uint64_t h1 __attribute__((unused)) = Point__Hashable__hash((&p1));
  uint64_t h2 __attribute__((unused)) = Color__Hashable__hash((&c));
  _Bool eq __attribute__((unused)) = Point__Eq__eq((&p1), (&p2));
  uint64_t eq_val;
  if (eq) {
    eq_val = 1ULL;
  } else {
    eq_val = 0ULL;
  }
  return (int)(((h1 + h2) + eq_val));

}

