/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void inclusive_scan_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)));
void exclusive_scan_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)));
void inclusive_scan_max(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

void inclusive_scan_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused))) {
  dst.data[0ULL] = src.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      dst.data[i] = (dst.data[(i - 1ULL)] + src.data[i]);
      i = (i + 1ULL);
    }

  }
}

void exclusive_scan_add(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused))) {
  dst.data[0ULL] = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      dst.data[i] = (dst.data[(i - 1ULL)] + src.data[(i - 1ULL)]);
      i = (i + 1ULL);
    }

  }
}

void inclusive_scan_max(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused))) {
  dst.data[0ULL] = src.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((src.data[i] > dst.data[(i - 1ULL)])) {
        dst.data[i] = src.data[i];

      } else {
        dst.data[i] = dst.data[(i - 1ULL)];

      }
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

