/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t digit_sum(uint64_t n __attribute__((unused)));
uint64_t digit_count(uint64_t n __attribute__((unused)));
uint64_t reverse_digits(uint64_t n __attribute__((unused)));
_Bool is_palindrome_num(uint64_t n __attribute__((unused)));
uint64_t nth_digit(uint64_t n __attribute__((unused)), uint64_t pos __attribute__((unused)));
int main();

uint64_t digit_sum(uint64_t n __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = n;
  uint64_t s __attribute__((unused)) = 0ULL;
  {
    while ((x > 0ULL)) {
      s = (s + (x % 10ULL));
      x = (x / 10ULL);
    }

  }
  return s;
}

uint64_t digit_count(uint64_t n __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = (n / 10ULL);
  uint64_t d __attribute__((unused)) = 1ULL;
  {
    while ((v > 0ULL)) {
      d = (d + 1ULL);
      v = (v / 10ULL);
    }

  }
  return d;
}

uint64_t reverse_digits(uint64_t n __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = n;
  uint64_t rev __attribute__((unused)) = 0ULL;
  {
    while ((x > 0ULL)) {
      rev = ((rev * 10ULL) + (x % 10ULL));
      x = (x / 10ULL);
    }

  }
  return rev;
}

_Bool is_palindrome_num(uint64_t n __attribute__((unused))) {
  return (reverse_digits(n) == n);
}

uint64_t nth_digit(uint64_t n __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = n;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < pos)) {
      x = (x / 10ULL);
      i = (i + 1ULL);
    }

  }
  return (x % 10ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

