/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t fib(uint64_t n __attribute__((unused)));
void fib_array(forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t tribonacci(uint64_t n __attribute__((unused)));
uint64_t fib_sum(uint64_t n __attribute__((unused)));
int main();

uint64_t fib(uint64_t n __attribute__((unused))) {
  if ((n <= 1ULL)) {
    return n;
  } else {
    uint64_t a __attribute__((unused)) = 0ULL;
    uint64_t b __attribute__((unused)) = 1ULL;
    uint64_t i __attribute__((unused)) = 2ULL;
    {
      while ((i <= n)) {
        uint64_t c __attribute__((unused)) = (a + b);
        a = b;
        b = c;
        i = (i + 1ULL);
      }

    }
    return b;
  }
}

void fib_array(forge_span_u64_t out __attribute__((unused)), uint64_t n __attribute__((unused))) {
  out.data[0ULL] = 0ULL;
  out.data[1ULL] = 1ULL;
  uint64_t i __attribute__((unused)) = 2ULL;
  {
    while ((i < n)) {
      out.data[i] = (out.data[(i - 1ULL)] + out.data[(i - 2ULL)]);
      i = (i + 1ULL);
    }

  }
}

uint64_t tribonacci(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    if ((n == 1ULL)) {
      return 0ULL;
    } else {
      if ((n == 2ULL)) {
        return 1ULL;
      } else {
        uint64_t a __attribute__((unused)) = 0ULL;
        uint64_t b __attribute__((unused)) = 0ULL;
        uint64_t c __attribute__((unused)) = 1ULL;
        uint64_t i __attribute__((unused)) = 3ULL;
        {
          while ((i <= n)) {
            uint64_t d __attribute__((unused)) = ((a + b) + c);
            a = b;
            b = c;
            c = d;
            i = (i + 1ULL);
          }

        }
        return c;
      }
    }
  }
}

uint64_t fib_sum(uint64_t n __attribute__((unused))) {
  uint64_t a __attribute__((unused)) = 0ULL;
  uint64_t b __attribute__((unused)) = 1ULL;
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i <= n)) {
      acc = (acc + a);
      uint64_t c __attribute__((unused)) = (a + b);
      a = b;
      b = c;
      i = (i + 1ULL);
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

