/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Counter Counter;

/* Monomorphized generic types */
typedef enum {
  Option_u64_tag_Some = 0,
  Option_u64_tag_None = 1,
} Option_u64_tag_t;
typedef struct Option_u64 {
  Option_u64_tag_t tag;
  union {
    struct {
      uint64_t _v0;
    } Some;
    struct {
      char _dummy;
    } None;
  } data;
} Option_u64;



typedef struct Counter {
  uint64_t cur;
  uint64_t limit;
} Counter;

/* Forward declarations */
Option_u64 Counter__Iterator__next(Counter* self __attribute__((unused)));
uint64_t sum_to(uint64_t n __attribute__((unused)));
int main();

Option_u64 Counter__Iterator__next(Counter* self __attribute__((unused))) {
  if (((*self).cur >= (*self).limit)) {
    return (Option_u64){ .tag = Option_u64_tag_None, .data.None = { ._dummy = 0 } };
  } else {
    uint64_t v __attribute__((unused)) = (*self).cur;
    (*self).cur = ((*self).cur + 1ULL);
    return (Option_u64){ .tag = Option_u64_tag_Some, .data.Some = { ._v0 = v } };
  }
}

uint64_t sum_to(uint64_t n __attribute__((unused))) {
  Counter c __attribute__((unused)) = (Counter){ .cur = 0ULL, .limit = n };
  uint64_t acc __attribute__((unused)) = 0ULL;
  {
    { Counter __iter_x = c;
      for(;;) {
        Option_u64 __opt_x = Counter__Iterator__next(&__iter_x);
        if (__opt_x.tag == 1) break;
        uint64_t x __attribute__((unused)) = __opt_x.data.Some._v0;
        acc = (acc + x);
      }
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(sum_to(5ULL));

}

