/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t isqrt(uint64_t n __attribute__((unused)));
uint64_t forge_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)));
uint64_t factorial(uint64_t n __attribute__((unused)));
uint64_t gcd2(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t lcm2(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
int main();

uint64_t isqrt(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    uint64_t x __attribute__((unused)) = n;
    uint64_t y __attribute__((unused)) = ((x + 1ULL) / 2ULL);
    {
      while ((y < x)) {
        x = y;
        y = ((x + (n / x)) / 2ULL);
      }

    }
    return x;
  }
}

uint64_t forge_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < forge_exp)) {
      acc = (acc * base);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t factorial(uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i <= n)) {
      acc = (acc * i);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t gcd2(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = a;
  uint64_t y __attribute__((unused)) = b;
  {
    while ((y > 0ULL)) {
      uint64_t t __attribute__((unused)) = y;
      y = (x % y);
      x = t;
    }

  }
  return x;
}

uint64_t lcm2(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  uint64_t g __attribute__((unused)) = gcd2(a, b);
  return ((a / g) * b);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

