/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void array_iota(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t start __attribute__((unused)));
void array_swap(forge_span_u64_t s __attribute__((unused)), uint64_t i __attribute__((unused)), uint64_t j __attribute__((unused)));
void array_fill_range(forge_span_u64_t s __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t array_count_zero(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
_Bool array_any_eq(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
_Bool array_all_eq(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

void array_iota(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t start __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      s.data[i] = (start + i);
      i = (i + 1ULL);
    }

  }
}

void array_swap(forge_span_u64_t s __attribute__((unused)), uint64_t i __attribute__((unused)), uint64_t j __attribute__((unused))) {
  uint64_t tmp __attribute__((unused)) = s.data[i];
  s.data[i] = s.data[j];
  s.data[j] = tmp;
}

void array_fill_range(forge_span_u64_t s __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = lo;
  {
    while ((i < hi)) {
      s.data[i] = val;
      i = (i + 1ULL);
    }

  }
}

uint64_t array_count_zero(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((s.data[i] == 0ULL)) {
        cnt = (cnt + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return cnt;
}

_Bool array_any_eq(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  _Bool found __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i < n) && (!found))) {
      if ((a.data[i] == b.data[i])) {
        found = 1;

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

_Bool array_all_eq(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  _Bool ok __attribute__((unused)) = 1;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i < n) && ok)) {
      if ((a.data[i] != b.data[i])) {
        ok = 0;

      }
      i = (i + 1ULL);
    }

  }
  return ok;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

