/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)), uint64_t m __attribute__((unused)));
uint64_t mod_sum_array(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused)));
int main();

uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  return (((a % m) + (b % m)) % m);
}

uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t am __attribute__((unused)) = (a % m);
  uint64_t bm __attribute__((unused)) = (b % m);
  if ((am >= bm)) {
    return ((am - bm) % m);
  } else {
    return (((m - bm) + am) % m);
  }
}

uint64_t mod_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t m __attribute__((unused))) {
  return (((a % m) * (b % m)) % m);
}

uint64_t mod_pow(uint64_t base __attribute__((unused)), uint64_t forge_exp __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = (1ULL % m);
  uint64_t b __attribute__((unused)) = (base % m);
  uint64_t e __attribute__((unused)) = forge_exp;
  {
    while ((e > 0ULL)) {
      if (((e % 2ULL) == 1ULL)) {
        acc = ((acc * b) % m);

      }
      b = ((b * b) % m);
      e = (e / 2ULL);
    }

  }
  return acc;
}

uint64_t mod_sum_array(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = ((acc + (s.data[i] % m)) % m);
      i = (i + 1ULL);
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

