/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sched_next(uint64_t current __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t sched_run_steps(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t steps __attribute__((unused)));
uint64_t sched_find_idle(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t sched_total_work(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t sched_max_work(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t sched_next(uint64_t current __attribute__((unused)), uint64_t n __attribute__((unused))) {
  return ((current + 1ULL) % n);
}

uint64_t sched_run_steps(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t steps __attribute__((unused))) {
  uint64_t cur __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < steps)) {
      schedule.data[cur] = (schedule.data[cur] + 1ULL);
      uint64_t nc __attribute__((unused)) = sched_next(cur, n);
      cur = nc;
      i = (i + 1ULL);
    }

  }
  return cur;
}

uint64_t sched_find_idle(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = n;
  _Bool done __attribute__((unused)) = 0;
  {
    while (((i < n) && (!done))) {
      if ((schedule.data[i] == 0ULL)) {
        found = i;
        done = 1;

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

uint64_t sched_total_work(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + schedule.data[i]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t sched_max_work(forge_span_u64_t schedule __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t best __attribute__((unused)) = schedule.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((schedule.data[i] > best)) {
        best = schedule.data[i];

      }
      i = (i + 1ULL);
    }

  }
  return best;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

