/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sum_checksum(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t xor_checksum(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t fletcher16(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t djb2_hash(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t fnv1a_hash(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t sum_checksum(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + data.data[i]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t xor_checksum(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc ^ data.data[i]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t fletcher16(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t s1 __attribute__((unused)) = 0ULL;
  uint64_t s2 __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      s1 = ((s1 + (data.data[i] % 255ULL)) % 255ULL);
      s2 = ((s2 + s1) % 65025ULL);
      i = (i + 1ULL);
    }

  }
  return ((s1 * 256ULL) + s2);
}

uint64_t djb2_hash(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t h __attribute__((unused)) = 5381ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      h = ((h * 33ULL) + data.data[i]);
      i = (i + 1ULL);
    }

  }
  return h;
}

uint64_t fnv1a_hash(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t h __attribute__((unused)) = 0xcbf29ce484222325ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      h = ((h ^ data.data[i]) * 1099511628211ULL);
      i = (i + 1ULL);
    }

  }
  return h;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

