/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t isqrt2(uint64_t n __attribute__((unused)));
uint64_t log2_ceil(uint64_t n __attribute__((unused)));
uint64_t round_to_power2(uint64_t n __attribute__((unused)));
uint64_t fast_div_by_const(uint64_t x __attribute__((unused)), uint64_t d __attribute__((unused)));
uint64_t integer_percent(uint64_t val __attribute__((unused)), uint64_t total __attribute__((unused)));
int main();

uint64_t isqrt2(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    uint64_t x __attribute__((unused)) = n;
    uint64_t y __attribute__((unused)) = ((x + 1ULL) / 2ULL);
    {
      while ((y < x)) {
        x = y;
        y = ((x + (n / x)) / 2ULL);
      }

    }
    return x;
  }
}

uint64_t log2_ceil(uint64_t n __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = (n - 1ULL);
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    while ((x > 0ULL)) {
      x = (x / 2ULL);
      k = (k + 1ULL);
    }

  }
  return k;
}

uint64_t round_to_power2(uint64_t n __attribute__((unused))) {
  uint64_t p __attribute__((unused)) = 1ULL;
  {
    while ((p < n)) {
      p = (p * 2ULL);
    }

  }
  return p;
}

uint64_t fast_div_by_const(uint64_t x __attribute__((unused)), uint64_t d __attribute__((unused))) {
  return (x / d);
}

uint64_t integer_percent(uint64_t val __attribute__((unused)), uint64_t total __attribute__((unused))) {
  return (((val * 100ULL) / total) % 101ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

