/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t pool_alloc(forge_span_u64_t free_list __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t head __attribute__((unused)));
uint64_t pool_free_count(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t pool_find_free(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)));
void pool_mark_used(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t idx __attribute__((unused)));
void pool_mark_free(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t idx __attribute__((unused)));
void pool_init(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t pool_alloc(forge_span_u64_t free_list __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t head __attribute__((unused))) {
  if ((head >= n)) {
    return n;
  } else {
    return (head + 1ULL);
  }
}

uint64_t pool_free_count(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t cnt __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((free_bitmap.data[i] == 1ULL)) {
        cnt = (cnt + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return cnt;
}

uint64_t pool_find_free(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = n;
  _Bool done __attribute__((unused)) = 0;
  {
    while (((i < n) && (!done))) {
      if ((free_bitmap.data[i] == 1ULL)) {
        found = i;
        done = 1;

      }
      i = (i + 1ULL);
    }

  }
  return found;
}

void pool_mark_used(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t idx __attribute__((unused))) {
  free_bitmap.data[idx] = 0ULL;
}

void pool_mark_free(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t idx __attribute__((unused))) {
  free_bitmap.data[idx] = 1ULL;
}

void pool_init(forge_span_u64_t free_bitmap __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      free_bitmap.data[i] = 1ULL;
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

