/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t nibble_lo(uint64_t x __attribute__((unused)));
uint64_t nibble_hi(uint64_t x __attribute__((unused)));
uint64_t hex_digit(uint64_t n __attribute__((unused)));
uint64_t byte_to_hex(forge_span_u64_t buf __attribute__((unused)), uint64_t pos __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t encode_bytes(forge_span_u64_t src __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)));
uint64_t pack_nibbles(uint64_t hi __attribute__((unused)), uint64_t lo __attribute__((unused)));
uint64_t unpack_hi(uint64_t x __attribute__((unused)));
uint64_t unpack_lo(uint64_t x __attribute__((unused)));
int main();

uint64_t nibble_lo(uint64_t x __attribute__((unused))) {
  return (x % 16ULL);
}

uint64_t nibble_hi(uint64_t x __attribute__((unused))) {
  return ((x / 16ULL) % 16ULL);
}

uint64_t hex_digit(uint64_t n __attribute__((unused))) {
  if ((n < 10ULL)) {
    return (n + 48ULL);
  } else {
    return ((n - 10ULL) + 65ULL);
  }
}

uint64_t byte_to_hex(forge_span_u64_t buf __attribute__((unused)), uint64_t pos __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t hi __attribute__((unused)) = nibble_hi(val);
  uint64_t lo __attribute__((unused)) = nibble_lo(val);
  buf.data[pos] = hex_digit(hi);
  buf.data[(pos + 1ULL)] = hex_digit(lo);
  return (pos + 2ULL);
}

uint64_t encode_bytes(forge_span_u64_t src __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t dst __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t out __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t hi __attribute__((unused)) = nibble_hi(src.data[i]);
      uint64_t lo __attribute__((unused)) = nibble_lo(src.data[i]);
      dst.data[out] = hex_digit(hi);
      dst.data[(out + 1ULL)] = hex_digit(lo);
      out = (out + 2ULL);
      i = (i + 1ULL);
    }

  }
  return out;
}

uint64_t pack_nibbles(uint64_t hi __attribute__((unused)), uint64_t lo __attribute__((unused))) {
  return ((hi * 16ULL) + lo);
}

uint64_t unpack_hi(uint64_t x __attribute__((unused))) {
  return ((x / 16ULL) % 16ULL);
}

uint64_t unpack_lo(uint64_t x __attribute__((unused))) {
  return (x % 16ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

