/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void window_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void window_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
void window_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused)));
uint64_t window_count(uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)));
int main();

void window_sum(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0ULL;
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < w)) {
      sum = (sum + s.data[j]);
      j = (j + 1ULL);
    }

  }
  out.data[0ULL] = sum;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while (((i + w) <= n)) {
      sum = ((sum + s.data[((i + w) - 1ULL)]) - s.data[(i - 1ULL)]);
      out.data[i] = sum;
      i = (i + 1ULL);
    }

  }
}

void window_max(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i + w) <= n)) {
      uint64_t mx __attribute__((unused)) = s.data[i];
      uint64_t j __attribute__((unused)) = 1ULL;
      {
        while ((j < w)) {
          if ((s.data[(i + j)] > mx)) {
            mx = s.data[(i + j)];

          }
          j = (j + 1ULL);
        }

      }
      out.data[i] = mx;
      i = (i + 1ULL);
    }

  }
}

void window_min(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t out __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while (((i + w) <= n)) {
      uint64_t mn __attribute__((unused)) = s.data[i];
      uint64_t j __attribute__((unused)) = 1ULL;
      {
        while ((j < w)) {
          if ((s.data[(i + j)] < mn)) {
            mn = s.data[(i + j)];

          }
          j = (j + 1ULL);
        }

      }
      out.data[i] = mn;
      i = (i + 1ULL);
    }

  }
}

uint64_t window_count(uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused))) {
  return ((n - w) + 1ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

