/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t bmat_get(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)));
void bmat_set(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t bmat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)));
uint64_t bmat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused)));
void bmat_fill_row(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t val __attribute__((unused)));
uint64_t bmat_trace(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t bmat_get(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused))) {
  return m.data[((row * cols) + col)];
}

void bmat_set(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t col __attribute__((unused)), uint64_t val __attribute__((unused))) {
  m.data[((row * cols) + col)] = val;
}

uint64_t bmat_row_sum(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < cols)) {
      acc = (acc + m.data[((row * cols) + j)]);
      j = (j + 1ULL);
    }

  }
  return acc;
}

uint64_t bmat_col_sum(forge_span_u64_t m __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t col __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < rows)) {
      acc = (acc + m.data[((i * cols) + col)]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

void bmat_fill_row(forge_span_u64_t m __attribute__((unused)), uint64_t cols __attribute__((unused)), uint64_t row __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < cols)) {
      m.data[((row * cols) + j)] = val;
      j = (j + 1ULL);
    }

  }
}

uint64_t bmat_trace(forge_span_u64_t m __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + m.data[((i * n) + i)]);
      i = (i + 1ULL);
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

