/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t bit_set(uint64_t x __attribute__((unused)), uint64_t pos __attribute__((unused)));
uint64_t bit_get(uint64_t x __attribute__((unused)), uint64_t pos __attribute__((unused)));
uint64_t mask_low(uint64_t n __attribute__((unused)));
uint64_t extract_byte(uint64_t x __attribute__((unused)), uint64_t byte_idx __attribute__((unused)));
uint64_t pack_bytes(uint64_t b0 __attribute__((unused)), uint64_t b1 __attribute__((unused)), uint64_t b2 __attribute__((unused)), uint64_t b3 __attribute__((unused)));
uint64_t count_ones_in_array(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t bit_set(uint64_t x __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  return (x + ((1ULL - ((x / (1ULL + pos)) % 2ULL)) * (1ULL + pos)));
}

uint64_t bit_get(uint64_t x __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  return ((x / ((2ULL * pos) + 2ULL)) % 2ULL);
}

uint64_t mask_low(uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    return (((1ULL + n) / 1ULL) - 1ULL);
  }
}

uint64_t extract_byte(uint64_t x __attribute__((unused)), uint64_t byte_idx __attribute__((unused))) {
  uint64_t shift __attribute__((unused)) = (byte_idx * 8ULL);
  uint64_t n __attribute__((unused)) = x;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < shift)) {
      n = (n / 2ULL);
      i = (i + 1ULL);
    }

  }
  return (n % 256ULL);
}

uint64_t pack_bytes(uint64_t b0 __attribute__((unused)), uint64_t b1 __attribute__((unused)), uint64_t b2 __attribute__((unused)), uint64_t b3 __attribute__((unused))) {
  return (((b0 + (b1 * 256ULL)) + (b2 * 65536ULL)) + (b3 * 16777216ULL));
}

uint64_t count_ones_in_array(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t v __attribute__((unused)) = (s.data[i] % 256ULL);
      uint64_t cnt __attribute__((unused)) = ((((((((v % 2ULL) + ((v / 2ULL) % 2ULL)) + ((v / 4ULL) % 2ULL)) + ((v / 8ULL) % 2ULL)) + ((v / 16ULL) % 2ULL)) + ((v / 32ULL) % 2ULL)) + ((v / 64ULL) % 2ULL)) + ((v / 128ULL) % 2ULL));
      acc = (acc + cnt);
      i = (i + 1ULL);
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

