/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

static const uint64_t MAX_SIZE = 1024ULL;

static const uint64_t MAGIC = 4660ULL;

static const uint64_t PI_INT = 3ULL;

/* Forward declarations */
uint64_t clamp_to_max(uint64_t v __attribute__((unused)));
_Bool is_magic(uint64_t v __attribute__((unused)));
uint64_t circle_area_approx(uint64_t r __attribute__((unused)));
int main();

uint64_t clamp_to_max(uint64_t v __attribute__((unused))) {
  if ((v > MAX_SIZE)) {
    return MAX_SIZE;
  } else {
    return v;
  }
}

_Bool is_magic(uint64_t v __attribute__((unused))) {
  return (v == MAGIC);
}

uint64_t circle_area_approx(uint64_t r __attribute__((unused))) {
  return ((PI_INT * r) * r);
}

int __attribute__((weak)) main() {
  uint64_t c1 __attribute__((unused)) = clamp_to_max(2000ULL);
  uint64_t c2 __attribute__((unused)) = clamp_to_max(100ULL);
  _Bool m __attribute__((unused)) = is_magic(4660ULL);
  uint64_t a __attribute__((unused)) = circle_area_approx(5ULL);
  uint64_t m_val;
  if (m) {
    m_val = 1ULL;
  } else {
    m_val = 0ULL;
  }
  return (int)((((c1 + c2) + m_val) + a));

}

