/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sum_prefix(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t max_array_rec(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t count_le(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t threshold __attribute__((unused)));
uint64_t bsearch_iter(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

uint64_t sum_prefix(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    return (s.data[(n - 1ULL)] + sum_prefix(s, (n - 1ULL)));
  }
}

uint64_t max_array_rec(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  if ((n == 1ULL)) {
    return s.data[0ULL];
  } else {
    uint64_t prev_max __attribute__((unused)) = max_array_rec(s, (n - 1ULL));
    if ((s.data[(n - 1ULL)] > prev_max)) {
      return s.data[(n - 1ULL)];
    } else {
      return prev_max;
    }
  }
}

uint64_t count_le(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t threshold __attribute__((unused))) {
  if ((n == 0ULL)) {
    return 0ULL;
  } else {
    uint64_t rest __attribute__((unused)) = count_le(s, (n - 1ULL), threshold);
    if ((s.data[(n - 1ULL)] <= threshold)) {
      return (rest + 1ULL);
    } else {
      return rest;
    }
  }
}

uint64_t bsearch_iter(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t lo __attribute__((unused)) = 0ULL;
  uint64_t hi __attribute__((unused)) = n;
  uint64_t ans __attribute__((unused)) = n;
  {
    while ((lo < hi)) {
      uint64_t mid __attribute__((unused)) = (lo + ((hi - lo) / 2ULL));
      if ((s.data[mid] == target)) {
        ans = mid;
        lo = hi;

      } else if ((s.data[mid] < target)) {
        lo = (mid + 1ULL);

      } else {
        hi = mid;

      }
    }

  }
  return ans;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

