/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t remove_element(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused)));
uint64_t remove_sorted_dups(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t remove_element(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t write __attribute__((unused)) = 0ULL;
  uint64_t read __attribute__((unused)) = 0ULL;
  {
    while ((read < n)) {
      if ((s.data[read] != target)) {
        s.data[write] = s.data[read];
        write = (write + 1ULL);

      }
      read = (read + 1ULL);
    }

  }
  return write;
}

uint64_t remove_sorted_dups(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t write __attribute__((unused)) = 1ULL;
  uint64_t read __attribute__((unused)) = 1ULL;
  {
    while ((read < n)) {
      if ((s.data[read] != s.data[(write - 1ULL)])) {
        s.data[write] = s.data[read];
        write = (write + 1ULL);

      }
      read = (read + 1ULL);
    }

  }
  return write;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

