/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void ewma_filter(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused)), forge_span_u64_t output __attribute__((unused)));
void sma(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t output __attribute__((unused)));
int main();

void ewma_filter(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t alpha __attribute__((unused)), forge_span_u64_t output __attribute__((unused))) {
  output.data[0ULL] = samples.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t prev __attribute__((unused)) = output.data[(i - 1ULL)];
      uint64_t cur __attribute__((unused)) = samples.data[i];
      output.data[i] = (((alpha * cur) + ((256ULL - alpha) * prev)) / 256ULL);
      i = (i + 1ULL);
    }

  }
}

void sma(forge_span_u64_t samples __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t output __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0ULL;
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < w)) {
      sum = (sum + samples.data[j]);
      j = (j + 1ULL);
    }

  }
  output.data[(w - 1ULL)] = (sum / w);
  uint64_t i __attribute__((unused)) = w;
  {
    while ((i < n)) {
      sum = ((sum + samples.data[i]) - samples.data[(i - w)]);
      output.data[i] = (sum / w);
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

