/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void sparse_to_dense(forge_span_u64_t indices __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t nnz __attribute__((unused)), forge_span_u64_t dense __attribute__((unused)), uint64_t dense_len __attribute__((unused)));
uint64_t dense_dot(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t sparse_dot(forge_span_u64_t indices __attribute__((unused)), forge_span_u64_t a_vals __attribute__((unused)), forge_span_u64_t b_vals __attribute__((unused)), uint64_t nnz __attribute__((unused)));
int main();

void sparse_to_dense(forge_span_u64_t indices __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t nnz __attribute__((unused)), forge_span_u64_t dense __attribute__((unused)), uint64_t dense_len __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < dense_len)) {
      dense.data[i] = 0ULL;
      i = (i + 1ULL);
    }

  }
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < nnz)) {
      uint64_t idx __attribute__((unused)) = indices.data[j];
      dense.data[idx] = (dense.data[idx] + values.data[j]);
      j = (j + 1ULL);
    }

  }
}

uint64_t dense_dot(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      acc = (acc + (a.data[i] * b.data[i]));
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t sparse_dot(forge_span_u64_t indices __attribute__((unused)), forge_span_u64_t a_vals __attribute__((unused)), forge_span_u64_t b_vals __attribute__((unused)), uint64_t nnz __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < nnz)) {
      acc = (acc + (a_vals.data[i] * b_vals.data[i]));
      i = (i + 1ULL);
    }

  }
  return acc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

