/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Debug Debug;
typedef struct Release Release;


typedef struct Debug {
  uint64_t seed;
} Debug;

typedef struct Release {
  uint64_t optimized;
} Release;

/* Forward declarations */
uint64_t Debug__Config__name_hash(const Debug* self __attribute__((unused)));
uint64_t Debug__Config__version();
uint64_t Release__Config__name_hash(const Release* self __attribute__((unused)));
uint64_t Release__Config__flags();
int main();
uint64_t Release__Config__version();
uint64_t Debug__Config__flags();

uint64_t Debug__Config__name_hash(const Debug* self __attribute__((unused))) {
  return ((*self).seed * 37ULL);
}

uint64_t Debug__Config__version() {
  return 999ULL;
}

uint64_t Release__Config__name_hash(const Release* self __attribute__((unused))) {
  return ((*self).optimized * 7ULL);
}

uint64_t Release__Config__flags() {
  return 128ULL;
}

int __attribute__((weak)) main() {
  Debug d __attribute__((unused)) = (Debug){ .seed = 5ULL };
  Release r __attribute__((unused)) = (Release){ .optimized = 10ULL };
  uint64_t dh __attribute__((unused)) = Debug__Config__name_hash((&d));
  uint64_t dv __attribute__((unused)) = Debug__Config__version();
  uint64_t df __attribute__((unused)) = Debug__Config__flags();
  uint64_t rh __attribute__((unused)) = Release__Config__name_hash((&r));
  uint64_t rv __attribute__((unused)) = Release__Config__version();
  uint64_t rf __attribute__((unused)) = Release__Config__flags();
  return (int)((((((dh + dv) + df) + rh) + rv) + rf));

}

uint64_t Release__Config__version() {
  return 1ULL;
}

uint64_t Debug__Config__flags() {
  return 0ULL;
}

