/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void merge_halves(forge_span_u64_t src __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t mid __attribute__((unused)), uint64_t hi __attribute__((unused)), forge_span_u64_t tmp __attribute__((unused)));
int main();

void merge_halves(forge_span_u64_t src __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t mid __attribute__((unused)), uint64_t hi __attribute__((unused)), forge_span_u64_t tmp __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = lo;
  uint64_t j __attribute__((unused)) = mid;
  uint64_t k __attribute__((unused)) = lo;
  {
    while (((i < mid) && (j < hi))) {
      if ((src.data[i] <= src.data[j])) {
        tmp.data[k] = src.data[i];
        i = (i + 1ULL);
        k = (k + 1ULL);

      } else {
        tmp.data[k] = src.data[j];
        j = (j + 1ULL);
        k = (k + 1ULL);

      }
    }

  }
  {
    while ((i < mid)) {
      tmp.data[k] = src.data[i];
      i = (i + 1ULL);
      k = (k + 1ULL);
    }

  }
  {
    while ((j < hi)) {
      tmp.data[k] = src.data[j];
      j = (j + 1ULL);
      k = (k + 1ULL);
    }

  }
  uint64_t c __attribute__((unused)) = lo;
  {
    while ((c < hi)) {
      src.data[c] = tmp.data[c];
      c = (c + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

