/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;
typedef struct { uint64_t _0; uint64_t _1; uint64_t _2; } __forge_tuple_u64_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t ring_enqueue(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t tail __attribute__((unused)), uint64_t count __attribute__((unused)), uint64_t val __attribute__((unused)));
__forge_tuple_u64_u64_u64_t ring_dequeue(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t head __attribute__((unused)), uint64_t count __attribute__((unused)));
__forge_tuple_u64_u64_t ring_fill(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t val __attribute__((unused)));
int main();

__forge_tuple_u64_u64_t ring_enqueue(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t tail __attribute__((unused)), uint64_t count __attribute__((unused)), uint64_t val __attribute__((unused))) {
  buf.data[tail] = val;
  uint64_t new_tail;
  if (((tail + 1ULL) == cap)) {
    new_tail = 0ULL;
  } else {
    new_tail = (tail + 1ULL);
  }
  return FORGE_AGG(__forge_tuple_u64_u64_t, new_tail, (count + 1ULL));
}

__forge_tuple_u64_u64_u64_t ring_dequeue(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t head __attribute__((unused)), uint64_t count __attribute__((unused))) {
  uint64_t val __attribute__((unused)) = buf.data[head];
  uint64_t new_head;
  if (((head + 1ULL) == cap)) {
    new_head = 0ULL;
  } else {
    new_head = (head + 1ULL);
  }
  return FORGE_AGG(__forge_tuple_u64_u64_u64_t, val, new_head, (count - 1ULL));
}

__forge_tuple_u64_u64_t ring_fill(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t tail __attribute__((unused)) = 0ULL;
  uint64_t count __attribute__((unused)) = 0ULL;
  {
    while ((count < cap)) {
      buf.data[tail] = val;
      tail = (((tail + 1ULL) == cap) ? 0ULL : (tail + 1ULL));
      count = (count + 1ULL);
    }

  }
  return FORGE_AGG(__forge_tuple_u64_u64_t, tail, count);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

