/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
void pool_init(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused)));
__forge_tuple_u64_u64_t pool_alloc(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused)), uint64_t free_count __attribute__((unused)));
uint64_t pool_free(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused)), uint64_t free_count __attribute__((unused)), uint64_t block __attribute__((unused)));
int main();

void pool_init(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < pool_size)) {
      free_list.data[i] = i;
      i = (i + 1ULL);
    }

  }
}

__forge_tuple_u64_u64_t pool_alloc(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused)), uint64_t free_count __attribute__((unused))) {
  uint64_t new_count __attribute__((unused)) = (free_count - 1ULL);
  uint64_t block __attribute__((unused)) = free_list.data[new_count];
  return FORGE_AGG(__forge_tuple_u64_u64_t, block, new_count);
}

uint64_t pool_free(forge_span_u64_t free_list __attribute__((unused)), uint64_t pool_size __attribute__((unused)), uint64_t free_count __attribute__((unused)), uint64_t block __attribute__((unused))) {
  free_list.data[free_count] = block;
  return (free_count + 1ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

