/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t hash1(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused)));
uint64_t hash2(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused)));
void set_bit(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t pos __attribute__((unused)));
_Bool test_bit(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t pos __attribute__((unused)));
void bloom_insert(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t val __attribute__((unused)));
_Bool bloom_query(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t val __attribute__((unused)));
int main();

uint64_t hash1(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused))) {
  return (val % nbits);
}

uint64_t hash2(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused))) {
  return (((val * 2654435761ULL) + 17ULL) % nbits);
}

void set_bit(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  bits.data[pos] = 1ULL;
}

_Bool test_bit(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  return (bits.data[pos] != 0ULL);
}

void bloom_insert(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t h1 __attribute__((unused)) = hash1(val, nbits);
  uint64_t h2 __attribute__((unused)) = hash2(val, nbits);
  set_bit(bits, nbits, h1);
  set_bit(bits, nbits, h2);
}

_Bool bloom_query(forge_span_u64_t bits __attribute__((unused)), uint64_t nbits __attribute__((unused)), uint64_t val __attribute__((unused))) {
  uint64_t h1 __attribute__((unused)) = hash1(val, nbits);
  uint64_t h2 __attribute__((unused)) = hash2(val, nbits);
  return (test_bit(bits, nbits, h1) && test_bit(bits, nbits, h2));
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

