/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward typedefs for user-defined structs/enums */
typedef struct Record Record;




typedef struct Record {
  uint64_t key;
  uint64_t value;
} Record;

/* Forward declarations */
uint64_t Record__Hashable__hash(const Record* self __attribute__((unused)));
uint64_t Record__Comparable__compare(const Record* self __attribute__((unused)), const Record* other __attribute__((unused)));
uint64_t Record__Displayable__display_val(const Record* self __attribute__((unused)));
uint64_t process_pair(const void* a __attribute__((unused)), const void* b __attribute__((unused)));
uint64_t describe_pair(const void* a __attribute__((unused)), const void* b __attribute__((unused)));
int main();

uint64_t Record__Hashable__hash(const Record* self __attribute__((unused))) {
  return ((*self).key * 2654435761ULL);
}

uint64_t Record__Comparable__compare(const Record* self __attribute__((unused)), const Record* other __attribute__((unused))) {
  if (((*self).key == (*other).key)) {
    return 0ULL;
  } else {
    if (((*self).key > (*other).key)) {
      return 1ULL;
    } else {
      return 2ULL;
    }
  }
}

uint64_t Record__Displayable__display_val(const Record* self __attribute__((unused))) {
  return (((*self).key * 1000ULL) + (*self).value);
}

uint64_t process_pair(const void* a __attribute__((unused)), const void* b __attribute__((unused))) {
  return 0ULL;
}

uint64_t describe_pair(const void* a __attribute__((unused)), const void* b __attribute__((unused))) {
  return 0ULL;
}

int __attribute__((weak)) main() {
  Record r1 __attribute__((unused)) = (Record){ .key = 10ULL, .value = 5ULL };
  Record r2 __attribute__((unused)) = (Record){ .key = 7ULL, .value = 3ULL };
  uint64_t _p __attribute__((unused)) = process_pair((&r1), (&r2));
  uint64_t _d __attribute__((unused)) = describe_pair((&r1), (&r2));
  uint64_t h1 __attribute__((unused)) = Record__Hashable__hash((&r1));
  uint64_t h2 __attribute__((unused)) = Record__Hashable__hash((&r2));
  uint64_t cmp __attribute__((unused)) = Record__Comparable__compare((&r1), (&r2));
  uint64_t dv1 __attribute__((unused)) = Record__Displayable__display_val((&r1));
  uint64_t dv2 __attribute__((unused)) = Record__Displayable__display_val((&r2));
  return (int)(((cmp + dv1) + dv2));

}

