/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t to_base(uint64_t val __attribute__((unused)), uint64_t base __attribute__((unused)), forge_span_u64_t digits __attribute__((unused)), uint64_t max_digits __attribute__((unused)));
uint64_t from_base(forge_span_u64_t digits __attribute__((unused)), uint64_t ndigits __attribute__((unused)), uint64_t base __attribute__((unused)));
int main();

uint64_t to_base(uint64_t val __attribute__((unused)), uint64_t base __attribute__((unused)), forge_span_u64_t digits __attribute__((unused)), uint64_t max_digits __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t i __attribute__((unused)) = 0ULL;
  if ((val == 0ULL)) {
    digits.data[0ULL] = 0ULL;
    i = 1ULL;

  } else {
    {
      while (((v > 0ULL) && (i < max_digits))) {
        digits.data[i] = (v % base);
        v = (v / base);
        i = (i + 1ULL);
      }

    }

  }
  return i;
}

uint64_t from_base(forge_span_u64_t digits __attribute__((unused)), uint64_t ndigits __attribute__((unused)), uint64_t base __attribute__((unused))) {
  uint64_t val __attribute__((unused)) = 0ULL;
  uint64_t power __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < ndigits)) {
      val = (val + (digits.data[i] * power));
      power = (power * base);
      i = (i + 1ULL);
    }

  }
  return val;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

