/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void assign_lengths(forge_span_u64_t freqs __attribute__((unused)), forge_span_u64_t lengths __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

void assign_lengths(forge_span_u64_t freqs __attribute__((unused)), forge_span_u64_t lengths __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      lengths.data[i] = 1ULL;
      i = (i + 1ULL);
    }

  }
  uint64_t merges __attribute__((unused)) = 0ULL;
  {
    while (((merges + 1ULL) < n)) {
      uint64_t idx1 __attribute__((unused)) = merges;
      uint64_t idx2 __attribute__((unused)) = (merges + 1ULL);
      if ((idx1 < n)) {
        lengths.data[idx1] = (lengths.data[idx1] + 1ULL);

      }
      if ((idx2 < n)) {
        lengths.data[idx2] = (lengths.data[idx2] + 1ULL);

      }
      merges = (merges + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

