/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void spmv_csr(forge_span_u64_t row_ptr __attribute__((unused)), forge_span_u64_t col_idx __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t nrows __attribute__((unused)), uint64_t nnz __attribute__((unused)), forge_span_u64_t x __attribute__((unused)), uint64_t x_len __attribute__((unused)), forge_span_u64_t y __attribute__((unused)));
int main();

void spmv_csr(forge_span_u64_t row_ptr __attribute__((unused)), forge_span_u64_t col_idx __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t nrows __attribute__((unused)), uint64_t nnz __attribute__((unused)), forge_span_u64_t x __attribute__((unused)), uint64_t x_len __attribute__((unused)), forge_span_u64_t y __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < nrows)) {
      uint64_t row_start __attribute__((unused)) = row_ptr.data[i];
      uint64_t row_end __attribute__((unused)) = row_ptr.data[(i + 1ULL)];
      uint64_t acc __attribute__((unused)) = 0ULL;
      uint64_t j __attribute__((unused)) = row_start;
      {
        while ((j < row_end)) {
          uint64_t col __attribute__((unused)) = col_idx.data[j];
          acc = (acc + (values.data[j] * x.data[col]));
          j = (j + 1ULL);
        }

      }
      y.data[i] = acc;
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

