/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t xorshift64(uint64_t state __attribute__((unused)));
uint64_t fill_random(uint64_t seed __attribute__((unused)), uint64_t bound __attribute__((unused)), forge_span_u64_t output __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t xorshift64(uint64_t state __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = state;
  s = (s ^ (s << 13ULL));
  s = (s ^ (s >> 7ULL));
  s = (s ^ (s << 17ULL));
  if ((s == 0ULL)) {
    return 1ULL;
  } else {
    return s;
  }
}

uint64_t fill_random(uint64_t seed __attribute__((unused)), uint64_t bound __attribute__((unused)), forge_span_u64_t output __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t state __attribute__((unused)) = seed;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      state = xorshift64(state);
      output.data[i] = (state % bound);
      i = (i + 1ULL);
    }

  }
  return state;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

