/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void move_to_front(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused)), uint64_t pos __attribute__((unused)));
uint64_t evict_lru(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused)));
uint64_t cache_find(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused)), uint64_t key __attribute__((unused)));
int main();

void move_to_front(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t val __attribute__((unused)) = cache.data[pos];
  uint64_t i __attribute__((unused)) = pos;
  {
    while ((i > 0ULL)) {
      cache.data[i] = cache.data[(i - 1ULL)];
      i = (i - 1ULL);
    }

  }
  cache.data[0ULL] = val;
}

uint64_t evict_lru(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused))) {
  return cache.data[(size - 1ULL)];
}

uint64_t cache_find(forge_span_u64_t cache __attribute__((unused)), uint64_t size __attribute__((unused)), uint64_t key __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  uint64_t found __attribute__((unused)) = size;
  {
    while ((i < size)) {
      if ((cache.data[i] == key)) {
        found = i;
        i = size;

      } else {
        i = (i + 1ULL);

      }
    }

  }
  return found;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

