/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
_Bool nfa_match(forge_span_u64_t pattern __attribute__((unused)), uint64_t n_states __attribute__((unused)), uint64_t n_trans __attribute__((unused)), forge_span_u64_t text __attribute__((unused)), uint64_t text_len __attribute__((unused)), forge_span_u64_t current __attribute__((unused)), forge_span_u64_t next __attribute__((unused)));
int main();

_Bool nfa_match(forge_span_u64_t pattern __attribute__((unused)), uint64_t n_states __attribute__((unused)), uint64_t n_trans __attribute__((unused)), forge_span_u64_t text __attribute__((unused)), uint64_t text_len __attribute__((unused)), forge_span_u64_t current __attribute__((unused)), forge_span_u64_t next __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = 0ULL;
  {
    while ((s < n_states)) {
      current.data[s] = 0ULL;
      s = (s + 1ULL);
    }

  }
  current.data[0ULL] = 1ULL;
  uint64_t t __attribute__((unused)) = 0ULL;
  {
    while ((t < text_len)) {
      uint64_t s2 __attribute__((unused)) = 0ULL;
      {
        while ((s2 < n_states)) {
          next.data[s2] = 0ULL;
          s2 = (s2 + 1ULL);
        }

      }
      uint64_t state __attribute__((unused)) = 0ULL;
      {
        while ((state < n_states)) {
          if ((current.data[state] == 1ULL)) {
            uint64_t e __attribute__((unused)) = 0ULL;
            {
              while (((e + 2ULL) < n_trans)) {
                if (((pattern.data[e] == state) && (pattern.data[(e + 1ULL)] == text.data[t]))) {
                  uint64_t nxt __attribute__((unused)) = pattern.data[(e + 2ULL)];
                  if ((nxt < n_states)) {
                    next.data[nxt] = 1ULL;

                  }

                }
                e = (e + 3ULL);
              }

            }

          }
          state = (state + 1ULL);
        }

      }
      uint64_t s3 __attribute__((unused)) = 0ULL;
      {
        while ((s3 < n_states)) {
          current.data[s3] = next.data[s3];
          s3 = (s3 + 1ULL);
        }

      }
      t = (t + 1ULL);
    }

  }
  return (current.data[(n_states - 1ULL)] == 1ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

