/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
_Bool check_row(forge_span_u64_t board __attribute__((unused)), uint64_t row __attribute__((unused)), forge_span_u64_t seen __attribute__((unused)));
_Bool check_col(forge_span_u64_t board __attribute__((unused)), uint64_t col __attribute__((unused)), forge_span_u64_t seen __attribute__((unused)));
_Bool check_all_rows(forge_span_u64_t board __attribute__((unused)), forge_span_u64_t seen __attribute__((unused)));
int main();

_Bool check_row(forge_span_u64_t board __attribute__((unused)), uint64_t row __attribute__((unused)), forge_span_u64_t seen __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < 9ULL)) {
      seen.data[j] = 0ULL;
      j = (j + 1ULL);
    }

  }
  _Bool ok __attribute__((unused)) = 1;
  uint64_t c __attribute__((unused)) = 0ULL;
  {
    while ((c < 9ULL)) {
      uint64_t val __attribute__((unused)) = board.data[((row * 9ULL) + c)];
      if (((val >= 1ULL) && (val <= 9ULL))) {
        if ((seen.data[(val - 1ULL)] != 0ULL)) {
          ok = 0;

        }
        seen.data[(val - 1ULL)] = 1ULL;

      } else {
        ok = 0;

      }
      c = (c + 1ULL);
    }

  }
  return ok;
}

_Bool check_col(forge_span_u64_t board __attribute__((unused)), uint64_t col __attribute__((unused)), forge_span_u64_t seen __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < 9ULL)) {
      seen.data[j] = 0ULL;
      j = (j + 1ULL);
    }

  }
  _Bool ok __attribute__((unused)) = 1;
  uint64_t r __attribute__((unused)) = 0ULL;
  {
    while ((r < 9ULL)) {
      uint64_t val __attribute__((unused)) = board.data[((r * 9ULL) + col)];
      if (((val >= 1ULL) && (val <= 9ULL))) {
        if ((seen.data[(val - 1ULL)] != 0ULL)) {
          ok = 0;

        }
        seen.data[(val - 1ULL)] = 1ULL;

      } else {
        ok = 0;

      }
      r = (r + 1ULL);
    }

  }
  return ok;
}

_Bool check_all_rows(forge_span_u64_t board __attribute__((unused)), forge_span_u64_t seen __attribute__((unused))) {
  _Bool ok __attribute__((unused)) = 1;
  uint64_t r __attribute__((unused)) = 0ULL;
  {
    while ((r < 9ULL)) {
      if ((!check_row(board, r, seen))) {
        ok = 0;

      }
      r = (r + 1ULL);
    }

  }
  return ok;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

