/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t cross_product(forge_span_u64_t pts __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t c __attribute__((unused)));
uint64_t find_bottom(forge_span_u64_t pts __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t cross_product(forge_span_u64_t pts __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t c __attribute__((unused))) {
  uint64_t ax __attribute__((unused)) = pts.data[(a + a)];
  uint64_t ay __attribute__((unused)) = pts.data[((a + a) + 1ULL)];
  uint64_t bx __attribute__((unused)) = pts.data[(b + b)];
  uint64_t by __attribute__((unused)) = pts.data[((b + b) + 1ULL)];
  uint64_t cx __attribute__((unused)) = pts.data[(c + c)];
  uint64_t cy __attribute__((unused)) = pts.data[((c + c) + 1ULL)];
  return (((bx - ax) * (cy - ay)) - ((by - ay) * (cx - ax)));
}

uint64_t find_bottom(forge_span_u64_t pts __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t best __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t iy __attribute__((unused)) = pts.data[((i + i) + 1ULL)];
      uint64_t by __attribute__((unused)) = pts.data[((best + best) + 1ULL)];
      if ((iy < by)) {
        best = i;

      } else if ((iy == by)) {
        uint64_t ix __attribute__((unused)) = pts.data[(i + i)];
        uint64_t bx __attribute__((unused)) = pts.data[(best + best)];
        if ((ix < bx)) {
          best = i;

        }

      }
      i = (i + 1ULL);
    }

  }
  return best;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

