/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t skip_search(forge_span_u64_t next __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t max_level __attribute__((unused)), uint64_t target __attribute__((unused)));
int main();

uint64_t skip_search(forge_span_u64_t next __attribute__((unused)), forge_span_u64_t values __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t max_level __attribute__((unused)), uint64_t target __attribute__((unused))) {
  uint64_t sentinel __attribute__((unused)) = n;
  uint64_t cur __attribute__((unused)) = 0ULL;
  uint64_t lev __attribute__((unused)) = max_level;
  {
    while ((lev > 0ULL)) {
      lev = (lev - 1ULL);
      uint64_t steps __attribute__((unused)) = 0ULL;
      {
        while ((steps < n)) {
          if ((cur < n)) {
            uint64_t nxt_idx __attribute__((unused)) = ((lev * n) + cur);
            if ((nxt_idx < (max_level * n))) {
              uint64_t nxt __attribute__((unused)) = next.data[nxt_idx];
              if (((nxt < n) && (values.data[nxt] <= target))) {
                cur = nxt;
                steps = (steps + 1ULL);

              } else {
                steps = n;

              }

            } else {
              steps = n;

            }

          } else {
            steps = n;

          }
        }

      }
    }

  }
  if (((cur < n) && (values.data[cur] == target))) {
    return cur;
  } else {
    return sentinel;
  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

