/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t rle_decode(forge_span_u64_t vals __attribute__((unused)), forge_span_u64_t counts __attribute__((unused)), uint64_t n_runs __attribute__((unused)), forge_span_u64_t output __attribute__((unused)), uint64_t out_cap __attribute__((unused)));
int main();

uint64_t rle_decode(forge_span_u64_t vals __attribute__((unused)), forge_span_u64_t counts __attribute__((unused)), uint64_t n_runs __attribute__((unused)), forge_span_u64_t output __attribute__((unused)), uint64_t out_cap __attribute__((unused))) {
  uint64_t out_idx __attribute__((unused)) = 0ULL;
  uint64_t r __attribute__((unused)) = 0ULL;
  {
    while ((r < n_runs)) {
      uint64_t val __attribute__((unused)) = vals.data[r];
      uint64_t cnt __attribute__((unused)) = counts.data[r];
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while (((j < cnt) && (out_idx < out_cap))) {
          output.data[out_idx] = val;
          out_idx = (out_idx + 1ULL);
          j = (j + 1ULL);
        }

      }
      r = (r + 1ULL);
    }

  }
  return out_idx;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

