/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void jacobi_step(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t x_old __attribute__((unused)), forge_span_u64_t x_new __attribute__((unused)), uint64_t n __attribute__((unused)));
uint64_t residual_norm(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t x __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

void jacobi_step(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), forge_span_u64_t x_old __attribute__((unused)), forge_span_u64_t x_new __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t sigma __attribute__((unused)) = 0ULL;
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < n)) {
          if ((j != i)) {
            uint64_t aij __attribute__((unused)) = a.data[((i * n) + j)];
            sigma = (sigma + (aij * x_old.data[j]));

          }
          j = (j + 1ULL);
        }

      }
      uint64_t diag __attribute__((unused)) = a.data[((i * n) + i)];
      if ((diag > 0ULL)) {
        x_new.data[i] = ((b.data[i] - sigma) / diag);

      } else {
        x_new.data[i] = 0ULL;

      }
      i = (i + 1ULL);
    }

  }
}

uint64_t residual_norm(forge_span_u64_t a __attribute__((unused)), forge_span_u64_t x __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t norm __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t ax_i __attribute__((unused)) = 0ULL;
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < n)) {
          ax_i = (ax_i + (a.data[((i * n) + j)] * x.data[j]));
          j = (j + 1ULL);
        }

      }
      uint64_t diff;
      if ((ax_i >= b.data[i])) {
        diff = (ax_i - b.data[i]);
      } else {
        diff = (b.data[i] - ax_i);
      }
      norm = (norm + diff);
      i = (i + 1ULL);
    }

  }
  return norm;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

