/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Tuple typedefs */
typedef struct { uint64_t _0; uint64_t _1; } __forge_tuple_u64_u64_t;

/* Forward declarations */
__forge_tuple_u64_u64_t gap_insert(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t ch __attribute__((unused)));
__forge_tuple_u64_u64_t gap_delete(uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t cap __attribute__((unused)));
__forge_tuple_u64_u64_t gap_move(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t pos __attribute__((unused)));
int main();

__forge_tuple_u64_u64_t gap_insert(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t ch __attribute__((unused))) {
  buf.data[gap_start] = ch;
  return FORGE_AGG(__forge_tuple_u64_u64_t, (gap_start + 1ULL), gap_end);
}

__forge_tuple_u64_u64_t gap_delete(uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  return FORGE_AGG(__forge_tuple_u64_u64_t, (gap_start - 1ULL), gap_end);
}

__forge_tuple_u64_u64_t gap_move(forge_span_u64_t buf __attribute__((unused)), uint64_t cap __attribute__((unused)), uint64_t gap_start __attribute__((unused)), uint64_t gap_end __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t gap_size __attribute__((unused)) = (gap_end - gap_start);
  uint64_t gs __attribute__((unused)) = gap_start;
  uint64_t ge __attribute__((unused)) = gap_end;
  {
    while ((gs > pos)) {
      ge = (ge - 1ULL);
      gs = (gs - 1ULL);
      buf.data[ge] = buf.data[gs];
    }

  }
  {
    while (((gs < pos) && (ge < cap))) {
      buf.data[gs] = buf.data[ge];
      gs = (gs + 1ULL);
      ge = (ge + 1ULL);
    }

  }
  return FORGE_AGG(__forge_tuple_u64_u64_t, gs, ge);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

