/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t interval_schedule(forge_span_u64_t starts __attribute__((unused)), forge_span_u64_t ends __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t selected __attribute__((unused)));
int main();

uint64_t interval_schedule(forge_span_u64_t starts __attribute__((unused)), forge_span_u64_t ends __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t selected __attribute__((unused))) {
  selected.data[0ULL] = 0ULL;
  uint64_t count __attribute__((unused)) = 1ULL;
  uint64_t last_end __attribute__((unused)) = ends.data[0ULL];
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      if ((starts.data[i] >= last_end)) {
        selected.data[count] = i;
        last_end = ends.data[i];
        count = (count + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

