/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t optimal_k(uint64_t m_bits __attribute__((unused)), uint64_t n_elements __attribute__((unused)));
uint64_t approx_fpr(uint64_t m_bits __attribute__((unused)), uint64_t n_elements __attribute__((unused)), uint64_t k __attribute__((unused)));
int main();

uint64_t optimal_k(uint64_t m_bits __attribute__((unused)), uint64_t n_elements __attribute__((unused))) {
  uint64_t k __attribute__((unused)) = ((m_bits * 45ULL) / (n_elements * 65ULL));
  if ((k == 0ULL)) {
    return 1ULL;
  } else {
    return k;
  }
}

uint64_t approx_fpr(uint64_t m_bits __attribute__((unused)), uint64_t n_elements __attribute__((unused)), uint64_t k __attribute__((unused))) {
  uint64_t fill __attribute__((unused)) = (((k * n_elements) * 1000ULL) / m_bits);
  uint64_t remain;
  if ((fill >= 1000ULL)) {
    remain = 0ULL;
  } else {
    remain = (1000ULL - fill);
  }
  uint64_t fpr __attribute__((unused)) = remain;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < k)) {
      fpr = ((fpr * remain) / 1000ULL);
      i = (i + 1ULL);
    }

  }
  return fpr;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

