/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t schoolbook_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
uint64_t karatsuba_step(uint64_t a_lo __attribute__((unused)), uint64_t a_hi __attribute__((unused)), uint64_t b_lo __attribute__((unused)), uint64_t b_hi __attribute__((unused)), uint64_t base __attribute__((unused)));
int main();

uint64_t schoolbook_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  return (a * b);
}

uint64_t karatsuba_step(uint64_t a_lo __attribute__((unused)), uint64_t a_hi __attribute__((unused)), uint64_t b_lo __attribute__((unused)), uint64_t b_hi __attribute__((unused)), uint64_t base __attribute__((unused))) {
  uint64_t z0 __attribute__((unused)) = (a_lo * b_lo);
  uint64_t z2 __attribute__((unused)) = (a_hi * b_hi);
  uint64_t sum_a __attribute__((unused)) = (a_lo + a_hi);
  uint64_t sum_b __attribute__((unused)) = (b_lo + b_hi);
  uint64_t z1_full __attribute__((unused)) = (sum_a * sum_b);
  uint64_t z1 __attribute__((unused)) = ((z1_full - z0) - z2);
  return ((((z2 * base) * base) + (z1 * base)) + z0);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

