/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t coalesce(forge_span_u64_t starts __attribute__((unused)), forge_span_u64_t sizes __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out_starts __attribute__((unused)), forge_span_u64_t out_sizes __attribute__((unused)));
int main();

uint64_t coalesce(forge_span_u64_t starts __attribute__((unused)), forge_span_u64_t sizes __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t out_starts __attribute__((unused)), forge_span_u64_t out_sizes __attribute__((unused))) {
  out_starts.data[0ULL] = starts.data[0ULL];
  out_sizes.data[0ULL] = sizes.data[0ULL];
  uint64_t wi __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t prev_end __attribute__((unused)) = (out_starts.data[wi] + out_sizes.data[wi]);
      if ((prev_end == starts.data[i])) {
        out_sizes.data[wi] = (out_sizes.data[wi] + sizes.data[i]);

      } else {
        wi = (wi + 1ULL);
        if ((wi < n)) {
          out_starts.data[wi] = starts.data[i];
          out_sizes.data[wi] = sizes.data[i];

        }

      }
      i = (i + 1ULL);
    }

  }
  return (wi + 1ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

