/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void reverse_segment(forge_span_u64_t s __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t count_words(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t sep __attribute__((unused)));
int main();

void reverse_segment(forge_span_u64_t s __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  uint64_t left __attribute__((unused)) = lo;
  uint64_t right __attribute__((unused)) = hi;
  {
    while (((left + 1ULL) < right)) {
      right = (right - 1ULL);
      uint64_t tmp __attribute__((unused)) = s.data[left];
      s.data[left] = s.data[right];
      s.data[right] = tmp;
      left = (left + 1ULL);
    }

  }
}

uint64_t count_words(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t sep __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  _Bool in_word __attribute__((unused)) = 0;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      if ((s.data[i] == sep)) {
        in_word = 0;

      } else {
        if ((in_word == 0)) {
          count = (count + 1ULL);
          in_word = 1;

        }

      }
      i = (i + 1ULL);
    }

  }
  return count;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

