/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t reverse_bits(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused)));
void bit_reversal_permute(forge_span_u64_t s __attribute__((unused)), forge_span_u64_t tmp __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t nbits __attribute__((unused)));
int main();

uint64_t reverse_bits(uint64_t val __attribute__((unused)), uint64_t nbits __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t rev __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < nbits)) {
      rev = ((rev * 2ULL) + (v % 2ULL));
      v = (v / 2ULL);
      i = (i + 1ULL);
    }

  }
  return rev;
}

void bit_reversal_permute(forge_span_u64_t s __attribute__((unused)), forge_span_u64_t tmp __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t nbits __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = reverse_bits(i, nbits);
      if ((j < n)) {
        tmp.data[i] = s.data[j];

      } else {
        tmp.data[i] = 0ULL;

      }
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

