/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t leading_zeros_approx(uint64_t val __attribute__((unused)));
void hll_add(forge_span_u64_t registers __attribute__((unused)), uint64_t m __attribute__((unused)), uint64_t hash __attribute__((unused)));
uint64_t hll_estimate(forge_span_u64_t registers __attribute__((unused)), uint64_t m __attribute__((unused)));
int main();

uint64_t leading_zeros_approx(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t cnt __attribute__((unused)) = 0ULL;
  {
    while (((v > 0ULL) && (cnt < 64ULL))) {
      v = (v / 2ULL);
      cnt = (cnt + 1ULL);
    }

  }
  if ((val == 0ULL)) {
    return 64ULL;
  } else {
    return (64ULL - cnt);
  }
}

void hll_add(forge_span_u64_t registers __attribute__((unused)), uint64_t m __attribute__((unused)), uint64_t hash __attribute__((unused))) {
  uint64_t idx __attribute__((unused)) = (hash % m);
  uint64_t lz __attribute__((unused)) = leading_zeros_approx((hash / m));
  if ((lz > registers.data[idx])) {
    registers.data[idx] = lz;

  }
}

uint64_t hll_estimate(forge_span_u64_t registers __attribute__((unused)), uint64_t m __attribute__((unused))) {
  uint64_t sum __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < m)) {
      sum = (sum + registers.data[i]);
      i = (i + 1ULL);
    }

  }
  return sum;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

