/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t min_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)));
void extract_diag(forge_span_u64_t mat __attribute__((unused)), forge_span_u64_t diag __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused)));
int main();

uint64_t min_u64(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused))) {
  if ((a <= b)) {
    return a;
  } else {
    return b;
  }
}

void extract_diag(forge_span_u64_t mat __attribute__((unused)), forge_span_u64_t diag __attribute__((unused)), uint64_t rows __attribute__((unused)), uint64_t cols __attribute__((unused))) {
  uint64_t d __attribute__((unused)) = min_u64(rows, cols);
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < d)) {
      if (((i < diag.len) && (((i * cols) + i) < mat.len))) {
        diag.data[i] = mat.data[((i * cols) + i)];

      }
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

