/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t sift_up(forge_span_u64_t heap __attribute__((unused)), uint64_t pos __attribute__((unused)));
uint64_t decrease_key(forge_span_u64_t heap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t pos __attribute__((unused)), uint64_t new_val __attribute__((unused)));
int main();

uint64_t sift_up(forge_span_u64_t heap __attribute__((unused)), uint64_t pos __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = pos;
  {
    while ((i > 0ULL)) {
      uint64_t parent __attribute__((unused)) = ((i - 1ULL) / 2ULL);
      if ((heap.data[i] < heap.data[parent])) {
        uint64_t tmp __attribute__((unused)) = heap.data[i];
        heap.data[i] = heap.data[parent];
        heap.data[parent] = tmp;
        i = parent;

      } else {
        i = 0ULL;

      }
    }

  }
  return i;
}

uint64_t decrease_key(forge_span_u64_t heap __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t pos __attribute__((unused)), uint64_t new_val __attribute__((unused))) {
  heap.data[pos] = new_val;
  uint64_t v __attribute__((unused)) = sift_up(heap, pos);
  return v;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

