/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void z_naive(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t z __attribute__((unused)));
int main();

void z_naive(forge_span_u64_t s __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t z __attribute__((unused))) {
  z.data[0ULL] = n;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i < n)) {
      uint64_t j __attribute__((unused)) = 0ULL;
      _Bool done __attribute__((unused)) = 0;
      {
        while ((done == 0)) {
          if ((((i + j) < n) && (s.data[j] == s.data[(i + j)]))) {
            j = (j + 1ULL);

          } else {
            done = 1;

          }
        }

      }
      z.data[i] = j;
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

