/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void dag_relax(forge_span_u64_t dist __attribute__((unused)), forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused)));
int main();

void dag_relax(forge_span_u64_t dist __attribute__((unused)), forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  uint64_t u __attribute__((unused)) = 0ULL;
  {
    while ((u < n)) {
      uint64_t v __attribute__((unused)) = 0ULL;
      {
        while ((v < n)) {
          if ((((u * n) + v) < (n * n))) {
            uint64_t w __attribute__((unused)) = adj.data[((u * n) + v)];
            if ((((((w > 0ULL) && (v < n)) && (u < n)) && ((dist.data[u] + w) > dist.data[v])) && ((dist.data[u] + w) <= cap))) {
              dist.data[v] = (dist.data[u] + w);

            }

          }
          v = (v + 1ULL);
        }

      }
      u = (u + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

