/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t merge_dedup(forge_span_u64_t a __attribute__((unused)), uint64_t na __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t nb __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t cap __attribute__((unused)));
int main();

uint64_t merge_dedup(forge_span_u64_t a __attribute__((unused)), uint64_t na __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t nb __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  uint64_t ia __attribute__((unused)) = 0ULL;
  uint64_t ib __attribute__((unused)) = 0ULL;
  uint64_t oc __attribute__((unused)) = 0ULL;
  uint64_t last __attribute__((unused)) = 0ULL;
  _Bool has_last __attribute__((unused)) = 0;
  {
    while (((ia < na) || (ib < nb))) {
      _Bool pick_a;
      if (((ia < na) && (ib < nb))) {
        pick_a = (a.data[ia] <= b.data[ib]);
      } else {
        if ((ia < na)) {
          pick_a = 1;
        } else {
          pick_a = 0;
        }
      }
      uint64_t val;
      if (pick_a) {
        val = a.data[ia];
      } else {
        val = b.data[ib];
      }
      if (((has_last == 0) || (val > last))) {
        if ((oc < cap)) {
          out.data[oc] = val;

        }
        oc = (oc + 1ULL);
        last = val;
        has_last = 1;

      }
      if (pick_a) {
        ia = (ia + 1ULL);

      } else {
        ib = (ib + 1ULL);

      }
    }

  }
  return oc;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

