/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void downsample(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t w __attribute__((unused)), uint64_t h __attribute__((unused)));
int main();

void downsample(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t w __attribute__((unused)), uint64_t h __attribute__((unused))) {
  uint64_t hw __attribute__((unused)) = (w / 2ULL);
  uint64_t hh __attribute__((unused)) = (h / 2ULL);
  uint64_t r __attribute__((unused)) = 0ULL;
  {
    while ((r < hh)) {
      uint64_t c __attribute__((unused)) = 0ULL;
      {
        while ((c < hw)) {
          uint64_t r2 __attribute__((unused)) = (r * 2ULL);
          uint64_t c2 __attribute__((unused)) = (c * 2ULL);
          if ((((((r2 * w) + c2) + w) + 1ULL) < (w * h))) {
            uint64_t avg __attribute__((unused)) = ((((src.data[((r2 * w) + c2)] + src.data[(((r2 * w) + c2) + 1ULL)]) + src.data[(((r2 + 1ULL) * w) + c2)]) + src.data[((((r2 + 1ULL) * w) + c2) + 1ULL)]) / 4ULL);
            if ((((r * hw) + c) < (hw * hh))) {
              dst.data[((r * hw) + c)] = avg;

            }

          }
          c = (c + 1ULL);
        }

      }
      r = (r + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

