/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t slip_encode(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused)));
int main();

uint64_t slip_encode(forge_span_u64_t src __attribute__((unused)), forge_span_u64_t dst __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t cap __attribute__((unused))) {
  uint64_t end_byte __attribute__((unused)) = 192ULL;
  uint64_t esc_byte __attribute__((unused)) = 219ULL;
  uint64_t out __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      uint64_t b __attribute__((unused)) = (src.data[i] & 255ULL);
      if ((b == end_byte)) {
        dst.data[out] = esc_byte;
        out = (out + 1ULL);
        dst.data[out] = 220ULL;
        out = (out + 1ULL);

      } else if ((b == esc_byte)) {
        dst.data[out] = esc_byte;
        out = (out + 1ULL);
        dst.data[out] = 221ULL;
        out = (out + 1ULL);

      } else {
        dst.data[out] = b;
        out = (out + 1ULL);

      }
      i = (i + 1ULL);
    }

  }
  return out;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

