/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t bipartite_check(forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t color __attribute__((unused)));
int main();

uint64_t bipartite_check(forge_span_u64_t adj __attribute__((unused)), uint64_t n __attribute__((unused)), forge_span_u64_t color __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n)) {
      color.data[i] = 0ULL;
      i = (i + 1ULL);
    }

  }
  uint64_t ok __attribute__((unused)) = 1ULL;
  uint64_t u __attribute__((unused)) = 0ULL;
  {
    while ((u < n)) {
      uint64_t v __attribute__((unused)) = 0ULL;
      {
        while ((v < n)) {
          if (((((u * n) + v) < (n * n)) && (adj.data[((u * n) + v)] > 0ULL))) {
            if (((color.data[u] == color.data[v]) && (color.data[u] > 0ULL))) {
              ok = 0ULL;

            }
            if (((color.data[v] == 0ULL) && (color.data[u] > 0ULL))) {
              color.data[v] = (3ULL - color.data[u]);

            }

          }
          v = (v + 1ULL);
        }

      }
      if ((color.data[u] == 0ULL)) {
        color.data[u] = 1ULL;

      }
      u = (u + 1ULL);
    }

  }
  return ok;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

