/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void kronecker(forge_span_u64_t a __attribute__((unused)), uint64_t ra __attribute__((unused)), uint64_t ca __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t rb __attribute__((unused)), uint64_t cb __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t orows __attribute__((unused)), uint64_t ocols __attribute__((unused)));
int main();

void kronecker(forge_span_u64_t a __attribute__((unused)), uint64_t ra __attribute__((unused)), uint64_t ca __attribute__((unused)), forge_span_u64_t b __attribute__((unused)), uint64_t rb __attribute__((unused)), uint64_t cb __attribute__((unused)), forge_span_u64_t out __attribute__((unused)), uint64_t orows __attribute__((unused)), uint64_t ocols __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < ra)) {
      uint64_t j __attribute__((unused)) = 0ULL;
      {
        while ((j < ca)) {
          uint64_t aij __attribute__((unused)) = a.data[((i * ca) + j)];
          uint64_t p __attribute__((unused)) = 0ULL;
          {
            while ((p < rb)) {
              uint64_t q __attribute__((unused)) = 0ULL;
              {
                while ((q < cb)) {
                  uint64_t row __attribute__((unused)) = ((i * rb) + p);
                  uint64_t col __attribute__((unused)) = ((j * cb) + q);
                  if (((row < orows) && (col < ocols))) {
                    if ((((row * ocols) + col) < (orows * ocols))) {
                      out.data[((row * ocols) + col)] = (aij * b.data[((p * cb) + q)]);

                    }

                  }
                  q = (q + 1ULL);
                }

              }
              p = (p + 1ULL);
            }

          }
          j = (j + 1ULL);
        }

      }
      i = (i + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

