/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused)));
uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused)));
uint64_t mod_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused)));
uint64_t ecc_add_x(uint64_t x1 __attribute__((unused)), uint64_t y1 __attribute__((unused)), uint64_t x2 __attribute__((unused)), uint64_t y2 __attribute__((unused)), uint64_t slope __attribute__((unused)), uint64_t p __attribute__((unused)));
int main();

uint64_t mod_sub(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused))) {
  if ((a >= b)) {
    return ((a - b) % p);
  } else {
    return ((p - ((b - a) % p)) % p);
  }
}

uint64_t mod_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused))) {
  return ((a + b) % p);
}

uint64_t mod_mul(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t p __attribute__((unused))) {
  return ((a * b) % p);
}

uint64_t ecc_add_x(uint64_t x1 __attribute__((unused)), uint64_t y1 __attribute__((unused)), uint64_t x2 __attribute__((unused)), uint64_t y2 __attribute__((unused)), uint64_t slope __attribute__((unused)), uint64_t p __attribute__((unused))) {
  uint64_t s2 __attribute__((unused)) = mod_mul(slope, slope, p);
  uint64_t tmp __attribute__((unused)) = mod_sub(s2, x1, p);
  uint64_t x3 __attribute__((unused)) = mod_sub(tmp, x2, p);
  return x3;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

