/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t isqrt(uint64_t n __attribute__((unused)));
int main();

uint64_t isqrt(uint64_t n __attribute__((unused))) {
  uint64_t x __attribute__((unused)) = n;
  uint64_t steps __attribute__((unused)) = 0ULL;
  uint64_t max_steps __attribute__((unused)) = 40ULL;
  {
    while ((steps < max_steps)) {
      uint64_t nx __attribute__((unused)) = ((x + (n / x)) / 2ULL);
      if ((nx >= x)) {
        steps = max_steps;

      } else {
        x = nx;
        if ((x == 0ULL)) {
          x = 1ULL;

        }
        steps = (steps + 1ULL);

      }
    }

  }
  if (((x * x) > n)) {
    x = (x - 1ULL);

  }
  return x;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

