/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t entropy_approx(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t hist __attribute__((unused)), uint64_t nbins __attribute__((unused)));
int main();

uint64_t entropy_approx(forge_span_u64_t data __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t w __attribute__((unused)), forge_span_u64_t hist __attribute__((unused)), uint64_t nbins __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < nbins)) {
      hist.data[j] = 0ULL;
      j = (j + 1ULL);
    }

  }
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < w)) {
      uint64_t b __attribute__((unused)) = (data.data[i] % nbins);
      hist.data[b] = (hist.data[b] + 1ULL);
      i = (i + 1ULL);
    }

  }
  uint64_t distinct __attribute__((unused)) = 0ULL;
  uint64_t k __attribute__((unused)) = 0ULL;
  {
    while ((k < nbins)) {
      if ((hist.data[k] > 0ULL)) {
        distinct = (distinct + 1ULL);

      }
      k = (k + 1ULL);
    }

  }
  return distinct;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

