/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t sum_n(uint64_t n __attribute__((unused)));
uint64_t factorial(uint64_t n __attribute__((unused)));
uint64_t count_down(uint64_t start __attribute__((unused)));
int main();

uint64_t sum_n(uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i <= n)) {
      acc = (acc + i);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t factorial(uint64_t n __attribute__((unused))) {
  uint64_t acc __attribute__((unused)) = 1ULL;
  uint64_t i __attribute__((unused)) = 1ULL;
  {
    while ((i <= n)) {
      acc = (acc * i);
      i = (i + 1ULL);
    }

  }
  return acc;
}

uint64_t count_down(uint64_t start __attribute__((unused))) {
  uint64_t count __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = start;
  {
    while ((i > 0ULL)) {
      i = (i - 1ULL);
      count = (count + 1ULL);
    }

  }
  return count;
}

int __attribute__((weak)) main() {
  uint64_t s5 __attribute__((unused)) = sum_n(5ULL);
  uint64_t s10 __attribute__((unused)) = sum_n(10ULL);
  uint64_t f5 __attribute__((unused)) = factorial(5ULL);
  uint64_t f6 __attribute__((unused)) = factorial(6ULL);
  uint64_t cd7 __attribute__((unused)) = count_down(7ULL);
  return (int)((((s5 + s10) + f5) + cd7));

}

