/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void cofactor_2x2(forge_span_u64_t mat __attribute__((unused)), forge_span_u64_t minor __attribute__((unused)), uint64_t r __attribute__((unused)), uint64_t c __attribute__((unused)));
int main();

void cofactor_2x2(forge_span_u64_t mat __attribute__((unused)), forge_span_u64_t minor __attribute__((unused)), uint64_t r __attribute__((unused)), uint64_t c __attribute__((unused))) {
  uint64_t out __attribute__((unused)) = 0ULL;
  uint64_t row __attribute__((unused)) = 0ULL;
  {
    while ((row < 3ULL)) {
      if ((row != r)) {
        uint64_t col __attribute__((unused)) = 0ULL;
        {
          while ((col < 3ULL)) {
            if ((col != c)) {
              if ((out < 4ULL)) {
                uint64_t idx __attribute__((unused)) = ((row * 3ULL) + col);
                if ((idx < 9ULL)) {
                  minor.data[out] = mat.data[idx];

                }
                out = (out + 1ULL);

              }

            }
            col = (col + 1ULL);
          }

        }

      }
      row = (row + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

