/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
void ntt_butterfly(forge_span_u64_t a __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t h __attribute__((unused)), uint64_t p __attribute__((unused)), forge_span_u64_t twiddle __attribute__((unused)));
int main();

void ntt_butterfly(forge_span_u64_t a __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t h __attribute__((unused)), uint64_t p __attribute__((unused)), forge_span_u64_t twiddle __attribute__((unused))) {
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < h)) {
      uint64_t w __attribute__((unused)) = (twiddle.data[j] % p);
      uint64_t u_val __attribute__((unused)) = (a.data[j] % p);
      uint64_t idx __attribute__((unused)) = (j + h);
      if ((idx < n)) {
        uint64_t v_val __attribute__((unused)) = (((a.data[idx] % p) * w) % p);
        a.data[j] = ((u_val + v_val) % p);
        a.data[idx] = (((u_val + p) - v_val) % p);

      }
      j = (j + 1ULL);
    }

  }
  uint64_t k __attribute__((unused)) = h;
  {
    while ((k < n)) {
      a.data[k] = (a.data[k] % p);
      k = (k + 1ULL);
    }

  }
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

