/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t btree_split(forge_span_u64_t keys __attribute__((unused)), forge_span_u64_t new_node __attribute__((unused)), uint64_t n __attribute__((unused)));
int main();

uint64_t btree_split(forge_span_u64_t keys __attribute__((unused)), forge_span_u64_t new_node __attribute__((unused)), uint64_t n __attribute__((unused))) {
  uint64_t mid __attribute__((unused)) = (n / 2ULL);
  uint64_t j __attribute__((unused)) = 0ULL;
  uint64_t src __attribute__((unused)) = (mid + 1ULL);
  {
    while ((src < n)) {
      if ((j < n)) {
        new_node.data[j] = keys.data[src];

      }
      j = (j + 1ULL);
      src = (src + 1ULL);
    }

  }
  return mid;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

