/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t zobrist_hash(forge_span_u64_t board __attribute__((unused)), forge_span_u64_t table __attribute__((unused)), uint64_t ncells __attribute__((unused)), uint64_t nvals __attribute__((unused)));
int main();

uint64_t zobrist_hash(forge_span_u64_t board __attribute__((unused)), forge_span_u64_t table __attribute__((unused)), uint64_t ncells __attribute__((unused)), uint64_t nvals __attribute__((unused))) {
  uint64_t h __attribute__((unused)) = 0ULL;
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < ncells)) {
      uint64_t v __attribute__((unused)) = (board.data[i] % nvals);
      uint64_t idx __attribute__((unused)) = ((i * nvals) + v);
      if ((idx < (ncells * nvals))) {
        h = (h ^ table.data[idx]);

      }
      i = (i + 1ULL);
    }

  }
  return h;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

