/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t degree_centrality(forge_span_u64_t edges_u __attribute__((unused)), forge_span_u64_t edges_v __attribute__((unused)), forge_span_u64_t deg __attribute__((unused)), uint64_t n_nodes __attribute__((unused)), uint64_t n_edges __attribute__((unused)));
int main();

uint64_t degree_centrality(forge_span_u64_t edges_u __attribute__((unused)), forge_span_u64_t edges_v __attribute__((unused)), forge_span_u64_t deg __attribute__((unused)), uint64_t n_nodes __attribute__((unused)), uint64_t n_edges __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < n_nodes)) {
      deg.data[i] = 0ULL;
      i = (i + 1ULL);
    }

  }
  uint64_t e __attribute__((unused)) = 0ULL;
  {
    while ((e < n_edges)) {
      uint64_t u __attribute__((unused)) = edges_u.data[e];
      uint64_t v __attribute__((unused)) = edges_v.data[e];
      if ((u < n_nodes)) {
        deg.data[u] = (deg.data[u] + 1ULL);

      }
      if ((v < n_nodes)) {
        deg.data[v] = (deg.data[v] + 1ULL);

      }
      e = (e + 1ULL);
    }

  }
  uint64_t best __attribute__((unused)) = 0ULL;
  uint64_t best_d __attribute__((unused)) = deg.data[0ULL];
  uint64_t j __attribute__((unused)) = 1ULL;
  {
    while ((j < n_nodes)) {
      if ((deg.data[j] > best_d)) {
        best = j;
        best_d = deg.data[j];

      }
      j = (j + 1ULL);
    }

  }
  return best;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

