/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t xtime(uint64_t x __attribute__((unused)));
void mix_column(forge_span_u64_t col __attribute__((unused)));
int main();

uint64_t xtime(uint64_t x __attribute__((unused))) {
  uint64_t shifted __attribute__((unused)) = ((x * 2ULL) % 256ULL);
  if ((x >= 128ULL)) {
    return ((shifted ^ 27ULL) % 256ULL);
  } else {
    return shifted;
  }
}

void mix_column(forge_span_u64_t col __attribute__((unused))) {
  uint64_t a0 __attribute__((unused)) = col.data[0ULL];
  uint64_t a1 __attribute__((unused)) = col.data[1ULL];
  uint64_t a2 __attribute__((unused)) = col.data[2ULL];
  uint64_t a3 __attribute__((unused)) = col.data[3ULL];
  uint64_t x0 __attribute__((unused)) = xtime(a0);
  uint64_t x1 __attribute__((unused)) = xtime(a1);
  uint64_t x2 __attribute__((unused)) = xtime(a2);
  uint64_t x3 __attribute__((unused)) = xtime(a3);
  col.data[0ULL] = (((((x0 ^ x1) ^ a1) ^ a2) ^ a3) % 256ULL);
  col.data[1ULL] = (((((a0 ^ x1) ^ x2) ^ a2) ^ a3) % 256ULL);
  col.data[2ULL] = (((((a0 ^ a1) ^ x2) ^ x3) ^ a3) % 256ULL);
  col.data[3ULL] = (((((x0 ^ a0) ^ a1) ^ a2) ^ x3) % 256ULL);
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

