/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* Forward declarations */
uint64_t clamp_byte(uint64_t x __attribute__((unused)));
uint64_t is_in_range(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused)));
uint64_t saturating_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t max __attribute__((unused)));
uint64_t normalize(uint64_t x __attribute__((unused)), uint64_t range __attribute__((unused)));
uint64_t weighted_avg(uint64_t a __attribute__((unused)), uint64_t wa __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t wb __attribute__((unused)));
int main();

uint64_t clamp_byte(uint64_t x __attribute__((unused))) {
  if ((x > 255ULL)) {
    return 255ULL;
  } else {
    return x;
  }
}

uint64_t is_in_range(uint64_t x __attribute__((unused)), uint64_t lo __attribute__((unused)), uint64_t hi __attribute__((unused))) {
  if (((x >= lo) && (x <= hi))) {
    return 1ULL;
  } else {
    return 0ULL;
  }
}

uint64_t saturating_add(uint64_t a __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t max __attribute__((unused))) {
  if ((a > (max - b))) {
    return max;
  } else {
    return (a + b);
  }
}

uint64_t normalize(uint64_t x __attribute__((unused)), uint64_t range __attribute__((unused))) {
  return (x % range);
}

uint64_t weighted_avg(uint64_t a __attribute__((unused)), uint64_t wa __attribute__((unused)), uint64_t b __attribute__((unused)), uint64_t wb __attribute__((unused))) {
  return (((a * wa) + (b * wb)) / (wa + wb));
}

int __attribute__((weak)) main() {
  uint64_t c1 __attribute__((unused)) = clamp_byte(300ULL);
  uint64_t c2 __attribute__((unused)) = clamp_byte(100ULL);
  uint64_t r1 __attribute__((unused)) = is_in_range(5ULL, 1ULL, 10ULL);
  uint64_t r2 __attribute__((unused)) = is_in_range(15ULL, 1ULL, 10ULL);
  uint64_t s1 __attribute__((unused)) = saturating_add(200ULL, 100ULL, 255ULL);
  uint64_t s2 __attribute__((unused)) = saturating_add(50ULL, 30ULL, 255ULL);
  uint64_t n1 __attribute__((unused)) = normalize(17ULL, 5ULL);
  uint64_t n2 __attribute__((unused)) = normalize(100ULL, 7ULL);
  uint64_t wa __attribute__((unused)) = weighted_avg(10ULL, 3ULL, 20ULL, 7ULL);
  return (int)(((((((((c1 + c2) + r1) + r2) + s1) + s2) + n1) + n2) + wa));

}

