/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t augment_flow(forge_span_u64_t path __attribute__((unused)), forge_span_u64_t cap __attribute__((unused)), forge_span_u64_t flow __attribute__((unused)), uint64_t plen __attribute__((unused)), uint64_t n_edges __attribute__((unused)));
int main();

uint64_t augment_flow(forge_span_u64_t path __attribute__((unused)), forge_span_u64_t cap __attribute__((unused)), forge_span_u64_t flow __attribute__((unused)), uint64_t plen __attribute__((unused)), uint64_t n_edges __attribute__((unused))) {
  uint64_t bottleneck __attribute__((unused)) = cap.data[path.data[0ULL]];
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < plen)) {
      uint64_t e __attribute__((unused)) = path.data[i];
      if ((e < n_edges)) {
        uint64_t residual __attribute__((unused)) = (cap.data[e] - flow.data[e]);
        if ((residual < bottleneck)) {
          bottleneck = residual;

        }

      }
      i = (i + 1ULL);
    }

  }
  uint64_t j __attribute__((unused)) = 0ULL;
  {
    while ((j < plen)) {
      uint64_t e __attribute__((unused)) = path.data[j];
      if ((e < n_edges)) {
        flow.data[e] = (flow.data[e] + bottleneck);

      }
      j = (j + 1ULL);
    }

  }
  return bottleneck;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

