/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t reservoir_sample(forge_span_u64_t stream __attribute__((unused)), forge_span_u64_t weights __attribute__((unused)), forge_span_u64_t reservoir __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t seed __attribute__((unused)));
int main();

uint64_t reservoir_sample(forge_span_u64_t stream __attribute__((unused)), forge_span_u64_t weights __attribute__((unused)), forge_span_u64_t reservoir __attribute__((unused)), uint64_t n __attribute__((unused)), uint64_t k __attribute__((unused)), uint64_t seed __attribute__((unused))) {
  uint64_t i __attribute__((unused)) = 0ULL;
  {
    while ((i < k)) {
      if ((i < n)) {
        reservoir.data[i] = stream.data[i];

      }
      i = (i + 1ULL);
    }

  }
  uint64_t j __attribute__((unused)) = k;
  uint64_t rng __attribute__((unused)) = seed;
  {
    while ((j < n)) {
      rng = (((rng * 6364136223846793005ULL) + 1ULL) % 1000000007ULL);
      uint64_t slot __attribute__((unused)) = (rng % k);
      if ((weights.data[j] > (rng % 100ULL))) {
        reservoir.data[slot] = stream.data[j];

      }
      j = (j + 1ULL);
    }

  }
  return n;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

