/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif
#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint64_t* data; uintptr_t len; } forge_span_u64_t;

/* Forward declarations */
uint64_t patricia_lookup(forge_span_u64_t left __attribute__((unused)), forge_span_u64_t right __attribute__((unused)), uint64_t n_nodes __attribute__((unused)), uint64_t key __attribute__((unused)), uint64_t depth __attribute__((unused)));
int main();

uint64_t patricia_lookup(forge_span_u64_t left __attribute__((unused)), forge_span_u64_t right __attribute__((unused)), uint64_t n_nodes __attribute__((unused)), uint64_t key __attribute__((unused)), uint64_t depth __attribute__((unused))) {
  uint64_t node __attribute__((unused)) = 0ULL;
  uint64_t d __attribute__((unused)) = 0ULL;
  uint64_t k __attribute__((unused)) = key;
  {
    while ((d < depth)) {
      uint64_t bit __attribute__((unused)) = (k % 2ULL);
      k = (k / 2ULL);
      uint64_t next;
      if ((bit == 0ULL)) {
        next = left.data[node];
      } else {
        next = right.data[node];
      }
      if ((next < n_nodes)) {
        node = next;

      }
      d = (d + 1ULL);
    }

  }
  return node;
}

int __attribute__((weak)) main() {
  return (int)(0ULL);

}

