/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;
typedef struct { forge_span_u32_t* data; uintptr_t len; } forge_span_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);
typedef float (*forge_fn_f32_u64_u64_ret_f32_t)(float, uint64_t, uint64_t);

__device__ uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t shfl_up_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_or(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_xor(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_and(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_sub(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_exch(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

__device__ uint64_t lane_id(void);  /* extern: forge_gpu */

__device__ uint64_t warp_id(void);  /* extern: forge_gpu */

__device__ float shfl_xor_sync_f32(float val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ float shfl_down_sync_f32(float val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

static const uint32_t M31_P = 2147483647ULL;

/* Forward declarations */
static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused)));
uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_neg(uint32_t a __attribute__((unused)));
uint32_t m31_double(uint32_t a __attribute__((unused)));
uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused)));
__global__ void accumulate_numerators(forge_span_span_u32_t col_ptrs __attribute__((unused)), forge_span_u32_t col_indices __attribute__((unused)), forge_span_u32_t b_coeffs __attribute__((unused)), forge_span_u32_t c_coeffs __attribute__((unused)), uint64_t n_batch_cols __attribute__((unused)), uint64_t n_rows __attribute__((unused)), forge_span_u32_t out0 __attribute__((unused)), forge_span_u32_t out1 __attribute__((unused)), forge_span_u32_t out2 __attribute__((unused)), forge_span_u32_t out3 __attribute__((unused)));
int main();

static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

static __host__ __device__ __forceinline__ uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = (((uint64_t)a) + ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((s >= p)) {
    r = (s - p);
  } else {
    r = s;
  }
  return ((uint32_t)r);
}

static __host__ __device__ __forceinline__ uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t a64 __attribute__((unused)) = ((uint64_t)a);
  uint64_t b64 __attribute__((unused)) = ((uint64_t)b);
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((a64 >= b64)) {
    r = (a64 - b64);
  } else {
    r = ((a64 + p) - b64);
  }
  return ((uint32_t)r);
}

static __host__ __device__ __forceinline__ uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t prod __attribute__((unused)) = (((uint64_t)a) * ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r __attribute__((unused)) = (prod % p);
  return ((uint32_t)r);
}

uint32_t m31_neg(uint32_t a __attribute__((unused))) {
  if ((a == 0ULL)) {
    return 0ULL;
  } else {
    return (M31_P - a);
  }
}

uint32_t m31_double(uint32_t a __attribute__((unused))) {
  return m31_add(a, a);
}

uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ac __attribute__((unused)) = m31_mul(a_re, b_re);
  uint32_t bd __attribute__((unused)) = m31_mul(a_im, b_im);
  return m31_sub(ac, bd);
}

uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ad __attribute__((unused)) = m31_mul(a_re, b_im);
  uint32_t bc __attribute__((unused)) = m31_mul(a_im, b_re);
  return m31_add(ad, bc);
}

uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_add(a_re, b_re);
}

uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_add(a_im, b_im);
}

uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_sub(a_re, b_re);
}

uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_sub(a_im, b_im);
}

uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_sub(m31_double(bd_re), bd_im);
  return m31_add(ac_re, t);
}

uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_add(bd_re, m31_double(bd_im));
  return m31_add(ac_im, t);
}

uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, d_re, d_im);
  uint32_t bc_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, c_re, c_im);
  return m31_add(ad_re, bc_re);
}

uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, d_re, d_im);
  uint32_t bc_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, c_re, c_im);
  return m31_add(ad_im, bc_im);
}

uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused))) {
  uint32_t lo __attribute__((unused)) = (v & M31_P);
  uint32_t hi __attribute__((unused)) = (v >> 31ULL);
  uint32_t r __attribute__((unused)) = (lo + hi);
  if ((r >= M31_P)) {
    return (r - M31_P);
  } else {
    return r;
  }
}

__global__ void accumulate_numerators(forge_span_span_u32_t col_ptrs __attribute__((unused)), forge_span_u32_t col_indices __attribute__((unused)), forge_span_u32_t b_coeffs __attribute__((unused)), forge_span_u32_t c_coeffs __attribute__((unused)), uint64_t n_batch_cols __attribute__((unused)), uint64_t n_rows __attribute__((unused)), forge_span_u32_t out0 __attribute__((unused)), forge_span_u32_t out1 __attribute__((unused)), forge_span_u32_t out2 __attribute__((unused)), forge_span_u32_t out3 __attribute__((unused))) {
  uint64_t row __attribute__((unused)) = ((blockIdx_x * blockDim_x) + threadIdx_x);
  if ((row < n_rows)) {
    uint32_t a0 __attribute__((unused)) = 0ULL;
    uint32_t a1 __attribute__((unused)) = 0ULL;
    uint32_t a2 __attribute__((unused)) = 0ULL;
    uint32_t a3 __attribute__((unused)) = 0ULL;
    uint64_t i __attribute__((unused)) = 0ULL;
    {
      while ((i < n_batch_cols)) {
        uint64_t cb __attribute__((unused)) = (i * 4ULL);
        uint32_t f_raw;
        if ((i < col_indices.len)) {
          uint64_t col_idx __attribute__((unused)) = ((uint64_t)col_indices.data[i]);
          if ((col_idx < col_ptrs.len)) {
            forge_span_u32_t col __attribute__((unused)) = col_ptrs.data[col_idx];
            if ((row < col.len)) {
              f_raw = col.data[row];
            } else {
              f_raw = 0ULL;
            }
          } else {
            f_raw = 0ULL;
          }
        } else {
          f_raw = 0ULL;
        }
        uint32_t f __attribute__((unused)) = reduce_word(f_raw);
        uint32_t t0_raw;
        if (((cb + 3ULL) < c_coeffs.len)) {
          if (((cb + 3ULL) < b_coeffs.len)) {
            uint32_t c0 __attribute__((unused)) = (c_coeffs.data[cb] % M31_P);
            uint32_t b0 __attribute__((unused)) = (b_coeffs.data[cb] % M31_P);
            t0_raw = m31_sub(m31_mul(c0, f), b0);
          } else {
            t0_raw = 0ULL;
          }
        } else {
          t0_raw = 0ULL;
        }
        uint32_t t0 __attribute__((unused)) = (t0_raw % M31_P);
        uint32_t t1_raw;
        if (((cb + 3ULL) < c_coeffs.len)) {
          if (((cb + 3ULL) < b_coeffs.len)) {
            uint32_t c1 __attribute__((unused)) = (c_coeffs.data[(cb + 1ULL)] % M31_P);
            uint32_t b1 __attribute__((unused)) = (b_coeffs.data[(cb + 1ULL)] % M31_P);
            t1_raw = m31_sub(m31_mul(c1, f), b1);
          } else {
            t1_raw = 0ULL;
          }
        } else {
          t1_raw = 0ULL;
        }
        uint32_t t1 __attribute__((unused)) = (t1_raw % M31_P);
        uint32_t t2_raw;
        if (((cb + 3ULL) < c_coeffs.len)) {
          if (((cb + 3ULL) < b_coeffs.len)) {
            uint32_t c2 __attribute__((unused)) = (c_coeffs.data[(cb + 2ULL)] % M31_P);
            uint32_t b2 __attribute__((unused)) = (b_coeffs.data[(cb + 2ULL)] % M31_P);
            t2_raw = m31_sub(m31_mul(c2, f), b2);
          } else {
            t2_raw = 0ULL;
          }
        } else {
          t2_raw = 0ULL;
        }
        uint32_t t2 __attribute__((unused)) = (t2_raw % M31_P);
        uint32_t t3_raw;
        if (((cb + 3ULL) < c_coeffs.len)) {
          if (((cb + 3ULL) < b_coeffs.len)) {
            uint32_t c3 __attribute__((unused)) = (c_coeffs.data[(cb + 3ULL)] % M31_P);
            uint32_t b3 __attribute__((unused)) = (b_coeffs.data[(cb + 3ULL)] % M31_P);
            t3_raw = m31_sub(m31_mul(c3, f), b3);
          } else {
            t3_raw = 0ULL;
          }
        } else {
          t3_raw = 0ULL;
        }
        uint32_t t3 __attribute__((unused)) = (t3_raw % M31_P);
        a0 = m31_add(a0, t0);
        a1 = m31_add(a1, t1);
        a2 = m31_add(a2, t2);
        a3 = m31_add(a3, t3);
        i = (i + 1ULL);
      }

    }
    out0.data[row] = a0;
    out1.data[row] = a1;
    out2.data[row] = a2;
    out3.data[row] = a3;

  }
}

int __attribute__((weak)) main() {
  return (int)(0);

}

