/* Generated by FORGE compiler — do not edit.
   All proof obligations discharged. This code is correct by construction. */

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#ifndef __GNUC__
#  define __attribute__(x)
#endif

/* FORGE GPU built-in aliases — FORGE flat names → CUDA struct members */
#define threadIdx_x ((uint32_t)(threadIdx.x))
#define threadIdx_y ((uint32_t)(threadIdx.y))
#define threadIdx_z ((uint32_t)(threadIdx.z))
#define blockIdx_x  ((uint32_t)(blockIdx.x))
#define blockIdx_y  ((uint32_t)(blockIdx.y))
#define blockIdx_z  ((uint32_t)(blockIdx.z))
#define blockDim_x  ((uint32_t)(blockDim.x))
#define blockDim_y  ((uint32_t)(blockDim.y))
#define blockDim_z  ((uint32_t)(blockDim.z))
#define gridDim_x   ((uint32_t)(gridDim.x))
#define gridDim_y   ((uint32_t)(gridDim.y))
#define gridDim_z   ((uint32_t)(gridDim.z))

#ifdef __SIZEOF_INT128__
typedef unsigned __int128 u256;
typedef unsigned __int128 u512;
typedef unsigned __int128 u1024;
typedef unsigned __int128 bv256;
#else
typedef uint64_t u256;
typedef uint64_t u512;
typedef uint64_t u1024;
typedef uint64_t bv256;
#endif
#ifdef __cplusplus
#  define FORGE_AGG(T, ...) (T{__VA_ARGS__})
#else
#  define FORGE_AGG(T, ...) ((T){__VA_ARGS__})
#endif

/* span<T> typedefs — fat pointers with proven bounds */
typedef struct { uint32_t* data; uintptr_t len; } forge_span_u32_t;
typedef struct { forge_span_u32_t* data; uintptr_t len; } forge_span_span_u32_t;

/* Function pointer typedefs */
typedef uint64_t (*forge_fn_u64_u64_u64_ret_u64_t)(uint64_t, uint64_t, uint64_t);
typedef uint64_t (*forge_fn_ptr_u64_u64_ret_u64_t)(uint64_t*, uint64_t);
typedef uint64_t (*forge_fn_u64_ret_u64_t)(uint64_t);
typedef uint64_t (*forge_fn__ret_u64_t)(void);
typedef float (*forge_fn_f32_u64_u64_ret_f32_t)(float, uint64_t, uint64_t);

__device__ uint64_t shfl_down_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t shfl_xor_sync(uint64_t val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_add(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_cas(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_max(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_min(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t shfl_up_sync(uint64_t val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

__device__ uint64_t atom_or(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_xor(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_and(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_sub(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t atom_exch(uint64_t* ptr, uint64_t val);  /* extern: forge_gpu */

__device__ uint64_t ballot_sync(uint64_t pred);  /* extern: forge_gpu */

__device__ uint64_t lane_id(void);  /* extern: forge_gpu */

__device__ uint64_t warp_id(void);  /* extern: forge_gpu */

__device__ float shfl_xor_sync_f32(float val, uint64_t mask, uint64_t width);  /* extern: forge_gpu */

__device__ float shfl_down_sync_f32(float val, uint64_t delta, uint64_t width);  /* extern: forge_gpu */

static const uint32_t M31_P = 2147483647ULL;

/* Forward declarations */
static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused)));
static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused)));
uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused)));
uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __host__ __device__ __forceinline__ uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t m31_neg(uint32_t a __attribute__((unused)));
uint32_t m31_double(uint32_t a __attribute__((unused)));
uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused)));
uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused)));
uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused)));
uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused)));
static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused)));
__global__ void accumulate_numerators_dual(forge_span_span_u32_t col_ptrs __attribute__((unused)), forge_span_u32_t col_indices_z __attribute__((unused)), forge_span_u32_t zn_coeff_idx __attribute__((unused)), forge_span_u32_t b_coeffs_z __attribute__((unused)), forge_span_u32_t c_coeffs_z __attribute__((unused)), forge_span_u32_t b_coeffs_zn __attribute__((unused)), forge_span_u32_t c_coeffs_zn __attribute__((unused)), uint64_t n_cols_z __attribute__((unused)), uint64_t n_rows __attribute__((unused)), forge_span_u32_t out_z0 __attribute__((unused)), forge_span_u32_t out_z1 __attribute__((unused)), forge_span_u32_t out_z2 __attribute__((unused)), forge_span_u32_t out_z3 __attribute__((unused)), forge_span_u32_t out_zn0 __attribute__((unused)), forge_span_u32_t out_zn1 __attribute__((unused)), forge_span_u32_t out_zn2 __attribute__((unused)), forge_span_u32_t out_zn3 __attribute__((unused)));
int main();

static __device__ __forceinline__ uint64_t warp_reduce_sum(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_max(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ uint64_t warp_reduce_min(uint64_t val __attribute__((unused))) {
  uint64_t v __attribute__((unused)) = val;
  uint64_t s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_sum_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  v = (v + __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL));
  v = (v + __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL));
  return v;
}

static __device__ __forceinline__ float warp_reduce_max_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s > v)) {
    v = s;

  }
  return v;
}

static __device__ __forceinline__ float warp_reduce_min_f32(float val __attribute__((unused))) {
  float v __attribute__((unused)) = val;
  float s __attribute__((unused)) = __shfl_xor_sync(0xffffffff, v, 16ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 8ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 4ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 2ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  s = __shfl_xor_sync(0xffffffff, v, 1ULL, 32ULL);
  if ((s < v)) {
    v = s;

  }
  return v;
}

uint64_t grid_stride_start(uint64_t block_idx __attribute__((unused)), uint64_t block_dim __attribute__((unused)), uint64_t thread_idx __attribute__((unused))) {
  return ((block_idx * block_dim) + thread_idx);
}

uint64_t grid_stride_step(uint64_t block_dim __attribute__((unused)), uint64_t grid_dim __attribute__((unused))) {
  return (block_dim * grid_dim);
}

static __host__ __device__ __forceinline__ uint32_t m31_add(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t s __attribute__((unused)) = (((uint64_t)a) + ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((s >= p)) {
    r = (s - p);
  } else {
    r = s;
  }
  return ((uint32_t)r);
}

static __host__ __device__ __forceinline__ uint32_t m31_sub(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t a64 __attribute__((unused)) = ((uint64_t)a);
  uint64_t b64 __attribute__((unused)) = ((uint64_t)b);
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r;
  if ((a64 >= b64)) {
    r = (a64 - b64);
  } else {
    r = ((a64 + p) - b64);
  }
  return ((uint32_t)r);
}

static __host__ __device__ __forceinline__ uint32_t m31_mul(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  uint64_t prod __attribute__((unused)) = (((uint64_t)a) * ((uint64_t)b));
  uint64_t p __attribute__((unused)) = ((uint64_t)M31_P);
  uint64_t r __attribute__((unused)) = (prod % p);
  return ((uint32_t)r);
}

uint32_t m31_neg(uint32_t a __attribute__((unused))) {
  if ((a == 0ULL)) {
    return 0ULL;
  } else {
    return (M31_P - a);
  }
}

uint32_t m31_double(uint32_t a __attribute__((unused))) {
  return m31_add(a, a);
}

uint32_t cm31_mul_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ac __attribute__((unused)) = m31_mul(a_re, b_re);
  uint32_t bd __attribute__((unused)) = m31_mul(a_im, b_im);
  return m31_sub(ac, bd);
}

uint32_t cm31_mul_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  uint32_t ad __attribute__((unused)) = m31_mul(a_re, b_im);
  uint32_t bc __attribute__((unused)) = m31_mul(a_im, b_re);
  return m31_add(ad, bc);
}

uint32_t cm31_add_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_add(a_re, b_re);
}

uint32_t cm31_add_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_add(a_im, b_im);
}

uint32_t cm31_sub_re(uint32_t a_re __attribute__((unused)), uint32_t b_re __attribute__((unused))) {
  return m31_sub(a_re, b_re);
}

uint32_t cm31_sub_im(uint32_t a_im __attribute__((unused)), uint32_t b_im __attribute__((unused))) {
  return m31_sub(a_im, b_im);
}

uint32_t qm31_mul_out_re_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_sub(m31_double(bd_re), bd_im);
  return m31_add(ac_re, t);
}

uint32_t qm31_mul_out_re_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ac_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, c_re, c_im);
  uint32_t bd_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, d_re, d_im);
  uint32_t bd_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, d_re, d_im);
  uint32_t t __attribute__((unused)) = m31_add(bd_re, m31_double(bd_im));
  return m31_add(ac_im, t);
}

uint32_t qm31_mul_out_im_re(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_re __attribute__((unused)) = cm31_mul_re(a_re, a_im, d_re, d_im);
  uint32_t bc_re __attribute__((unused)) = cm31_mul_re(b_re, b_im, c_re, c_im);
  return m31_add(ad_re, bc_re);
}

uint32_t qm31_mul_out_im_im(uint32_t a_re __attribute__((unused)), uint32_t a_im __attribute__((unused)), uint32_t b_re __attribute__((unused)), uint32_t b_im __attribute__((unused)), uint32_t c_re __attribute__((unused)), uint32_t c_im __attribute__((unused)), uint32_t d_re __attribute__((unused)), uint32_t d_im __attribute__((unused))) {
  uint32_t ad_im __attribute__((unused)) = cm31_mul_im(a_re, a_im, d_re, d_im);
  uint32_t bc_im __attribute__((unused)) = cm31_mul_im(b_re, b_im, c_re, c_im);
  return m31_add(ad_im, bc_im);
}

uint32_t qm31_add_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_add_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_add(a, b);
}

uint32_t qm31_sub_re_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_re_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_re(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

uint32_t qm31_sub_im_im(uint32_t a __attribute__((unused)), uint32_t b __attribute__((unused))) {
  return m31_sub(a, b);
}

static __device__ __forceinline__ uint32_t reduce_word(uint32_t v __attribute__((unused))) {
  uint32_t lo __attribute__((unused)) = (v & M31_P);
  uint32_t hi __attribute__((unused)) = (v >> 31ULL);
  uint32_t r __attribute__((unused)) = (lo + hi);
  if ((r >= M31_P)) {
    return (r - M31_P);
  } else {
    return r;
  }
}

__global__ void accumulate_numerators_dual(forge_span_span_u32_t col_ptrs __attribute__((unused)), forge_span_u32_t col_indices_z __attribute__((unused)), forge_span_u32_t zn_coeff_idx __attribute__((unused)), forge_span_u32_t b_coeffs_z __attribute__((unused)), forge_span_u32_t c_coeffs_z __attribute__((unused)), forge_span_u32_t b_coeffs_zn __attribute__((unused)), forge_span_u32_t c_coeffs_zn __attribute__((unused)), uint64_t n_cols_z __attribute__((unused)), uint64_t n_rows __attribute__((unused)), forge_span_u32_t out_z0 __attribute__((unused)), forge_span_u32_t out_z1 __attribute__((unused)), forge_span_u32_t out_z2 __attribute__((unused)), forge_span_u32_t out_z3 __attribute__((unused)), forge_span_u32_t out_zn0 __attribute__((unused)), forge_span_u32_t out_zn1 __attribute__((unused)), forge_span_u32_t out_zn2 __attribute__((unused)), forge_span_u32_t out_zn3 __attribute__((unused))) {
  uint64_t row __attribute__((unused)) = ((blockIdx_x * blockDim_x) + threadIdx_x);
  if ((row < n_rows)) {
    uint32_t az0 __attribute__((unused)) = 0ULL;
    uint32_t az1 __attribute__((unused)) = 0ULL;
    uint32_t az2 __attribute__((unused)) = 0ULL;
    uint32_t az3 __attribute__((unused)) = 0ULL;
    uint32_t an0 __attribute__((unused)) = 0ULL;
    uint32_t an1 __attribute__((unused)) = 0ULL;
    uint32_t an2 __attribute__((unused)) = 0ULL;
    uint32_t an3 __attribute__((unused)) = 0ULL;
    uint64_t i __attribute__((unused)) = 0ULL;
    {
      while ((i < n_cols_z)) {
        uint64_t cb __attribute__((unused)) = (i * 4ULL);
        uint32_t f_raw;
        if ((i < col_indices_z.len)) {
          uint64_t col_idx __attribute__((unused)) = ((uint64_t)col_indices_z.data[i]);
          if ((col_idx < col_ptrs.len)) {
            forge_span_u32_t col __attribute__((unused)) = col_ptrs.data[col_idx];
            if ((row < col.len)) {
              f_raw = col.data[row];
            } else {
              f_raw = 0ULL;
            }
          } else {
            f_raw = 0ULL;
          }
        } else {
          f_raw = 0ULL;
        }
        uint32_t f __attribute__((unused)) = reduce_word(f_raw);
        uint32_t tz0 __attribute__((unused)) = ((((cb + 3ULL) < c_coeffs_z.len) ? (((cb + 3ULL) < b_coeffs_z.len) ? m31_sub(m31_mul((c_coeffs_z.data[cb] % M31_P), f), (b_coeffs_z.data[cb] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tz1 __attribute__((unused)) = ((((cb + 3ULL) < c_coeffs_z.len) ? (((cb + 3ULL) < b_coeffs_z.len) ? m31_sub(m31_mul((c_coeffs_z.data[(cb + 1ULL)] % M31_P), f), (b_coeffs_z.data[(cb + 1ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tz2 __attribute__((unused)) = ((((cb + 3ULL) < c_coeffs_z.len) ? (((cb + 3ULL) < b_coeffs_z.len) ? m31_sub(m31_mul((c_coeffs_z.data[(cb + 2ULL)] % M31_P), f), (b_coeffs_z.data[(cb + 2ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tz3 __attribute__((unused)) = ((((cb + 3ULL) < c_coeffs_z.len) ? (((cb + 3ULL) < b_coeffs_z.len) ? m31_sub(m31_mul((c_coeffs_z.data[(cb + 3ULL)] % M31_P), f), (b_coeffs_z.data[(cb + 3ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        az0 = m31_add(az0, tz0);
        az1 = m31_add(az1, tz1);
        az2 = m31_add(az2, tz2);
        az3 = m31_add(az3, tz3);
        uint64_t zn_i;
        if ((i < zn_coeff_idx.len)) {
          zn_i = ((uint64_t)zn_coeff_idx.data[i]);
        } else {
          zn_i = 4294967295ULL;
        }
        uint64_t nb __attribute__((unused)) = (zn_i * 4ULL);
        uint32_t tn0 __attribute__((unused)) = ((((nb + 3ULL) < c_coeffs_zn.len) ? (((nb + 3ULL) < b_coeffs_zn.len) ? m31_sub(m31_mul((c_coeffs_zn.data[nb] % M31_P), f), (b_coeffs_zn.data[nb] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tn1 __attribute__((unused)) = ((((nb + 3ULL) < c_coeffs_zn.len) ? (((nb + 3ULL) < b_coeffs_zn.len) ? m31_sub(m31_mul((c_coeffs_zn.data[(nb + 1ULL)] % M31_P), f), (b_coeffs_zn.data[(nb + 1ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tn2 __attribute__((unused)) = ((((nb + 3ULL) < c_coeffs_zn.len) ? (((nb + 3ULL) < b_coeffs_zn.len) ? m31_sub(m31_mul((c_coeffs_zn.data[(nb + 2ULL)] % M31_P), f), (b_coeffs_zn.data[(nb + 2ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        uint32_t tn3 __attribute__((unused)) = ((((nb + 3ULL) < c_coeffs_zn.len) ? (((nb + 3ULL) < b_coeffs_zn.len) ? m31_sub(m31_mul((c_coeffs_zn.data[(nb + 3ULL)] % M31_P), f), (b_coeffs_zn.data[(nb + 3ULL)] % M31_P)) : 0ULL) : 0ULL) % M31_P);
        an0 = m31_add(an0, tn0);
        an1 = m31_add(an1, tn1);
        an2 = m31_add(an2, tn2);
        an3 = m31_add(an3, tn3);
        i = (i + 1ULL);
      }

    }
    out_z0.data[row] = az0;
    out_z1.data[row] = az1;
    out_z2.data[row] = az2;
    out_z3.data[row] = az3;
    out_zn0.data[row] = an0;
    out_zn1.data[row] = an1;
    out_zn2.data[row] = an2;
    out_zn3.data[row] = an3;

  }
}

int __attribute__((weak)) main() {
  return (int)(0);

}

